// Code generated by "stringer -type=MaterialBehavior"; DO NOT EDIT.

package mapping

import "strconv"

const _MaterialBehavior_name = "ScaleNoneScaleWidthScaleHeightScaleAll"

var _MaterialBehavior_index = [...]uint8{0, 9, 19, 30, 38}

func (i MaterialBehavior) String() string {
	if i < 0 || i >= MaterialBehavior(len(_MaterialBehavior_index)-1) {
		return "MaterialBehavior(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MaterialBehavior_name[_MaterialBehavior_index[i]:_MaterialBehavior_index[i+1]]
}
