// Code generated by "enumer -type=DynamicState -json"; DO NOT EDIT.

package dynamic

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _DynamicStateName = "SpawnNowPrevRenderDynamicStates"

var _DynamicStateIndex = [...]uint8{0, 5, 8, 12, 18, 31}

const _DynamicStateLowerName = "spawnnowprevrenderdynamicstates"

func (i DynamicState) String() string {
	if i < 0 || i >= DynamicState(len(_DynamicStateIndex)-1) {
		return fmt.Sprintf("DynamicState(%d)", i)
	}
	return _DynamicStateName[_DynamicStateIndex[i]:_DynamicStateIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _DynamicStateNoOp() {
	var x [1]struct{}
	_ = x[Spawn-(0)]
	_ = x[Now-(1)]
	_ = x[Prev-(2)]
	_ = x[Render-(3)]
	_ = x[DynamicStates-(4)]
}

var _DynamicStateValues = []DynamicState{Spawn, Now, Prev, Render, DynamicStates}

var _DynamicStateNameToValueMap = map[string]DynamicState{
	_DynamicStateName[0:5]:        Spawn,
	_DynamicStateLowerName[0:5]:   Spawn,
	_DynamicStateName[5:8]:        Now,
	_DynamicStateLowerName[5:8]:   Now,
	_DynamicStateName[8:12]:       Prev,
	_DynamicStateLowerName[8:12]:  Prev,
	_DynamicStateName[12:18]:      Render,
	_DynamicStateLowerName[12:18]: Render,
	_DynamicStateName[18:31]:      DynamicStates,
	_DynamicStateLowerName[18:31]: DynamicStates,
}

var _DynamicStateNames = []string{
	_DynamicStateName[0:5],
	_DynamicStateName[5:8],
	_DynamicStateName[8:12],
	_DynamicStateName[12:18],
	_DynamicStateName[18:31],
}

// DynamicStateString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func DynamicStateString(s string) (DynamicState, error) {
	if val, ok := _DynamicStateNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _DynamicStateNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to DynamicState values", s)
}

// DynamicStateValues returns all values of the enum
func DynamicStateValues() []DynamicState {
	return _DynamicStateValues
}

// DynamicStateStrings returns a slice of all String values of the enum
func DynamicStateStrings() []string {
	strs := make([]string, len(_DynamicStateNames))
	copy(strs, _DynamicStateNames)
	return strs
}

// IsADynamicState returns "true" if the value is listed in the enum definition. "false" otherwise
func (i DynamicState) IsADynamicState() bool {
	for _, v := range _DynamicStateValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for DynamicState
func (i DynamicState) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for DynamicState
func (i *DynamicState) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("DynamicState should be a string, got %s", data)
	}

	var err error
	*i, err = DynamicStateString(s)
	return err
}
