// Code generated by "enumer -type=DynamicStage -json"; DO NOT EDIT.

package dynamic

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _DynamicStageName = "DynamicOriginalDynamicPrevDynamicRenderDynamicNow"

var _DynamicStageIndex = [...]uint8{0, 15, 26, 39, 49}

const _DynamicStageLowerName = "dynamicoriginaldynamicprevdynamicrenderdynamicnow"

func (i DynamicStage) String() string {
	if i < 0 || i >= DynamicStage(len(_DynamicStageIndex)-1) {
		return fmt.Sprintf("DynamicStage(%d)", i)
	}
	return _DynamicStageName[_DynamicStageIndex[i]:_DynamicStageIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _DynamicStageNoOp() {
	var x [1]struct{}
	_ = x[DynamicSpawn-(0)]
	_ = x[DynamicPrev-(1)]
	_ = x[DynamicRender-(2)]
	_ = x[DynamicNow-(3)]
}

var _DynamicStageValues = []DynamicStage{DynamicSpawn, DynamicPrev, DynamicRender, DynamicNow}

var _DynamicStageNameToValueMap = map[string]DynamicStage{
	_DynamicStageName[0:15]:       DynamicSpawn,
	_DynamicStageLowerName[0:15]:  DynamicSpawn,
	_DynamicStageName[15:26]:      DynamicPrev,
	_DynamicStageLowerName[15:26]: DynamicPrev,
	_DynamicStageName[26:39]:      DynamicRender,
	_DynamicStageLowerName[26:39]: DynamicRender,
	_DynamicStageName[39:49]:      DynamicNow,
	_DynamicStageLowerName[39:49]: DynamicNow,
}

var _DynamicStageNames = []string{
	_DynamicStageName[0:15],
	_DynamicStageName[15:26],
	_DynamicStageName[26:39],
	_DynamicStageName[39:49],
}

// DynamicStageString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func DynamicStageString(s string) (DynamicStage, error) {
	if val, ok := _DynamicStageNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _DynamicStageNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to DynamicStage values", s)
}

// DynamicStageValues returns all values of the enum
func DynamicStageValues() []DynamicStage {
	return _DynamicStageValues
}

// DynamicStageStrings returns a slice of all String values of the enum
func DynamicStageStrings() []string {
	strs := make([]string, len(_DynamicStageNames))
	copy(strs, _DynamicStageNames)
	return strs
}

// IsADynamicStage returns "true" if the value is listed in the enum definition. "false" otherwise
func (i DynamicStage) IsADynamicStage() bool {
	for _, v := range _DynamicStageValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for DynamicStage
func (i DynamicStage) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for DynamicStage
func (i *DynamicStage) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("DynamicStage should be a string, got %s", data)
	}

	var err error
	*i, err = DynamicStageString(s)
	return err
}
