version: 2

# For cross-compiling to Windows/Linux:
# 1. Install mingw-64 for Windows: brew install mingw-w64
# 2. Install cross-compilers for linux:
# brew tap messense/macos-cross-toolchains
# brew install x86_64-unknown-linux-gnu
# brew install aarch64-unknown-linux-gnu

env:
  - CGO_CFLAGS='-I/opt/local/include'
  - CGO_LDFLAGS='-L/opt/local/lib'
  - CGO_ENABLED=1
before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: gofoom-game
    binary: gofoom-game
    main: ./game
    goarch:
      - amd64
      - arm64
    goos:
      - linux
      - windows
      - darwin
    ignore:
      - goos: windows
        goarch: arm64
    env:
      - >-
        {{- if and (eq .Os "windows") (eq .Arch "amd64") -}}
          CXX='x86_64-w64-mingw32-g++'
        {{- end }}
      - >-
        {{- if and (eq .Os "windows") (eq .Arch "amd64") -}}
          CC='x86_64-w64-mingw32-gcc'
        {{- end }}
      - >-
        {{- if and (eq .Os "linux") (eq .Arch "amd64") -}}
          CXX='x86_64-linux-gnu-g++'
        {{- end }}
      - >-
        {{- if and (eq .Os "linux") (eq .Arch "amd64") -}}
          CC='x86_64-linux-gnu-gcc'
        {{- end }}
      - >-
        {{- if and (eq .Os "linux") (eq .Arch "arm64") -}}
          CXX='aarch64-linux-gnu-g++'
        {{- end }}
      - >-
        {{- if and (eq .Os "linux") (eq .Arch "arm64") -}}
          CC='aarch64-linux-gnu-gcc'
        {{- end }}

  - id: gofoom-editor
    binary: gofoom-editor
    main: ./editor
    goarch:
      - amd64
      - arm64
    goos:
      - linux
      - windows
      - darwin
    ignore:
      - goos: windows
        goarch: arm64
    env:
      - >-
        {{- if and (eq .Os "windows") (eq .Arch "amd64") -}}
          CXX='x86_64-w64-mingw32-g++'
        {{- end }}
      - >-
        {{- if and (eq .Os "windows") (eq .Arch "amd64") -}}
          CC='x86_64-w64-mingw32-gcc'
        {{- end }}
      - >-
        {{- if and (eq .Os "linux") (eq .Arch "amd64") -}}
          CXX='x86_64-linux-gnu-g++'
        {{- end }}
      - >-
        {{- if and (eq .Os "linux") (eq .Arch "amd64") -}}
          CC='x86_64-linux-gnu-gcc'
        {{- end }}
      - >-
        {{- if and (eq .Os "linux") (eq .Arch "arm64") -}}
          CXX='aarch64-linux-gnu-g++'
        {{- end }}
      - >-
        {{- if and (eq .Os "linux") (eq .Arch "arm64") -}}
          CC='aarch64-linux-gnu-gcc'
        {{- end }}

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
