// Code generated by "enumer -type=ItemFlags -json"; DO NOT EDIT.

package inventory

import (
	"encoding/json"
	"fmt"
	"strings"
)

const (
	_ItemFlagsName_0      = "ItemBounceItemAutoProximity"
	_ItemFlagsLowerName_0 = "itembounceitemautoproximity"
	_ItemFlagsName_1      = "ItemAutoPlayerTargetable"
	_ItemFlagsLowerName_1 = "itemautoplayertargetable"
)

var (
	_ItemFlagsIndex_0 = [...]uint8{0, 10, 27}
	_ItemFlagsIndex_1 = [...]uint8{0, 24}
)

func (i ItemFlags) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _ItemFlagsName_0[_ItemFlagsIndex_0[i]:_ItemFlagsIndex_0[i+1]]
	case i == 4:
		return _ItemFlagsName_1
	default:
		return fmt.Sprintf("ItemFlags(%d)", i)
	}
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ItemFlagsNoOp() {
	var x [1]struct{}
	_ = x[ItemBounce-(1)]
	_ = x[ItemAutoProximity-(2)]
	_ = x[ItemAutoPlayerTargetable-(4)]
}

var _ItemFlagsValues = []ItemFlags{ItemBounce, ItemAutoProximity, ItemAutoPlayerTargetable}

var _ItemFlagsNameToValueMap = map[string]ItemFlags{
	_ItemFlagsName_0[0:10]:       ItemBounce,
	_ItemFlagsLowerName_0[0:10]:  ItemBounce,
	_ItemFlagsName_0[10:27]:      ItemAutoProximity,
	_ItemFlagsLowerName_0[10:27]: ItemAutoProximity,
	_ItemFlagsName_1[0:24]:       ItemAutoPlayerTargetable,
	_ItemFlagsLowerName_1[0:24]:  ItemAutoPlayerTargetable,
}

var _ItemFlagsNames = []string{
	_ItemFlagsName_0[0:10],
	_ItemFlagsName_0[10:27],
	_ItemFlagsName_1[0:24],
}

// ItemFlagsString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ItemFlagsString(s string) (ItemFlags, error) {
	if val, ok := _ItemFlagsNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ItemFlagsNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ItemFlags values", s)
}

// ItemFlagsValues returns all values of the enum
func ItemFlagsValues() []ItemFlags {
	return _ItemFlagsValues
}

// ItemFlagsStrings returns a slice of all String values of the enum
func ItemFlagsStrings() []string {
	strs := make([]string, len(_ItemFlagsNames))
	copy(strs, _ItemFlagsNames)
	return strs
}

// IsAItemFlags returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ItemFlags) IsAItemFlags() bool {
	for _, v := range _ItemFlagsValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for ItemFlags
func (i ItemFlags) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for ItemFlags
func (i *ItemFlags) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("ItemFlags should be a string, got %s", data)
	}

	var err error
	*i, err = ItemFlagsString(s)
	return err
}
