// Code generated by "enumer -type=WeaponIntent -json"; DO NOT EDIT.

package inventory

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _WeaponIntentName = "WeaponHeldWeaponFireWeaponHolstered"

var _WeaponIntentIndex = [...]uint8{0, 10, 20, 35}

const _WeaponIntentLowerName = "weaponheldweaponfireweaponholstered"

func (i WeaponIntent) String() string {
	if i < 0 || i >= WeaponIntent(len(_WeaponIntentIndex)-1) {
		return fmt.Sprintf("WeaponIntent(%d)", i)
	}
	return _WeaponIntentName[_WeaponIntentIndex[i]:_WeaponIntentIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _WeaponIntentNoOp() {
	var x [1]struct{}
	_ = x[WeaponHeld-(0)]
	_ = x[WeaponFire-(1)]
	_ = x[WeaponHolstered-(2)]
}

var _WeaponIntentValues = []WeaponIntent{WeaponHeld, WeaponFire, WeaponHolstered}

var _WeaponIntentNameToValueMap = map[string]WeaponIntent{
	_WeaponIntentName[0:10]:       WeaponHeld,
	_WeaponIntentLowerName[0:10]:  WeaponHeld,
	_WeaponIntentName[10:20]:      WeaponFire,
	_WeaponIntentLowerName[10:20]: WeaponFire,
	_WeaponIntentName[20:35]:      WeaponHolstered,
	_WeaponIntentLowerName[20:35]: WeaponHolstered,
}

var _WeaponIntentNames = []string{
	_WeaponIntentName[0:10],
	_WeaponIntentName[10:20],
	_WeaponIntentName[20:35],
}

// WeaponIntentString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func WeaponIntentString(s string) (WeaponIntent, error) {
	if val, ok := _WeaponIntentNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _WeaponIntentNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to WeaponIntent values", s)
}

// WeaponIntentValues returns all values of the enum
func WeaponIntentValues() []WeaponIntent {
	return _WeaponIntentValues
}

// WeaponIntentStrings returns a slice of all String values of the enum
func WeaponIntentStrings() []string {
	strs := make([]string, len(_WeaponIntentNames))
	copy(strs, _WeaponIntentNames)
	return strs
}

// IsAWeaponIntent returns "true" if the value is listed in the enum definition. "false" otherwise
func (i WeaponIntent) IsAWeaponIntent() bool {
	for _, v := range _WeaponIntentValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for WeaponIntent
func (i WeaponIntent) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for WeaponIntent
func (i *WeaponIntent) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("WeaponIntent should be a string, got %s", data)
	}

	var err error
	*i, err = WeaponIntentString(s)
	return err
}
