// Code generated by "enumer -type=WeaponState -json"; DO NOT EDIT.

package inventory

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _WeaponStateName = "WeaponIdleWeaponUnholsteringWeaponFiringWeaponCoolingWeaponReloadingWeaponHolsteringWeaponStateCount"

var _WeaponStateIndex = [...]uint8{0, 10, 28, 40, 53, 68, 84, 100}

const _WeaponStateLowerName = "weaponidleweaponunholsteringweaponfiringweaponcoolingweaponreloadingweaponholsteringweaponstatecount"

func (i WeaponState) String() string {
	if i < 0 || i >= WeaponState(len(_WeaponStateIndex)-1) {
		return fmt.Sprintf("WeaponState(%d)", i)
	}
	return _WeaponStateName[_WeaponStateIndex[i]:_WeaponStateIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _WeaponStateNoOp() {
	var x [1]struct{}
	_ = x[WeaponIdle-(0)]
	_ = x[WeaponUnholstering-(1)]
	_ = x[WeaponFiring-(2)]
	_ = x[WeaponCooling-(3)]
	_ = x[WeaponReloading-(4)]
	_ = x[WeaponHolstering-(5)]
	_ = x[WeaponStateCount-(6)]
}

var _WeaponStateValues = []WeaponState{WeaponIdle, WeaponUnholstering, WeaponFiring, WeaponCooling, WeaponReloading, WeaponHolstering, WeaponStateCount}

var _WeaponStateNameToValueMap = map[string]WeaponState{
	_WeaponStateName[0:10]:        WeaponIdle,
	_WeaponStateLowerName[0:10]:   WeaponIdle,
	_WeaponStateName[10:28]:       WeaponUnholstering,
	_WeaponStateLowerName[10:28]:  WeaponUnholstering,
	_WeaponStateName[28:40]:       WeaponFiring,
	_WeaponStateLowerName[28:40]:  WeaponFiring,
	_WeaponStateName[40:53]:       WeaponCooling,
	_WeaponStateLowerName[40:53]:  WeaponCooling,
	_WeaponStateName[53:68]:       WeaponReloading,
	_WeaponStateLowerName[53:68]:  WeaponReloading,
	_WeaponStateName[68:84]:       WeaponHolstering,
	_WeaponStateLowerName[68:84]:  WeaponHolstering,
	_WeaponStateName[84:100]:      WeaponStateCount,
	_WeaponStateLowerName[84:100]: WeaponStateCount,
}

var _WeaponStateNames = []string{
	_WeaponStateName[0:10],
	_WeaponStateName[10:28],
	_WeaponStateName[28:40],
	_WeaponStateName[40:53],
	_WeaponStateName[53:68],
	_WeaponStateName[68:84],
	_WeaponStateName[84:100],
}

// WeaponStateString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func WeaponStateString(s string) (WeaponState, error) {
	if val, ok := _WeaponStateNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _WeaponStateNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to WeaponState values", s)
}

// WeaponStateValues returns all values of the enum
func WeaponStateValues() []WeaponState {
	return _WeaponStateValues
}

// WeaponStateStrings returns a slice of all String values of the enum
func WeaponStateStrings() []string {
	strs := make([]string, len(_WeaponStateNames))
	copy(strs, _WeaponStateNames)
	return strs
}

// IsAWeaponState returns "true" if the value is listed in the enum definition. "false" otherwise
func (i WeaponState) IsAWeaponState() bool {
	for _, v := range _WeaponStateValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for WeaponState
func (i WeaponState) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for WeaponState
func (i *WeaponState) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("WeaponState should be a string, got %s", data)
	}

	var err error
	*i, err = WeaponStateString(s)
	return err
}
