// Code generated by ecs/cmd/gofoom_ecs_generator. DO NOT EDIT.
package inventory

import "tlyakhov/gofoom/ecs"

var CarrierCID ecs.ComponentID
var ItemCID ecs.ComponentID
var SlotCID ecs.ComponentID
var WeaponCID ecs.ComponentID
var WeaponClassCID ecs.ComponentID
var WeaponClassInstantCID ecs.ComponentID
var WeaponClassProjectileCID ecs.ComponentID

func init() {
	CarrierCID = ecs.RegisterComponent(&ecs.Arena[Carrier, *Carrier]{})
	ItemCID = ecs.RegisterComponent(&ecs.Arena[Item, *Item]{})
	SlotCID = ecs.RegisterComponent(&ecs.Arena[Slot, *Slot]{})
	WeaponCID = ecs.RegisterComponent(&ecs.Arena[Weapon, *Weapon]{})
	WeaponClassCID = ecs.RegisterComponent(&ecs.Arena[WeaponClass, *WeaponClass]{})
	WeaponClassInstantCID = ecs.RegisterComponent(&ecs.Arena[WeaponClassInstant, *WeaponClassInstant]{})
	WeaponClassProjectileCID = ecs.RegisterComponent(&ecs.Arena[WeaponClassProjectile, *WeaponClassProjectile]{})
}
func GetCarrier(e ecs.Entity) *Carrier {
	if asserted, ok := ecs.GetComponent(e, CarrierCID).(*Carrier); ok {
		return asserted
	}
	return nil
}

func (*Carrier) ComponentID() ecs.ComponentID {
	return CarrierCID
}
func GetItem(e ecs.Entity) *Item {
	if asserted, ok := ecs.GetComponent(e, ItemCID).(*Item); ok {
		return asserted
	}
	return nil
}

func (*Item) ComponentID() ecs.ComponentID {
	return ItemCID
}
func GetSlot(e ecs.Entity) *Slot {
	if asserted, ok := ecs.GetComponent(e, SlotCID).(*Slot); ok {
		return asserted
	}
	return nil
}

func (*Slot) ComponentID() ecs.ComponentID {
	return SlotCID
}
func GetWeapon(e ecs.Entity) *Weapon {
	if asserted, ok := ecs.GetComponent(e, WeaponCID).(*Weapon); ok {
		return asserted
	}
	return nil
}

func (*Weapon) ComponentID() ecs.ComponentID {
	return WeaponCID
}
func GetWeaponClass(e ecs.Entity) *WeaponClass {
	if asserted, ok := ecs.GetComponent(e, WeaponClassCID).(*WeaponClass); ok {
		return asserted
	}
	return nil
}

func (*WeaponClass) ComponentID() ecs.ComponentID {
	return WeaponClassCID
}
func GetWeaponClassInstant(e ecs.Entity) *WeaponClassInstant {
	if asserted, ok := ecs.GetComponent(e, WeaponClassInstantCID).(*WeaponClassInstant); ok {
		return asserted
	}
	return nil
}

func (*WeaponClassInstant) ComponentID() ecs.ComponentID {
	return WeaponClassInstantCID
}
func GetWeaponClassProjectile(e ecs.Entity) *WeaponClassProjectile {
	if asserted, ok := ecs.GetComponent(e, WeaponClassProjectileCID).(*WeaponClassProjectile); ok {
		return asserted
	}
	return nil
}

func (*WeaponClassProjectile) ComponentID() ecs.ComponentID {
	return WeaponClassProjectileCID
}
