// Code generated by "enumer -type=AutoSpawn -json"; DO NOT EDIT.

package behaviors

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _AutoSpawnName = "AutoSpawnNoneAutoSpawnOnLoadAutoSpawnDeleteOnLoad"

var _AutoSpawnIndex = [...]uint8{0, 13, 28, 49}

const _AutoSpawnLowerName = "autospawnnoneautospawnonloadautospawndeleteonload"

func (i AutoSpawn) String() string {
	if i < 0 || i >= AutoSpawn(len(_AutoSpawnIndex)-1) {
		return fmt.Sprintf("AutoSpawn(%d)", i)
	}
	return _AutoSpawnName[_AutoSpawnIndex[i]:_AutoSpawnIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _AutoSpawnNoOp() {
	var x [1]struct{}
	_ = x[AutoSpawnNone-(0)]
	_ = x[AutoSpawnOnLoad-(1)]
	_ = x[AutoSpawnDeleteOnLoad-(2)]
}

var _AutoSpawnValues = []AutoSpawn{AutoSpawnNone, AutoSpawnOnLoad, AutoSpawnDeleteOnLoad}

var _AutoSpawnNameToValueMap = map[string]AutoSpawn{
	_AutoSpawnName[0:13]:       AutoSpawnNone,
	_AutoSpawnLowerName[0:13]:  AutoSpawnNone,
	_AutoSpawnName[13:28]:      AutoSpawnOnLoad,
	_AutoSpawnLowerName[13:28]: AutoSpawnOnLoad,
	_AutoSpawnName[28:49]:      AutoSpawnDeleteOnLoad,
	_AutoSpawnLowerName[28:49]: AutoSpawnDeleteOnLoad,
}

var _AutoSpawnNames = []string{
	_AutoSpawnName[0:13],
	_AutoSpawnName[13:28],
	_AutoSpawnName[28:49],
}

// AutoSpawnString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func AutoSpawnString(s string) (AutoSpawn, error) {
	if val, ok := _AutoSpawnNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _AutoSpawnNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to AutoSpawn values", s)
}

// AutoSpawnValues returns all values of the enum
func AutoSpawnValues() []AutoSpawn {
	return _AutoSpawnValues
}

// AutoSpawnStrings returns a slice of all String values of the enum
func AutoSpawnStrings() []string {
	strs := make([]string, len(_AutoSpawnNames))
	copy(strs, _AutoSpawnNames)
	return strs
}

// IsAAutoSpawn returns "true" if the value is listed in the enum definition. "false" otherwise
func (i AutoSpawn) IsAAutoSpawn() bool {
	for _, v := range _AutoSpawnValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for AutoSpawn
func (i AutoSpawn) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for AutoSpawn
func (i *AutoSpawn) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("AutoSpawn should be a string, got %s", data)
	}

	var err error
	*i, err = AutoSpawnString(s)
	return err
}
