// Code generated by "enumer -type=DoorType -json"; DO NOT EDIT.

package behaviors

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _DoorTypeName = "DoorTypeVerticalDoorTypeSwing"

var _DoorTypeIndex = [...]uint8{0, 16, 29}

const _DoorTypeLowerName = "doortypeverticaldoortypeswing"

func (i DoorType) String() string {
	if i < 0 || i >= DoorType(len(_DoorTypeIndex)-1) {
		return fmt.Sprintf("DoorType(%d)", i)
	}
	return _DoorTypeName[_DoorTypeIndex[i]:_DoorTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _DoorTypeNoOp() {
	var x [1]struct{}
	_ = x[DoorTypeVertical-(0)]
	_ = x[DoorTypeSwing-(1)]
}

var _DoorTypeValues = []DoorType{DoorTypeVertical, DoorTypeSwing}

var _DoorTypeNameToValueMap = map[string]DoorType{
	_DoorTypeName[0:16]:       DoorTypeVertical,
	_DoorTypeLowerName[0:16]:  DoorTypeVertical,
	_DoorTypeName[16:29]:      DoorTypeSwing,
	_DoorTypeLowerName[16:29]: DoorTypeSwing,
}

var _DoorTypeNames = []string{
	_DoorTypeName[0:16],
	_DoorTypeName[16:29],
}

// DoorTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func DoorTypeString(s string) (DoorType, error) {
	if val, ok := _DoorTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _DoorTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to DoorType values", s)
}

// DoorTypeValues returns all values of the enum
func DoorTypeValues() []DoorType {
	return _DoorTypeValues
}

// DoorTypeStrings returns a slice of all String values of the enum
func DoorTypeStrings() []string {
	strs := make([]string, len(_DoorTypeNames))
	copy(strs, _DoorTypeNames)
	return strs
}

// IsADoorType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i DoorType) IsADoorType() bool {
	for _, v := range _DoorTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for DoorType
func (i DoorType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for DoorType
func (i *DoorType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("DoorType should be a string, got %s", data)
	}

	var err error
	*i, err = DoorTypeString(s)
	return err
}
