// Code generated by "enumer -type=DoorState -json"; DO NOT EDIT.

package behaviors

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _DoorStateName = "DoorStateOpenDoorStateOpeningDoorStateClosingDoorStateClosed"

var _DoorStateIndex = [...]uint8{0, 13, 29, 45, 60}

const _DoorStateLowerName = "doorstateopendoorstateopeningdoorstateclosingdoorstateclosed"

func (i DoorState) String() string {
	if i < 0 || i >= DoorState(len(_DoorStateIndex)-1) {
		return fmt.Sprintf("DoorState(%d)", i)
	}
	return _DoorStateName[_DoorStateIndex[i]:_DoorStateIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _DoorStateNoOp() {
	var x [1]struct{}
	_ = x[DoorStateOpen-(0)]
	_ = x[DoorStateOpening-(1)]
	_ = x[DoorStateClosing-(2)]
	_ = x[DoorStateClosed-(3)]
}

var _DoorStateValues = []DoorState{DoorStateOpen, DoorStateOpening, DoorStateClosing, DoorStateClosed}

var _DoorStateNameToValueMap = map[string]DoorState{
	_DoorStateName[0:13]:       DoorStateOpen,
	_DoorStateLowerName[0:13]:  DoorStateOpen,
	_DoorStateName[13:29]:      DoorStateOpening,
	_DoorStateLowerName[13:29]: DoorStateOpening,
	_DoorStateName[29:45]:      DoorStateClosing,
	_DoorStateLowerName[29:45]: DoorStateClosing,
	_DoorStateName[45:60]:      DoorStateClosed,
	_DoorStateLowerName[45:60]: DoorStateClosed,
}

var _DoorStateNames = []string{
	_DoorStateName[0:13],
	_DoorStateName[13:29],
	_DoorStateName[29:45],
	_DoorStateName[45:60],
}

// DoorStateString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func DoorStateString(s string) (DoorState, error) {
	if val, ok := _DoorStateNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _DoorStateNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to DoorState values", s)
}

// DoorStateValues returns all values of the enum
func DoorStateValues() []DoorState {
	return _DoorStateValues
}

// DoorStateStrings returns a slice of all String values of the enum
func DoorStateStrings() []string {
	strs := make([]string, len(_DoorStateNames))
	copy(strs, _DoorStateNames)
	return strs
}

// IsADoorState returns "true" if the value is listed in the enum definition. "false" otherwise
func (i DoorState) IsADoorState() bool {
	for _, v := range _DoorStateValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for DoorState
func (i DoorState) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for DoorState
func (i *DoorState) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("DoorState should be a string, got %s", data)
	}

	var err error
	*i, err = DoorStateString(s)
	return err
}
