// Code generated by "enumer -type=InventoryItemFlags -json"; DO NOT EDIT.

package behaviors

import (
	"encoding/json"
	"fmt"
	"strings"
)

const (
	_InventoryItemFlagsName_0      = "InventoryItemBounceInventoryItemAutoProximity"
	_InventoryItemFlagsLowerName_0 = "inventoryitembounceinventoryitemautoproximity"
	_InventoryItemFlagsName_1      = "InventoryItemAutoPlayerTargetable"
	_InventoryItemFlagsLowerName_1 = "inventoryitemautoplayertargetable"
)

var (
	_InventoryItemFlagsIndex_0 = [...]uint8{0, 19, 45}
	_InventoryItemFlagsIndex_1 = [...]uint8{0, 33}
)

func (i InventoryItemFlags) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _InventoryItemFlagsName_0[_InventoryItemFlagsIndex_0[i]:_InventoryItemFlagsIndex_0[i+1]]
	case i == 4:
		return _InventoryItemFlagsName_1
	default:
		return fmt.Sprintf("InventoryItemFlags(%d)", i)
	}
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _InventoryItemFlagsNoOp() {
	var x [1]struct{}
	_ = x[InventoryItemBounce-(1)]
	_ = x[InventoryItemAutoProximity-(2)]
	_ = x[InventoryItemAutoPlayerTargetable-(4)]
}

var _InventoryItemFlagsValues = []InventoryItemFlags{InventoryItemBounce, InventoryItemAutoProximity, InventoryItemAutoPlayerTargetable}

var _InventoryItemFlagsNameToValueMap = map[string]InventoryItemFlags{
	_InventoryItemFlagsName_0[0:19]:       InventoryItemBounce,
	_InventoryItemFlagsLowerName_0[0:19]:  InventoryItemBounce,
	_InventoryItemFlagsName_0[19:45]:      InventoryItemAutoProximity,
	_InventoryItemFlagsLowerName_0[19:45]: InventoryItemAutoProximity,
	_InventoryItemFlagsName_1[0:33]:       InventoryItemAutoPlayerTargetable,
	_InventoryItemFlagsLowerName_1[0:33]:  InventoryItemAutoPlayerTargetable,
}

var _InventoryItemFlagsNames = []string{
	_InventoryItemFlagsName_0[0:19],
	_InventoryItemFlagsName_0[19:45],
	_InventoryItemFlagsName_1[0:33],
}

// InventoryItemFlagsString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func InventoryItemFlagsString(s string) (InventoryItemFlags, error) {
	if val, ok := _InventoryItemFlagsNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _InventoryItemFlagsNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to InventoryItemFlags values", s)
}

// InventoryItemFlagsValues returns all values of the enum
func InventoryItemFlagsValues() []InventoryItemFlags {
	return _InventoryItemFlagsValues
}

// InventoryItemFlagsStrings returns a slice of all String values of the enum
func InventoryItemFlagsStrings() []string {
	strs := make([]string, len(_InventoryItemFlagsNames))
	copy(strs, _InventoryItemFlagsNames)
	return strs
}

// IsAInventoryItemFlags returns "true" if the value is listed in the enum definition. "false" otherwise
func (i InventoryItemFlags) IsAInventoryItemFlags() bool {
	for _, v := range _InventoryItemFlagsValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for InventoryItemFlags
func (i InventoryItemFlags) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for InventoryItemFlags
func (i *InventoryItemFlags) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("InventoryItemFlags should be a string, got %s", data)
	}

	var err error
	*i, err = InventoryItemFlagsString(s)
	return err
}
