// Code generated by "enumer -type=ProximityFlags -json"; DO NOT EDIT.

package behaviors

import (
	"encoding/json"
	"fmt"
	"strings"
)

const (
	_ProximityFlagsName_0      = "ProximityOnBodyProximityOnSector"
	_ProximityFlagsLowerName_0 = "proximityonbodyproximityonsector"
	_ProximityFlagsName_1      = "ProximityTargetsBody"
	_ProximityFlagsLowerName_1 = "proximitytargetsbody"
	_ProximityFlagsName_2      = "ProximityTargetsSector"
	_ProximityFlagsLowerName_2 = "proximitytargetssector"
)

var (
	_ProximityFlagsIndex_0 = [...]uint8{0, 15, 32}
	_ProximityFlagsIndex_1 = [...]uint8{0, 20}
	_ProximityFlagsIndex_2 = [...]uint8{0, 22}
)

func (i ProximityFlags) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _ProximityFlagsName_0[_ProximityFlagsIndex_0[i]:_ProximityFlagsIndex_0[i+1]]
	case i == 4:
		return _ProximityFlagsName_1
	case i == 8:
		return _ProximityFlagsName_2
	default:
		return fmt.Sprintf("ProximityFlags(%d)", i)
	}
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ProximityFlagsNoOp() {
	var x [1]struct{}
	_ = x[ProximityOnBody-(1)]
	_ = x[ProximityOnSector-(2)]
	_ = x[ProximityTargetsBody-(4)]
	_ = x[ProximityTargetsSector-(8)]
}

var _ProximityFlagsValues = []ProximityFlags{ProximityOnBody, ProximityOnSector, ProximityTargetsBody, ProximityTargetsSector}

var _ProximityFlagsNameToValueMap = map[string]ProximityFlags{
	_ProximityFlagsName_0[0:15]:       ProximityOnBody,
	_ProximityFlagsLowerName_0[0:15]:  ProximityOnBody,
	_ProximityFlagsName_0[15:32]:      ProximityOnSector,
	_ProximityFlagsLowerName_0[15:32]: ProximityOnSector,
	_ProximityFlagsName_1[0:20]:       ProximityTargetsBody,
	_ProximityFlagsLowerName_1[0:20]:  ProximityTargetsBody,
	_ProximityFlagsName_2[0:22]:       ProximityTargetsSector,
	_ProximityFlagsLowerName_2[0:22]:  ProximityTargetsSector,
}

var _ProximityFlagsNames = []string{
	_ProximityFlagsName_0[0:15],
	_ProximityFlagsName_0[15:32],
	_ProximityFlagsName_1[0:20],
	_ProximityFlagsName_2[0:22],
}

// ProximityFlagsString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ProximityFlagsString(s string) (ProximityFlags, error) {
	if val, ok := _ProximityFlagsNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ProximityFlagsNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ProximityFlags values", s)
}

// ProximityFlagsValues returns all values of the enum
func ProximityFlagsValues() []ProximityFlags {
	return _ProximityFlagsValues
}

// ProximityFlagsStrings returns a slice of all String values of the enum
func ProximityFlagsStrings() []string {
	strs := make([]string, len(_ProximityFlagsNames))
	copy(strs, _ProximityFlagsNames)
	return strs
}

// IsAProximityFlags returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ProximityFlags) IsAProximityFlags() bool {
	for _, v := range _ProximityFlagsValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for ProximityFlags
func (i ProximityFlags) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for ProximityFlags
func (i *ProximityFlags) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("ProximityFlags should be a string, got %s", data)
	}

	var err error
	*i, err = ProximityFlagsString(s)
	return err
}
