// Code generated by "enumer -type=ProximityStatus -json"; DO NOT EDIT.

package behaviors

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _ProximityStatusName = "ProximityIdleProximityFiringProximityWaiting"

var _ProximityStatusIndex = [...]uint8{0, 13, 28, 44}

const _ProximityStatusLowerName = "proximityidleproximityfiringproximitywaiting"

func (i ProximityStatus) String() string {
	if i < 0 || i >= ProximityStatus(len(_ProximityStatusIndex)-1) {
		return fmt.Sprintf("ProximityStatus(%d)", i)
	}
	return _ProximityStatusName[_ProximityStatusIndex[i]:_ProximityStatusIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ProximityStatusNoOp() {
	var x [1]struct{}
	_ = x[ProximityIdle-(0)]
	_ = x[ProximityFiring-(1)]
	_ = x[ProximityWaiting-(2)]
}

var _ProximityStatusValues = []ProximityStatus{ProximityIdle, ProximityFiring, ProximityWaiting}

var _ProximityStatusNameToValueMap = map[string]ProximityStatus{
	_ProximityStatusName[0:13]:       ProximityIdle,
	_ProximityStatusLowerName[0:13]:  ProximityIdle,
	_ProximityStatusName[13:28]:      ProximityFiring,
	_ProximityStatusLowerName[13:28]: ProximityFiring,
	_ProximityStatusName[28:44]:      ProximityWaiting,
	_ProximityStatusLowerName[28:44]: ProximityWaiting,
}

var _ProximityStatusNames = []string{
	_ProximityStatusName[0:13],
	_ProximityStatusName[13:28],
	_ProximityStatusName[28:44],
}

// ProximityStatusString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ProximityStatusString(s string) (ProximityStatus, error) {
	if val, ok := _ProximityStatusNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ProximityStatusNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ProximityStatus values", s)
}

// ProximityStatusValues returns all values of the enum
func ProximityStatusValues() []ProximityStatus {
	return _ProximityStatusValues
}

// ProximityStatusStrings returns a slice of all String values of the enum
func ProximityStatusStrings() []string {
	strs := make([]string, len(_ProximityStatusNames))
	copy(strs, _ProximityStatusNames)
	return strs
}

// IsAProximityStatus returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ProximityStatus) IsAProximityStatus() bool {
	for _, v := range _ProximityStatusValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for ProximityStatus
func (i ProximityStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for ProximityStatus
func (i *ProximityStatus) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("ProximityStatus should be a string, got %s", data)
	}

	var err error
	*i, err = ProximityStatusString(s)
	return err
}
