// Code generated by ecs/cmd/gofoom_ecs_generator. DO NOT EDIT.
package behaviors

import "tlyakhov/gofoom/ecs"

var ActionFaceCID ecs.ComponentID
var ActionFireCID ecs.ComponentID
var ActionJumpCID ecs.ComponentID
var ActionTimedCID ecs.ComponentID
var ActionTransitionCID ecs.ComponentID
var ActionWaypointCID ecs.ComponentID
var ActorCID ecs.ComponentID
var ActorStateCID ecs.ComponentID
var AliveCID ecs.ComponentID
var ParticleEmitterCID ecs.ComponentID
var PlayerTargetableCID ecs.ComponentID
var ProximityCID ecs.ComponentID
var ProximityStateCID ecs.ComponentID
var UnderwaterCID ecs.ComponentID
var VerticalDoorCID ecs.ComponentID
var WanderCID ecs.ComponentID

func init() {
	ActionFaceCID = ecs.RegisterComponent(&ecs.Arena[ActionFace, *ActionFace]{})
	ActionFireCID = ecs.RegisterComponent(&ecs.Arena[ActionFire, *ActionFire]{})
	ActionJumpCID = ecs.RegisterComponent(&ecs.Arena[ActionJump, *ActionJump]{})
	ActionTimedCID = ecs.RegisterComponent(&ecs.Arena[ActionTimed, *ActionTimed]{})
	ActionTransitionCID = ecs.RegisterComponent(&ecs.Arena[ActionTransition, *ActionTransition]{})
	ActionWaypointCID = ecs.RegisterComponent(&ecs.Arena[ActionWaypoint, *ActionWaypoint]{})
	ActorCID = ecs.RegisterComponent(&ecs.Arena[Actor, *Actor]{})
	ActorStateCID = ecs.RegisterComponent(&ecs.Arena[ActorState, *ActorState]{})
	AliveCID = ecs.RegisterComponent(&ecs.Arena[Alive, *Alive]{})
	ParticleEmitterCID = ecs.RegisterComponent(&ecs.Arena[ParticleEmitter, *ParticleEmitter]{})
	PlayerTargetableCID = ecs.RegisterComponent(&ecs.Arena[PlayerTargetable, *PlayerTargetable]{})
	ProximityCID = ecs.RegisterComponent(&ecs.Arena[Proximity, *Proximity]{})
	ProximityStateCID = ecs.RegisterComponent(&ecs.Arena[ProximityState, *ProximityState]{})
	UnderwaterCID = ecs.RegisterComponent(&ecs.Arena[Underwater, *Underwater]{})
	VerticalDoorCID = ecs.RegisterComponent(&ecs.Arena[VerticalDoor, *VerticalDoor]{})
	WanderCID = ecs.RegisterComponent(&ecs.Arena[Wander, *Wander]{})
}
func GetActionFace(e ecs.Entity) *ActionFace {
	if asserted, ok := ecs.GetComponent(e, ActionFaceCID).(*ActionFace); ok {
		return asserted
	}
	return nil
}

func (*ActionFace) ComponentID() ecs.ComponentID {
	return ActionFaceCID
}
func GetActionFire(e ecs.Entity) *ActionFire {
	if asserted, ok := ecs.GetComponent(e, ActionFireCID).(*ActionFire); ok {
		return asserted
	}
	return nil
}

func (*ActionFire) ComponentID() ecs.ComponentID {
	return ActionFireCID
}
func GetActionJump(e ecs.Entity) *ActionJump {
	if asserted, ok := ecs.GetComponent(e, ActionJumpCID).(*ActionJump); ok {
		return asserted
	}
	return nil
}

func (*ActionJump) ComponentID() ecs.ComponentID {
	return ActionJumpCID
}
func GetActionTimed(e ecs.Entity) *ActionTimed {
	if asserted, ok := ecs.GetComponent(e, ActionTimedCID).(*ActionTimed); ok {
		return asserted
	}
	return nil
}

func (*ActionTimed) ComponentID() ecs.ComponentID {
	return ActionTimedCID
}
func GetActionTransition(e ecs.Entity) *ActionTransition {
	if asserted, ok := ecs.GetComponent(e, ActionTransitionCID).(*ActionTransition); ok {
		return asserted
	}
	return nil
}

func (*ActionTransition) ComponentID() ecs.ComponentID {
	return ActionTransitionCID
}
func GetActionWaypoint(e ecs.Entity) *ActionWaypoint {
	if asserted, ok := ecs.GetComponent(e, ActionWaypointCID).(*ActionWaypoint); ok {
		return asserted
	}
	return nil
}

func (*ActionWaypoint) ComponentID() ecs.ComponentID {
	return ActionWaypointCID
}
func GetActor(e ecs.Entity) *Actor {
	if asserted, ok := ecs.GetComponent(e, ActorCID).(*Actor); ok {
		return asserted
	}
	return nil
}

func (*Actor) ComponentID() ecs.ComponentID {
	return ActorCID
}
func GetActorState(e ecs.Entity) *ActorState {
	if asserted, ok := ecs.GetComponent(e, ActorStateCID).(*ActorState); ok {
		return asserted
	}
	return nil
}

func (*ActorState) ComponentID() ecs.ComponentID {
	return ActorStateCID
}
func GetAlive(e ecs.Entity) *Alive {
	if asserted, ok := ecs.GetComponent(e, AliveCID).(*Alive); ok {
		return asserted
	}
	return nil
}

func (*Alive) ComponentID() ecs.ComponentID {
	return AliveCID
}
func GetParticleEmitter(e ecs.Entity) *ParticleEmitter {
	if asserted, ok := ecs.GetComponent(e, ParticleEmitterCID).(*ParticleEmitter); ok {
		return asserted
	}
	return nil
}

func (*ParticleEmitter) ComponentID() ecs.ComponentID {
	return ParticleEmitterCID
}
func GetPlayerTargetable(e ecs.Entity) *PlayerTargetable {
	if asserted, ok := ecs.GetComponent(e, PlayerTargetableCID).(*PlayerTargetable); ok {
		return asserted
	}
	return nil
}

func (*PlayerTargetable) ComponentID() ecs.ComponentID {
	return PlayerTargetableCID
}
func GetProximity(e ecs.Entity) *Proximity {
	if asserted, ok := ecs.GetComponent(e, ProximityCID).(*Proximity); ok {
		return asserted
	}
	return nil
}

func (*Proximity) ComponentID() ecs.ComponentID {
	return ProximityCID
}
func GetProximityState(e ecs.Entity) *ProximityState {
	if asserted, ok := ecs.GetComponent(e, ProximityStateCID).(*ProximityState); ok {
		return asserted
	}
	return nil
}

func (*ProximityState) ComponentID() ecs.ComponentID {
	return ProximityStateCID
}
func GetUnderwater(e ecs.Entity) *Underwater {
	if asserted, ok := ecs.GetComponent(e, UnderwaterCID).(*Underwater); ok {
		return asserted
	}
	return nil
}

func (*Underwater) ComponentID() ecs.ComponentID {
	return UnderwaterCID
}
func GetVerticalDoor(e ecs.Entity) *VerticalDoor {
	if asserted, ok := ecs.GetComponent(e, VerticalDoorCID).(*VerticalDoor); ok {
		return asserted
	}
	return nil
}

func (*VerticalDoor) ComponentID() ecs.ComponentID {
	return VerticalDoorCID
}
func GetWander(e ecs.Entity) *Wander {
	if asserted, ok := ecs.GetComponent(e, WanderCID).(*Wander); ok {
		return asserted
	}
	return nil
}

func (*Wander) ComponentID() ecs.ComponentID {
	return WanderCID
}
