// Code generated by "enumer -type=SoundPlayMode -json"; DO NOT EDIT.

package audio

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _SoundPlayModeName = "SoundPlayNormalSoundPlayOnePerTagSoundPlayInterruptPerTag"

var _SoundPlayModeIndex = [...]uint8{0, 15, 33, 57}

const _SoundPlayModeLowerName = "soundplaynormalsoundplayonepertagsoundplayinterruptpertag"

func (i SoundPlayMode) String() string {
	if i < 0 || i >= SoundPlayMode(len(_SoundPlayModeIndex)-1) {
		return fmt.Sprintf("SoundPlayMode(%d)", i)
	}
	return _SoundPlayModeName[_SoundPlayModeIndex[i]:_SoundPlayModeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _SoundPlayModeNoOp() {
	var x [1]struct{}
	_ = x[SoundPlayNormal-(0)]
	_ = x[SoundPlayOnePerTag-(1)]
	_ = x[SoundPlayInterruptPerTag-(2)]
}

var _SoundPlayModeValues = []SoundPlayMode{SoundPlayNormal, SoundPlayOnePerTag, SoundPlayInterruptPerTag}

var _SoundPlayModeNameToValueMap = map[string]SoundPlayMode{
	_SoundPlayModeName[0:15]:       SoundPlayNormal,
	_SoundPlayModeLowerName[0:15]:  SoundPlayNormal,
	_SoundPlayModeName[15:33]:      SoundPlayOnePerTag,
	_SoundPlayModeLowerName[15:33]: SoundPlayOnePerTag,
	_SoundPlayModeName[33:57]:      SoundPlayInterruptPerTag,
	_SoundPlayModeLowerName[33:57]: SoundPlayInterruptPerTag,
}

var _SoundPlayModeNames = []string{
	_SoundPlayModeName[0:15],
	_SoundPlayModeName[15:33],
	_SoundPlayModeName[33:57],
}

// SoundPlayModeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func SoundPlayModeString(s string) (SoundPlayMode, error) {
	if val, ok := _SoundPlayModeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _SoundPlayModeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to SoundPlayMode values", s)
}

// SoundPlayModeValues returns all values of the enum
func SoundPlayModeValues() []SoundPlayMode {
	return _SoundPlayModeValues
}

// SoundPlayModeStrings returns a slice of all String values of the enum
func SoundPlayModeStrings() []string {
	strs := make([]string, len(_SoundPlayModeNames))
	copy(strs, _SoundPlayModeNames)
	return strs
}

// IsASoundPlayMode returns "true" if the value is listed in the enum definition. "false" otherwise
func (i SoundPlayMode) IsASoundPlayMode() bool {
	for _, v := range _SoundPlayModeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for SoundPlayMode
func (i SoundPlayMode) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for SoundPlayMode
func (i *SoundPlayMode) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("SoundPlayMode should be a string, got %s", data)
	}

	var err error
	*i, err = SoundPlayModeString(s)
	return err
}
