// Code generated by ecs/cmd/gofoom_ecs_generator. DO NOT EDIT.
package audio

import "tlyakhov/gofoom/ecs"

var MixerCID ecs.ComponentID
var SoundCID ecs.ComponentID
var SourceCID ecs.ComponentID

func init() {
	MixerCID = ecs.RegisterComponent(&ecs.Arena[Mixer, *Mixer]{})
	SoundCID = ecs.RegisterComponent(&ecs.Arena[Sound, *Sound]{})
	SourceCID = ecs.RegisterComponent(&ecs.Arena[Source, *Source]{})
}
func GetMixer(e ecs.Entity) *Mixer {
	panic("Tried to GetMixer, which is a singleton. use ecs.Singleton instead")
}

func (*Mixer) ComponentID() ecs.ComponentID {
	return MixerCID
}
func GetSound(e ecs.Entity) *Sound {
	if asserted, ok := ecs.Component(e, SoundCID).(*Sound); ok {
		return asserted
	}
	return nil
}

func (*Sound) ComponentID() ecs.ComponentID {
	return SoundCID
}
func GetSource(e ecs.Entity) *Source {
	if asserted, ok := ecs.Component(e, SourceCID).(*Source); ok {
		return asserted
	}
	return nil
}

func (*Source) ComponentID() ecs.ComponentID {
	return SourceCID
}
