// Code generated by ecs/cmd/gofoom_ecs_generator. DO NOT EDIT.
package audio

import "tlyakhov/gofoom/ecs"

var SoundCID ecs.ComponentID
var SoundEventCID ecs.ComponentID
var SourceCID ecs.ComponentID

func init() {
	SoundCID = ecs.RegisterComponent(&ecs.Arena[Sound, *Sound]{})
	SoundEventCID = ecs.RegisterComponent(&ecs.Arena[SoundEvent, *SoundEvent]{})
	SourceCID = ecs.RegisterComponent(&ecs.Arena[Source, *Source]{})
}
func GetSound(e ecs.Entity) *Sound {
	if asserted, ok := ecs.GetComponent(e, SoundCID).(*Sound); ok {
		return asserted
	}
	return nil
}

func (*Sound) ComponentID() ecs.ComponentID {
	return SoundCID
}
func GetSoundEvent(e ecs.Entity) *SoundEvent {
	if asserted, ok := ecs.GetComponent(e, SoundEventCID).(*SoundEvent); ok {
		return asserted
	}
	return nil
}

func (*SoundEvent) ComponentID() ecs.ComponentID {
	return SoundEventCID
}
func GetSource(e ecs.Entity) *Source {
	if asserted, ok := ecs.GetComponent(e, SourceCID).(*Source); ok {
		return asserted
	}
	return nil
}

func (*Source) ComponentID() ecs.ComponentID {
	return SourceCID
}
