// Code generated by "enumer -type=MaterialBehavior -json"; DO NOT EDIT.

package core

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _MaterialBehaviorName = "ScaleNoneScaleHeightScaleWidthScaleAll"

var _MaterialBehaviorIndex = [...]uint8{0, 9, 20, 30, 38}

const _MaterialBehaviorLowerName = "scalenonescaleheightscalewidthscaleall"

func (i MaterialBehavior) String() string {
	if i < 0 || i >= MaterialBehavior(len(_MaterialBehaviorIndex)-1) {
		return fmt.Sprintf("MaterialBehavior(%d)", i)
	}
	return _MaterialBehaviorName[_MaterialBehaviorIndex[i]:_MaterialBehaviorIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _MaterialBehaviorNoOp() {
	var x [1]struct{}
	_ = x[ScaleNone-(0)]
	_ = x[ScaleHeight-(1)]
	_ = x[ScaleWidth-(2)]
	_ = x[ScaleAll-(3)]
}

var _MaterialBehaviorValues = []MaterialBehavior{ScaleNone, ScaleHeight, ScaleWidth, ScaleAll}

var _MaterialBehaviorNameToValueMap = map[string]MaterialBehavior{
	_MaterialBehaviorName[0:9]:        ScaleNone,
	_MaterialBehaviorLowerName[0:9]:   ScaleNone,
	_MaterialBehaviorName[9:20]:       ScaleHeight,
	_MaterialBehaviorLowerName[9:20]:  ScaleHeight,
	_MaterialBehaviorName[20:30]:      ScaleWidth,
	_MaterialBehaviorLowerName[20:30]: ScaleWidth,
	_MaterialBehaviorName[30:38]:      ScaleAll,
	_MaterialBehaviorLowerName[30:38]: ScaleAll,
}

var _MaterialBehaviorNames = []string{
	_MaterialBehaviorName[0:9],
	_MaterialBehaviorName[9:20],
	_MaterialBehaviorName[20:30],
	_MaterialBehaviorName[30:38],
}

// MaterialBehaviorString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func MaterialBehaviorString(s string) (MaterialBehavior, error) {
	if val, ok := _MaterialBehaviorNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _MaterialBehaviorNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to MaterialBehavior values", s)
}

// MaterialBehaviorValues returns all values of the enum
func MaterialBehaviorValues() []MaterialBehavior {
	return _MaterialBehaviorValues
}

// MaterialBehaviorStrings returns a slice of all String values of the enum
func MaterialBehaviorStrings() []string {
	strs := make([]string, len(_MaterialBehaviorNames))
	copy(strs, _MaterialBehaviorNames)
	return strs
}

// IsAMaterialBehavior returns "true" if the value is listed in the enum definition. "false" otherwise
func (i MaterialBehavior) IsAMaterialBehavior() bool {
	for _, v := range _MaterialBehaviorValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for MaterialBehavior
func (i MaterialBehavior) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for MaterialBehavior
func (i *MaterialBehavior) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("MaterialBehavior should be a string, got %s", data)
	}

	var err error
	*i, err = MaterialBehaviorString(s)
	return err
}
