// Code generated by "enumer -type=PickedType -json"; DO NOT EDIT.

package state

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _PickedTypeName = "PickCeilingPickHighPickMidPickLowPickFloorPickBody"

var _PickedTypeIndex = [...]uint8{0, 11, 19, 26, 33, 42, 50}

const _PickedTypeLowerName = "pickceilingpickhighpickmidpicklowpickfloorpickbody"

func (i PickedType) String() string {
	if i < 0 || i >= PickedType(len(_PickedTypeIndex)-1) {
		return fmt.Sprintf("PickedType(%d)", i)
	}
	return _PickedTypeName[_PickedTypeIndex[i]:_PickedTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _PickedTypeNoOp() {
	var x [1]struct{}
	_ = x[PickCeiling-(0)]
	_ = x[PickHigh-(1)]
	_ = x[PickMid-(2)]
	_ = x[PickLow-(3)]
	_ = x[PickFloor-(4)]
	_ = x[PickBody-(5)]
}

var _PickedTypeValues = []PickedType{PickCeiling, PickHigh, PickMid, PickLow, PickFloor, PickBody}

var _PickedTypeNameToValueMap = map[string]PickedType{
	_PickedTypeName[0:11]:       PickCeiling,
	_PickedTypeLowerName[0:11]:  PickCeiling,
	_PickedTypeName[11:19]:      PickHigh,
	_PickedTypeLowerName[11:19]: PickHigh,
	_PickedTypeName[19:26]:      PickMid,
	_PickedTypeLowerName[19:26]: PickMid,
	_PickedTypeName[26:33]:      PickLow,
	_PickedTypeLowerName[26:33]: PickLow,
	_PickedTypeName[33:42]:      PickFloor,
	_PickedTypeLowerName[33:42]: PickFloor,
	_PickedTypeName[42:50]:      PickBody,
	_PickedTypeLowerName[42:50]: PickBody,
}

var _PickedTypeNames = []string{
	_PickedTypeName[0:11],
	_PickedTypeName[11:19],
	_PickedTypeName[19:26],
	_PickedTypeName[26:33],
	_PickedTypeName[33:42],
	_PickedTypeName[42:50],
}

// PickedTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func PickedTypeString(s string) (PickedType, error) {
	if val, ok := _PickedTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _PickedTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to PickedType values", s)
}

// PickedTypeValues returns all values of the enum
func PickedTypeValues() []PickedType {
	return _PickedTypeValues
}

// PickedTypeStrings returns a slice of all String values of the enum
func PickedTypeStrings() []string {
	strs := make([]string, len(_PickedTypeNames))
	copy(strs, _PickedTypeNames)
	return strs
}

// IsAPickedType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i PickedType) IsAPickedType() bool {
	for _, v := range _PickedTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for PickedType
func (i PickedType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for PickedType
func (i *PickedType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("PickedType should be a string, got %s", data)
	}

	var err error
	*i, err = PickedTypeString(s)
	return err
}
