// Code generated by "enumer -type=ComponentFlags -json"; DO NOT EDIT.

package ecs

import (
	"encoding/json"
	"fmt"
	"strings"
)

const (
	_ComponentFlagsName_0      = "ComponentActiveComponentNoSave"
	_ComponentFlagsLowerName_0 = "componentactivecomponentnosave"
	_ComponentFlagsName_1      = "ComponentHideInEditor"
	_ComponentFlagsLowerName_1 = "componenthideineditor"
	_ComponentFlagsName_2      = "ComponentHideEntityInEditor"
	_ComponentFlagsLowerName_2 = "componenthideentityineditor"
	_ComponentFlagsName_3      = "ComponentLockedInEditor"
	_ComponentFlagsLowerName_3 = "componentlockedineditor"
	_ComponentFlagsName_4      = "ComponentLockedEntityInEditor"
	_ComponentFlagsLowerName_4 = "componentlockedentityineditor"
)

var (
	_ComponentFlagsIndex_0 = [...]uint8{0, 15, 30}
	_ComponentFlagsIndex_1 = [...]uint8{0, 21}
	_ComponentFlagsIndex_2 = [...]uint8{0, 27}
	_ComponentFlagsIndex_3 = [...]uint8{0, 23}
	_ComponentFlagsIndex_4 = [...]uint8{0, 29}
)

func (i ComponentFlags) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _ComponentFlagsName_0[_ComponentFlagsIndex_0[i]:_ComponentFlagsIndex_0[i+1]]
	case i == 4:
		return _ComponentFlagsName_1
	case i == 8:
		return _ComponentFlagsName_2
	case i == 16:
		return _ComponentFlagsName_3
	case i == 32:
		return _ComponentFlagsName_4
	default:
		return fmt.Sprintf("ComponentFlags(%d)", i)
	}
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ComponentFlagsNoOp() {
	var x [1]struct{}
	_ = x[ComponentActive-(1)]
	_ = x[ComponentNoSave-(2)]
	_ = x[ComponentHideInEditor-(4)]
	_ = x[ComponentHideEntityInEditor-(8)]
	_ = x[ComponentLockedInEditor-(16)]
	_ = x[ComponentLockedEntityInEditor-(32)]
}

var _ComponentFlagsValues = []ComponentFlags{ComponentActive, ComponentNoSave, ComponentHideInEditor, ComponentHideEntityInEditor, ComponentLockedInEditor, ComponentLockedEntityInEditor}

var _ComponentFlagsNameToValueMap = map[string]ComponentFlags{
	_ComponentFlagsName_0[0:15]:       ComponentActive,
	_ComponentFlagsLowerName_0[0:15]:  ComponentActive,
	_ComponentFlagsName_0[15:30]:      ComponentNoSave,
	_ComponentFlagsLowerName_0[15:30]: ComponentNoSave,
	_ComponentFlagsName_1[0:21]:       ComponentHideInEditor,
	_ComponentFlagsLowerName_1[0:21]:  ComponentHideInEditor,
	_ComponentFlagsName_2[0:27]:       ComponentHideEntityInEditor,
	_ComponentFlagsLowerName_2[0:27]:  ComponentHideEntityInEditor,
	_ComponentFlagsName_3[0:23]:       ComponentLockedInEditor,
	_ComponentFlagsLowerName_3[0:23]:  ComponentLockedInEditor,
	_ComponentFlagsName_4[0:29]:       ComponentLockedEntityInEditor,
	_ComponentFlagsLowerName_4[0:29]:  ComponentLockedEntityInEditor,
}

var _ComponentFlagsNames = []string{
	_ComponentFlagsName_0[0:15],
	_ComponentFlagsName_0[15:30],
	_ComponentFlagsName_1[0:21],
	_ComponentFlagsName_2[0:27],
	_ComponentFlagsName_3[0:23],
	_ComponentFlagsName_4[0:29],
}

// ComponentFlagsString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ComponentFlagsString(s string) (ComponentFlags, error) {
	if val, ok := _ComponentFlagsNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ComponentFlagsNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ComponentFlags values", s)
}

// ComponentFlagsValues returns all values of the enum
func ComponentFlagsValues() []ComponentFlags {
	return _ComponentFlagsValues
}

// ComponentFlagsStrings returns a slice of all String values of the enum
func ComponentFlagsStrings() []string {
	strs := make([]string, len(_ComponentFlagsNames))
	copy(strs, _ComponentFlagsNames)
	return strs
}

// IsAComponentFlags returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ComponentFlags) IsAComponentFlags() bool {
	for _, v := range _ComponentFlagsValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for ComponentFlags
func (i ComponentFlags) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for ComponentFlags
func (i *ComponentFlags) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("ComponentFlags should be a string, got %s", data)
	}

	var err error
	*i, err = ComponentFlagsString(s)
	return err
}
