// Code generated by "enumer -type=FieldFlags -json"; DO NOT EDIT.

package ecs

import (
	"encoding/json"
	"fmt"
	"strings"
)

const (
	_FieldFlagsName_0      = "FieldNonCacheableFieldNonTraversable"
	_FieldFlagsLowerName_0 = "fieldnoncacheablefieldnontraversable"
	_FieldFlagsName_1      = "FieldShallowCacheable"
	_FieldFlagsLowerName_1 = "fieldshallowcacheable"
)

var (
	_FieldFlagsIndex_0 = [...]uint8{0, 17, 36}
	_FieldFlagsIndex_1 = [...]uint8{0, 21}
)

func (i FieldFlags) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _FieldFlagsName_0[_FieldFlagsIndex_0[i]:_FieldFlagsIndex_0[i+1]]
	case i == 4:
		return _FieldFlagsName_1
	default:
		return fmt.Sprintf("FieldFlags(%d)", i)
	}
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _FieldFlagsNoOp() {
	var x [1]struct{}
	_ = x[FieldNonCacheable-(1)]
	_ = x[FieldNonTraversable-(2)]
	_ = x[FieldShallowCacheable-(4)]
}

var _FieldFlagsValues = []FieldFlags{FieldNonCacheable, FieldNonTraversable, FieldShallowCacheable}

var _FieldFlagsNameToValueMap = map[string]FieldFlags{
	_FieldFlagsName_0[0:17]:       FieldNonCacheable,
	_FieldFlagsLowerName_0[0:17]:  FieldNonCacheable,
	_FieldFlagsName_0[17:36]:      FieldNonTraversable,
	_FieldFlagsLowerName_0[17:36]: FieldNonTraversable,
	_FieldFlagsName_1[0:21]:       FieldShallowCacheable,
	_FieldFlagsLowerName_1[0:21]:  FieldShallowCacheable,
}

var _FieldFlagsNames = []string{
	_FieldFlagsName_0[0:17],
	_FieldFlagsName_0[17:36],
	_FieldFlagsName_1[0:21],
}

// FieldFlagsString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func FieldFlagsString(s string) (FieldFlags, error) {
	if val, ok := _FieldFlagsNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _FieldFlagsNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to FieldFlags values", s)
}

// FieldFlagsValues returns all values of the enum
func FieldFlagsValues() []FieldFlags {
	return _FieldFlagsValues
}

// FieldFlagsStrings returns a slice of all String values of the enum
func FieldFlagsStrings() []string {
	strs := make([]string, len(_FieldFlagsNames))
	copy(strs, _FieldFlagsNames)
	return strs
}

// IsAFieldFlags returns "true" if the value is listed in the enum definition. "false" otherwise
func (i FieldFlags) IsAFieldFlags() bool {
	for _, v := range _FieldFlagsValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for FieldFlags
func (i FieldFlags) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for FieldFlags
func (i *FieldFlags) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("FieldFlags should be a string, got %s", data)
	}

	var err error
	*i, err = FieldFlagsString(s)
	return err
}
