package properties

import (
	"reflect"

	"tlyakhov/gofoom/editor/actions"
	"tlyakhov/gofoom/editor/state"

	"fyne.io/fyne/v2/widget"
)

func (g *Grid) fieldEnum(field *state.PropertyGridField, enumValues any) {
	// This is the actual value of this property converted to an int.
	origValue := field.Values[0].Elem().Int()

	selectedIndex := 0
	opts := make([]string, 0)
	optsValues := make([]reflect.Value, 0)
	// Iterate through all the values of the enum type.
	refEnumValues := reflect.ValueOf(enumValues)
	for i := 0; i < refEnumValues.Len(); i++ {
		enumValue := refEnumValues.Index(i)
		// Our enum should have a String() method generated by the enumer library. Call it.
		enumName := enumValue.MethodByName("String").Call([]reflect.Value{})[0].String()
		// Set the GTK+ list entry.
		opts = append(opts, enumName)
		optsValues = append(optsValues, enumValue)
		if enumValue.Int() == origValue {
			selectedIndex = i
		}
	}

	box := widget.NewSelect(opts, nil)
	box.SetSelectedIndex(selectedIndex)
	box.OnChanged = func(opt string) {
		action := &actions.SetProperty{
			IEditor:           g.IEditor,
			PropertyGridField: field,
			ToSet:             optsValues[box.SelectedIndex()], //reflect.ValueOf(value2).Convert(field.Type.Elem()),
		}
		g.NewAction(action)
		action.Act()
	}

	g.FContainer.Add(box)
}
