// Code generated by "enumer -type=NpcState -json"; DO NOT EDIT.

package character

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _NpcStateName = "NpcStateIdleNpcStateSawTargetNpcStatePursuitNpcStateLostTargetNpcStateSearchingNpcStateDeadNpcStateCount"

var _NpcStateIndex = [...]uint8{0, 12, 29, 44, 62, 79, 91, 104}

const _NpcStateLowerName = "npcstateidlenpcstatesawtargetnpcstatepursuitnpcstatelosttargetnpcstatesearchingnpcstatedeadnpcstatecount"

func (i NpcState) String() string {
	if i < 0 || i >= NpcState(len(_NpcStateIndex)-1) {
		return fmt.Sprintf("NpcState(%d)", i)
	}
	return _NpcStateName[_NpcStateIndex[i]:_NpcStateIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _NpcStateNoOp() {
	var x [1]struct{}
	_ = x[NpcStateIdle-(0)]
	_ = x[NpcStateSawTarget-(1)]
	_ = x[NpcStatePursuit-(2)]
	_ = x[NpcStateLostTarget-(3)]
	_ = x[NpcStateSearching-(4)]
	_ = x[NpcStateDead-(5)]
	_ = x[NpcStateCount-(6)]
}

var _NpcStateValues = []NpcState{NpcStateIdle, NpcStateSawTarget, NpcStatePursuit, NpcStateLostTarget, NpcStateSearching, NpcStateDead, NpcStateCount}

var _NpcStateNameToValueMap = map[string]NpcState{
	_NpcStateName[0:12]:        NpcStateIdle,
	_NpcStateLowerName[0:12]:   NpcStateIdle,
	_NpcStateName[12:29]:       NpcStateSawTarget,
	_NpcStateLowerName[12:29]:  NpcStateSawTarget,
	_NpcStateName[29:44]:       NpcStatePursuit,
	_NpcStateLowerName[29:44]:  NpcStatePursuit,
	_NpcStateName[44:62]:       NpcStateLostTarget,
	_NpcStateLowerName[44:62]:  NpcStateLostTarget,
	_NpcStateName[62:79]:       NpcStateSearching,
	_NpcStateLowerName[62:79]:  NpcStateSearching,
	_NpcStateName[79:91]:       NpcStateDead,
	_NpcStateLowerName[79:91]:  NpcStateDead,
	_NpcStateName[91:104]:      NpcStateCount,
	_NpcStateLowerName[91:104]: NpcStateCount,
}

var _NpcStateNames = []string{
	_NpcStateName[0:12],
	_NpcStateName[12:29],
	_NpcStateName[29:44],
	_NpcStateName[44:62],
	_NpcStateName[62:79],
	_NpcStateName[79:91],
	_NpcStateName[91:104],
}

// NpcStateString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func NpcStateString(s string) (NpcState, error) {
	if val, ok := _NpcStateNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _NpcStateNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to NpcState values", s)
}

// NpcStateValues returns all values of the enum
func NpcStateValues() []NpcState {
	return _NpcStateValues
}

// NpcStateStrings returns a slice of all String values of the enum
func NpcStateStrings() []string {
	strs := make([]string, len(_NpcStateNames))
	copy(strs, _NpcStateNames)
	return strs
}

// IsANpcState returns "true" if the value is listed in the enum definition. "false" otherwise
func (i NpcState) IsANpcState() bool {
	for _, v := range _NpcStateValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for NpcState
func (i NpcState) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for NpcState
func (i *NpcState) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("NpcState should be a string, got %s", data)
	}

	var err error
	*i, err = NpcStateString(s)
	return err
}
