// Code generated by ecs/cmd/gofoom_ecs_generator. DO NOT EDIT.
package character

import "tlyakhov/gofoom/ecs"

var PlayerCID ecs.ComponentID

func init() {
	PlayerCID = ecs.RegisterComponent(&ecs.Arena[Player, *Player]{})
}
func GetPlayer(e ecs.Entity) *Player {
	if asserted, ok := ecs.Component(e, PlayerCID).(*Player); ok {
		return asserted
	}
	return nil
}

func (*Player) ComponentID() ecs.ComponentID {
	return PlayerCID
}
