// Code generated by "enumer -type=EntityListColumnID -json"; DO NOT EDIT.

package main

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _EntityListColumnIDName = "elcEntityelcDescelcRank"

var _EntityListColumnIDIndex = [...]uint8{0, 9, 16, 23}

const _EntityListColumnIDLowerName = "elcentityelcdescelcrank"

func (i EntityListColumnID) String() string {
	if i < 0 || i >= EntityListColumnID(len(_EntityListColumnIDIndex)-1) {
		return fmt.Sprintf("EntityListColumnID(%d)", i)
	}
	return _EntityListColumnIDName[_EntityListColumnIDIndex[i]:_EntityListColumnIDIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _EntityListColumnIDNoOp() {
	var x [1]struct{}
	_ = x[elcEntity-(0)]
	_ = x[elcDesc-(1)]
	_ = x[elcRank-(2)]
}

var _EntityListColumnIDValues = []EntityListColumnID{elcEntity, elcDesc, elcRank}

var _EntityListColumnIDNameToValueMap = map[string]EntityListColumnID{
	_EntityListColumnIDName[0:9]:        elcEntity,
	_EntityListColumnIDLowerName[0:9]:   elcEntity,
	_EntityListColumnIDName[9:16]:       elcDesc,
	_EntityListColumnIDLowerName[9:16]:  elcDesc,
	_EntityListColumnIDName[16:23]:      elcRank,
	_EntityListColumnIDLowerName[16:23]: elcRank,
}

var _EntityListColumnIDNames = []string{
	_EntityListColumnIDName[0:9],
	_EntityListColumnIDName[9:16],
	_EntityListColumnIDName[16:23],
}

// EntityListColumnIDString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func EntityListColumnIDString(s string) (EntityListColumnID, error) {
	if val, ok := _EntityListColumnIDNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _EntityListColumnIDNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to EntityListColumnID values", s)
}

// EntityListColumnIDValues returns all values of the enum
func EntityListColumnIDValues() []EntityListColumnID {
	return _EntityListColumnIDValues
}

// EntityListColumnIDStrings returns a slice of all String values of the enum
func EntityListColumnIDStrings() []string {
	strs := make([]string, len(_EntityListColumnIDNames))
	copy(strs, _EntityListColumnIDNames)
	return strs
}

// IsAEntityListColumnID returns "true" if the value is listed in the enum definition. "false" otherwise
func (i EntityListColumnID) IsAEntityListColumnID() bool {
	for _, v := range _EntityListColumnIDValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for EntityListColumnID
func (i EntityListColumnID) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for EntityListColumnID
func (i *EntityListColumnID) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("EntityListColumnID should be a string, got %s", data)
	}

	var err error
	*i, err = EntityListColumnIDString(s)
	return err
}
