// Code generated by "enumer -type=AnimationStyle -json"; DO NOT EDIT.

package concepts

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _AnimationStyleName = "AnimationStyleOnceAnimationStyleHoldAnimationStyleLoop"

var _AnimationStyleIndex = [...]uint8{0, 18, 36, 54}

const _AnimationStyleLowerName = "animationstyleonceanimationstyleholdanimationstyleloop"

func (i AnimationStyle) String() string {
	if i < 0 || i >= AnimationStyle(len(_AnimationStyleIndex)-1) {
		return fmt.Sprintf("AnimationStyle(%d)", i)
	}
	return _AnimationStyleName[_AnimationStyleIndex[i]:_AnimationStyleIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _AnimationStyleNoOp() {
	var x [1]struct{}
	_ = x[AnimationStyleOnce-(0)]
	_ = x[AnimationStyleHold-(1)]
	_ = x[AnimationStyleLoop-(2)]
}

var _AnimationStyleValues = []AnimationStyle{AnimationStyleOnce, AnimationStyleHold, AnimationStyleLoop}

var _AnimationStyleNameToValueMap = map[string]AnimationStyle{
	_AnimationStyleName[0:18]:       AnimationStyleOnce,
	_AnimationStyleLowerName[0:18]:  AnimationStyleOnce,
	_AnimationStyleName[18:36]:      AnimationStyleHold,
	_AnimationStyleLowerName[18:36]: AnimationStyleHold,
	_AnimationStyleName[36:54]:      AnimationStyleLoop,
	_AnimationStyleLowerName[36:54]: AnimationStyleLoop,
}

var _AnimationStyleNames = []string{
	_AnimationStyleName[0:18],
	_AnimationStyleName[18:36],
	_AnimationStyleName[36:54],
}

// AnimationStyleString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func AnimationStyleString(s string) (AnimationStyle, error) {
	if val, ok := _AnimationStyleNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _AnimationStyleNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to AnimationStyle values", s)
}

// AnimationStyleValues returns all values of the enum
func AnimationStyleValues() []AnimationStyle {
	return _AnimationStyleValues
}

// AnimationStyleStrings returns a slice of all String values of the enum
func AnimationStyleStrings() []string {
	strs := make([]string, len(_AnimationStyleNames))
	copy(strs, _AnimationStyleNames)
	return strs
}

// IsAAnimationStyle returns "true" if the value is listed in the enum definition. "false" otherwise
func (i AnimationStyle) IsAAnimationStyle() bool {
	for _, v := range _AnimationStyleValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for AnimationStyle
func (i AnimationStyle) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for AnimationStyle
func (i *AnimationStyle) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("AnimationStyle should be a string, got %s", data)
	}

	var err error
	*i, err = AnimationStyleString(s)
	return err
}
