// Code generated by "enumer -type=AnimationLifetime -json"; DO NOT EDIT.

package concepts

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _AnimationLifetimeName = "AnimationLifetimeOnceAnimationLifetimeHoldAnimationLifetimeLoop"

var _AnimationLifetimeIndex = [...]uint8{0, 21, 42, 63}

const _AnimationLifetimeLowerName = "animationlifetimeonceanimationlifetimeholdanimationlifetimeloop"

func (i AnimationLifetime) String() string {
	if i < 0 || i >= AnimationLifetime(len(_AnimationLifetimeIndex)-1) {
		return fmt.Sprintf("AnimationLifetime(%d)", i)
	}
	return _AnimationLifetimeName[_AnimationLifetimeIndex[i]:_AnimationLifetimeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _AnimationLifetimeNoOp() {
	var x [1]struct{}
	_ = x[AnimationLifetimeOnce-(0)]
	_ = x[AnimationLifetimeHold-(1)]
	_ = x[AnimationLifetimeLoop-(2)]
}

var _AnimationLifetimeValues = []AnimationLifetime{AnimationLifetimeOnce, AnimationLifetimeHold, AnimationLifetimeLoop}

var _AnimationLifetimeNameToValueMap = map[string]AnimationLifetime{
	_AnimationLifetimeName[0:21]:       AnimationLifetimeOnce,
	_AnimationLifetimeLowerName[0:21]:  AnimationLifetimeOnce,
	_AnimationLifetimeName[21:42]:      AnimationLifetimeHold,
	_AnimationLifetimeLowerName[21:42]: AnimationLifetimeHold,
	_AnimationLifetimeName[42:63]:      AnimationLifetimeLoop,
	_AnimationLifetimeLowerName[42:63]: AnimationLifetimeLoop,
}

var _AnimationLifetimeNames = []string{
	_AnimationLifetimeName[0:21],
	_AnimationLifetimeName[21:42],
	_AnimationLifetimeName[42:63],
}

// AnimationLifetimeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func AnimationLifetimeString(s string) (AnimationLifetime, error) {
	if val, ok := _AnimationLifetimeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _AnimationLifetimeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to AnimationLifetime values", s)
}

// AnimationLifetimeValues returns all values of the enum
func AnimationLifetimeValues() []AnimationLifetime {
	return _AnimationLifetimeValues
}

// AnimationLifetimeStrings returns a slice of all String values of the enum
func AnimationLifetimeStrings() []string {
	strs := make([]string, len(_AnimationLifetimeNames))
	copy(strs, _AnimationLifetimeNames)
	return strs
}

// IsAAnimationLifetime returns "true" if the value is listed in the enum definition. "false" otherwise
func (i AnimationLifetime) IsAAnimationLifetime() bool {
	for _, v := range _AnimationLifetimeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for AnimationLifetime
func (i AnimationLifetime) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for AnimationLifetime
func (i *AnimationLifetime) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("AnimationLifetime should be a string, got %s", data)
	}

	var err error
	*i, err = AnimationLifetimeString(s)
	return err
}
