// Code generated by "enumer -type=AnimationCoordinates -json"; DO NOT EDIT.

package concepts

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _AnimationCoordinatesName = "AnimationCoordinatesRelativeAnimationCoordinatesAbsolute"

var _AnimationCoordinatesIndex = [...]uint8{0, 28, 56}

const _AnimationCoordinatesLowerName = "animationcoordinatesrelativeanimationcoordinatesabsolute"

func (i AnimationCoordinates) String() string {
	if i < 0 || i >= AnimationCoordinates(len(_AnimationCoordinatesIndex)-1) {
		return fmt.Sprintf("AnimationCoordinates(%d)", i)
	}
	return _AnimationCoordinatesName[_AnimationCoordinatesIndex[i]:_AnimationCoordinatesIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _AnimationCoordinatesNoOp() {
	var x [1]struct{}
	_ = x[AnimationCoordinatesRelative-(0)]
	_ = x[AnimationCoordinatesAbsolute-(1)]
}

var _AnimationCoordinatesValues = []AnimationCoordinates{AnimationCoordinatesRelative, AnimationCoordinatesAbsolute}

var _AnimationCoordinatesNameToValueMap = map[string]AnimationCoordinates{
	_AnimationCoordinatesName[0:28]:       AnimationCoordinatesRelative,
	_AnimationCoordinatesLowerName[0:28]:  AnimationCoordinatesRelative,
	_AnimationCoordinatesName[28:56]:      AnimationCoordinatesAbsolute,
	_AnimationCoordinatesLowerName[28:56]: AnimationCoordinatesAbsolute,
}

var _AnimationCoordinatesNames = []string{
	_AnimationCoordinatesName[0:28],
	_AnimationCoordinatesName[28:56],
}

// AnimationCoordinatesString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func AnimationCoordinatesString(s string) (AnimationCoordinates, error) {
	if val, ok := _AnimationCoordinatesNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _AnimationCoordinatesNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to AnimationCoordinates values", s)
}

// AnimationCoordinatesValues returns all values of the enum
func AnimationCoordinatesValues() []AnimationCoordinates {
	return _AnimationCoordinatesValues
}

// AnimationCoordinatesStrings returns a slice of all String values of the enum
func AnimationCoordinatesStrings() []string {
	strs := make([]string, len(_AnimationCoordinatesNames))
	copy(strs, _AnimationCoordinatesNames)
	return strs
}

// IsAAnimationCoordinates returns "true" if the value is listed in the enum definition. "false" otherwise
func (i AnimationCoordinates) IsAAnimationCoordinates() bool {
	for _, v := range _AnimationCoordinatesValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for AnimationCoordinates
func (i AnimationCoordinates) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for AnimationCoordinates
func (i *AnimationCoordinates) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("AnimationCoordinates should be a string, got %s", data)
	}

	var err error
	*i, err = AnimationCoordinatesString(s)
	return err
}
