// Code generated by "enumer -type=BlendType -json"; DO NOT EDIT.

package concepts

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _BlendTypeName = "BlendNormalBlendDissolveBlendMultiplyBlendScreenBlendOverlay"

var _BlendTypeIndex = [...]uint8{0, 11, 24, 37, 48, 60}

const _BlendTypeLowerName = "blendnormalblenddissolveblendmultiplyblendscreenblendoverlay"

func (i BlendType) String() string {
	if i < 0 || i >= BlendType(len(_BlendTypeIndex)-1) {
		return fmt.Sprintf("BlendType(%d)", i)
	}
	return _BlendTypeName[_BlendTypeIndex[i]:_BlendTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _BlendTypeNoOp() {
	var x [1]struct{}
	_ = x[BlendNormal-(0)]
	_ = x[BlendDissolve-(1)]
	_ = x[BlendMultiply-(2)]
	_ = x[BlendScreen-(3)]
	_ = x[BlendOverlay-(4)]
}

var _BlendTypeValues = []BlendType{BlendNormal, BlendDissolve, BlendMultiply, BlendScreen, BlendOverlay}

var _BlendTypeNameToValueMap = map[string]BlendType{
	_BlendTypeName[0:11]:       BlendNormal,
	_BlendTypeLowerName[0:11]:  BlendNormal,
	_BlendTypeName[11:24]:      BlendDissolve,
	_BlendTypeLowerName[11:24]: BlendDissolve,
	_BlendTypeName[24:37]:      BlendMultiply,
	_BlendTypeLowerName[24:37]: BlendMultiply,
	_BlendTypeName[37:48]:      BlendScreen,
	_BlendTypeLowerName[37:48]: BlendScreen,
	_BlendTypeName[48:60]:      BlendOverlay,
	_BlendTypeLowerName[48:60]: BlendOverlay,
}

var _BlendTypeNames = []string{
	_BlendTypeName[0:11],
	_BlendTypeName[11:24],
	_BlendTypeName[24:37],
	_BlendTypeName[37:48],
	_BlendTypeName[48:60],
}

// BlendTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func BlendTypeString(s string) (BlendType, error) {
	if val, ok := _BlendTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _BlendTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to BlendType values", s)
}

// BlendTypeValues returns all values of the enum
func BlendTypeValues() []BlendType {
	return _BlendTypeValues
}

// BlendTypeStrings returns a slice of all String values of the enum
func BlendTypeStrings() []string {
	strs := make([]string, len(_BlendTypeNames))
	copy(strs, _BlendTypeNames)
	return strs
}

// IsABlendType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i BlendType) IsABlendType() bool {
	for _, v := range _BlendTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for BlendType
func (i BlendType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for BlendType
func (i *BlendType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("BlendType should be a string, got %s", data)
	}

	var err error
	*i, err = BlendTypeString(s)
	return err
}
