// Code generated by "enumer -type=BlendFunc -json"; DO NOT EDIT.

package concepts

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _BlendFuncName = "BlendNormalBlendDissolveBlendMultiplyBlendScreenBlendOverlay"

var _BlendFuncIndex = [...]uint8{0, 11, 24, 37, 48, 60}

const _BlendFuncLowerName = "blendnormalblenddissolveblendmultiplyblendscreenblendoverlay"

func (i BlendType) String() string {
	if i < 0 || i >= BlendType(len(_BlendFuncIndex)-1) {
		return fmt.Sprintf("BlendFunc(%d)", i)
	}
	return _BlendFuncName[_BlendFuncIndex[i]:_BlendFuncIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _BlendFuncNoOp() {
	var x [1]struct{}
	_ = x[BlendNormal-(0)]
	_ = x[BlendDissolve-(1)]
	_ = x[BlendMultiply-(2)]
	_ = x[BlendScreen-(3)]
	_ = x[BlendOverlay-(4)]
}

var _BlendFuncValues = []BlendType{BlendNormal, BlendDissolve, BlendMultiply, BlendScreen, BlendOverlay}

var _BlendFuncNameToValueMap = map[string]BlendType{
	_BlendFuncName[0:11]:       BlendNormal,
	_BlendFuncLowerName[0:11]:  BlendNormal,
	_BlendFuncName[11:24]:      BlendDissolve,
	_BlendFuncLowerName[11:24]: BlendDissolve,
	_BlendFuncName[24:37]:      BlendMultiply,
	_BlendFuncLowerName[24:37]: BlendMultiply,
	_BlendFuncName[37:48]:      BlendScreen,
	_BlendFuncLowerName[37:48]: BlendScreen,
	_BlendFuncName[48:60]:      BlendOverlay,
	_BlendFuncLowerName[48:60]: BlendOverlay,
}

var _BlendFuncNames = []string{
	_BlendFuncName[0:11],
	_BlendFuncName[11:24],
	_BlendFuncName[24:37],
	_BlendFuncName[37:48],
	_BlendFuncName[48:60],
}

// BlendFuncString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func BlendFuncString(s string) (BlendType, error) {
	if val, ok := _BlendFuncNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _BlendFuncNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to BlendFunc values", s)
}

// BlendFuncValues returns all values of the enum
func BlendFuncValues() []BlendType {
	return _BlendFuncValues
}

// BlendFuncStrings returns a slice of all String values of the enum
func BlendFuncStrings() []string {
	strs := make([]string, len(_BlendFuncNames))
	copy(strs, _BlendFuncNames)
	return strs
}

// IsABlendFunc returns "true" if the value is listed in the enum definition. "false" otherwise
func (i BlendType) IsABlendFunc() bool {
	for _, v := range _BlendFuncValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for BlendFunc
func (i BlendType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for BlendFunc
func (i *BlendType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("BlendFunc should be a string, got %s", data)
	}

	var err error
	*i, err = BlendFuncString(s)
	return err
}
