// Code generated by command: go run blend_asm.go -out blend_asm.s -stubs blend_asm_stub.go. DO NOT EDIT.

package concepts

// BlendFrameBuffer converts float64 framebuffer to uint8 with an added tint
//
//go:noescape
func BlendFrameBuffer(target []uint8, fb [][4]float64, tint *[4]float64)

// BlendColors adds a and b * opacity.
//
//go:noescape
func BlendColors(a *[4]float64, b *[4]float64, opacity float64)

// AsmVector4Mul4Self multiplies a and b.
//
//go:noescape
func AsmVector4Mul4Self(a *[4]float64, b *[4]float64)

// AsmInt32ToVector4 converts a uint32 color to a vector.
//
//go:noescape
func AsmInt32ToVector4(c uint32, a *[4]float64)

// AsmInt32ToVector4PreMul converts a uint32 color to a vector with pre-multiplied alpha.
//
//go:noescape
func AsmInt32ToVector4PreMul(c uint32, a *[4]float64)
