// Code generated by command: go run vector4_amd64_asm.go -out vector4_amd64_asm.s -stubs vector4_amd64_stub.go. DO NOT EDIT.

#include "textflag.h"

// func asmAddPreMulColorSelf(a *[4]float64, b *[4]float64)
// Requires: AVX
TEXT ·asmAddPreMulColorSelf(SB), NOSPLIT, $0-16
	MOVQ         a+0(FP), AX
	MOVQ         b+8(FP), CX
	VBROADCASTSD 24(CX), Y0
	VBROADCASTSD one<>+0(SB), Y1
	VSUBPD       Y0, Y1, Y0
	VMULPD       (AX), Y0, Y0
	VADDPD       (CX), Y0, Y0
	VMOVUPD      Y0, (AX)
	RET

DATA one<>+0(SB)/8, $0x3ff0000000000000
GLOBL one<>(SB), RODATA|NOPTR, $8
