// Code generated by command: go run vector3_amd64_asm.go -out vector3_amd64_asm.s -stubs vector3_amd64_stub.go. DO NOT EDIT.

#include "textflag.h"

// func asmVector3AddSelf(a *[4]float64, b *[4]float64)
// Requires: AVX
TEXT ·asmVector3AddSelf(SB), NOSPLIT, $0-16
	MOVQ    a+0(FP), AX
	MOVQ    b+8(FP), CX
	VMOVUPD (AX), Y0
	VADDPD  (CX), Y0, Y0
	VMOVUPD Y0, (AX)
	RET

// func asmVector3SubSelf(a *[4]float64, b *[4]float64)
// Requires: AVX
TEXT ·asmVector3SubSelf(SB), NOSPLIT, $0-16
	MOVQ    a+0(FP), AX
	MOVQ    b+8(FP), CX
	VMOVUPD (AX), Y0
	VSUBPD  (CX), Y0, Y0
	VMOVUPD Y0, (AX)
	RET
