// Code generated by command: go run vector3_amd64_asm.go -out vector3_amd64_asm.s -stubs vector3_amd64_stub.go. DO NOT EDIT.

package concepts

// asmVector3AddSelf adds a and b.
//
//go:noescape
func asmVector3AddSelf(a *[4]float64, b *[4]float64)

// asmVector3SubSelf subtracts a and b.
//
//go:noescape
func asmVector3SubSelf(a *[4]float64, b *[4]float64)
