// Code generated by command: go run vector4_amd64_asm.go -out vector4_amd64_asm.s -stubs vector4_amd64_stub.go. DO NOT EDIT.

package concepts

// asmAddPreMulColorSelf adds a and b with pre-multiplied alpha.
func asmAddPreMulColorSelf(a *[4]float64, b *[4]float64)
