// Code generated by command: go run vector4_amd64_asm.go -out vector4_amd64_asm.s -stubs vector4_amd64_stub.go. DO NOT EDIT.

package concepts

// AsmVector4AddSelf adds a and b.
//
//go:noescape
func AsmVector4AddSelf(a *[4]float64, b *[4]float64)

// AsmVector4AddPreMulColorSelf adds a and b with pre-multiplied alpha.
//
//go:noescape
func AsmVector4AddPreMulColorSelf(a *[4]float64, b *[4]float64)

// AsmVector4Mul4Self multiplies a and b.
//
//go:noescape
func AsmVector4Mul4Self(a *[4]float64, b *[4]float64)

// AsmInt32ToVector4 converts a uint32 color to a vector.
//
//go:noescape
func AsmInt32ToVector4(c uint32, a *[4]float64)

// AsmInt32ToVector4PreMul converts a uint32 color to a vector with pre-multiplied alpha.
//
//go:noescape
func AsmInt32ToVector4PreMul(c uint32, a *[4]float64)
