// Code generated by "enumer -type=LightSamplerType -json"; DO NOT EDIT.

package render

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _LightSamplerTypeName = "LightSamplerBodyLightSamplerFloorLightSamplerCeilLightSamplerWall"

var _LightSamplerTypeIndex = [...]uint8{0, 16, 33, 49, 65}

const _LightSamplerTypeLowerName = "lightsamplerbodylightsamplerfloorlightsamplerceillightsamplerwall"

func (i LightSamplerType) String() string {
	if i < 0 || i >= LightSamplerType(len(_LightSamplerTypeIndex)-1) {
		return fmt.Sprintf("LightSamplerType(%d)", i)
	}
	return _LightSamplerTypeName[_LightSamplerTypeIndex[i]:_LightSamplerTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _LightSamplerTypeNoOp() {
	var x [1]struct{}
	_ = x[LightSamplerBody-(0)]
	_ = x[LightSamplerFloor-(1)]
	_ = x[LightSamplerCeil-(2)]
	_ = x[LightSamplerWall-(3)]
}

var _LightSamplerTypeValues = []LightSamplerType{LightSamplerBody, LightSamplerFloor, LightSamplerCeil, LightSamplerWall}

var _LightSamplerTypeNameToValueMap = map[string]LightSamplerType{
	_LightSamplerTypeName[0:16]:       LightSamplerBody,
	_LightSamplerTypeLowerName[0:16]:  LightSamplerBody,
	_LightSamplerTypeName[16:33]:      LightSamplerFloor,
	_LightSamplerTypeLowerName[16:33]: LightSamplerFloor,
	_LightSamplerTypeName[33:49]:      LightSamplerCeil,
	_LightSamplerTypeLowerName[33:49]: LightSamplerCeil,
	_LightSamplerTypeName[49:65]:      LightSamplerWall,
	_LightSamplerTypeLowerName[49:65]: LightSamplerWall,
}

var _LightSamplerTypeNames = []string{
	_LightSamplerTypeName[0:16],
	_LightSamplerTypeName[16:33],
	_LightSamplerTypeName[33:49],
	_LightSamplerTypeName[49:65],
}

// LightSamplerTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func LightSamplerTypeString(s string) (LightSamplerType, error) {
	if val, ok := _LightSamplerTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _LightSamplerTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to LightSamplerType values", s)
}

// LightSamplerTypeValues returns all values of the enum
func LightSamplerTypeValues() []LightSamplerType {
	return _LightSamplerTypeValues
}

// LightSamplerTypeStrings returns a slice of all String values of the enum
func LightSamplerTypeStrings() []string {
	strs := make([]string, len(_LightSamplerTypeNames))
	copy(strs, _LightSamplerTypeNames)
	return strs
}

// IsALightSamplerType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i LightSamplerType) IsALightSamplerType() bool {
	for _, v := range _LightSamplerTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for LightSamplerType
func (i LightSamplerType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for LightSamplerType
func (i *LightSamplerType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("LightSamplerType should be a string, got %s", data)
	}

	var err error
	*i, err = LightSamplerTypeString(s)
	return err
}
