// Code generated by "enumer -type=MaterialShadow -json"; DO NOT EDIT.

package materials

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _MaterialShadowName = "ShadowNoneShadowImageShadowSphereShadowAABB"

var _MaterialShadowIndex = [...]uint8{0, 10, 21, 33, 43}

const _MaterialShadowLowerName = "shadownoneshadowimageshadowsphereshadowaabb"

func (i MaterialShadow) String() string {
	if i < 0 || i >= MaterialShadow(len(_MaterialShadowIndex)-1) {
		return fmt.Sprintf("MaterialShadow(%d)", i)
	}
	return _MaterialShadowName[_MaterialShadowIndex[i]:_MaterialShadowIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _MaterialShadowNoOp() {
	var x [1]struct{}
	_ = x[ShadowNone-(0)]
	_ = x[ShadowImage-(1)]
	_ = x[ShadowSphere-(2)]
	_ = x[ShadowAABB-(3)]
}

var _MaterialShadowValues = []MaterialShadow{ShadowNone, ShadowImage, ShadowSphere, ShadowAABB}

var _MaterialShadowNameToValueMap = map[string]MaterialShadow{
	_MaterialShadowName[0:10]:       ShadowNone,
	_MaterialShadowLowerName[0:10]:  ShadowNone,
	_MaterialShadowName[10:21]:      ShadowImage,
	_MaterialShadowLowerName[10:21]: ShadowImage,
	_MaterialShadowName[21:33]:      ShadowSphere,
	_MaterialShadowLowerName[21:33]: ShadowSphere,
	_MaterialShadowName[33:43]:      ShadowAABB,
	_MaterialShadowLowerName[33:43]: ShadowAABB,
}

var _MaterialShadowNames = []string{
	_MaterialShadowName[0:10],
	_MaterialShadowName[10:21],
	_MaterialShadowName[21:33],
	_MaterialShadowName[33:43],
}

// MaterialShadowString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func MaterialShadowString(s string) (MaterialShadow, error) {
	if val, ok := _MaterialShadowNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _MaterialShadowNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to MaterialShadow values", s)
}

// MaterialShadowValues returns all values of the enum
func MaterialShadowValues() []MaterialShadow {
	return _MaterialShadowValues
}

// MaterialShadowStrings returns a slice of all String values of the enum
func MaterialShadowStrings() []string {
	strs := make([]string, len(_MaterialShadowNames))
	copy(strs, _MaterialShadowNames)
	return strs
}

// IsAMaterialShadow returns "true" if the value is listed in the enum definition. "false" otherwise
func (i MaterialShadow) IsAMaterialShadow() bool {
	for _, v := range _MaterialShadowValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for MaterialShadow
func (i MaterialShadow) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for MaterialShadow
func (i *MaterialShadow) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("MaterialShadow should be a string, got %s", data)
	}

	var err error
	*i, err = MaterialShadowString(s)
	return err
}
