// Code generated by "enumer -type=ShaderFlags -json"; DO NOT EDIT.

package materials

import (
	"encoding/json"
	"fmt"
	"strings"
)

const (
	_ShaderFlagsName_0      = "ShaderTiledShaderSky"
	_ShaderFlagsLowerName_0 = "shadertiledshadersky"
	_ShaderFlagsName_1      = "ShaderStaticBackground"
	_ShaderFlagsLowerName_1 = "shaderstaticbackground"
	_ShaderFlagsName_2      = "ShaderLiquid"
	_ShaderFlagsLowerName_2 = "shaderliquid"
	_ShaderFlagsName_3      = "ShaderFrob"
	_ShaderFlagsLowerName_3 = "shaderfrob"
)

var (
	_ShaderFlagsIndex_0 = [...]uint8{0, 11, 20}
	_ShaderFlagsIndex_1 = [...]uint8{0, 22}
	_ShaderFlagsIndex_2 = [...]uint8{0, 12}
	_ShaderFlagsIndex_3 = [...]uint8{0, 10}
)

func (i ShaderFlags) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _ShaderFlagsName_0[_ShaderFlagsIndex_0[i]:_ShaderFlagsIndex_0[i+1]]
	case i == 4:
		return _ShaderFlagsName_1
	case i == 8:
		return _ShaderFlagsName_2
	case i == 16:
		return _ShaderFlagsName_3
	default:
		return fmt.Sprintf("ShaderFlags(%d)", i)
	}
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ShaderFlagsNoOp() {
	var x [1]struct{}
	_ = x[ShaderTiled-(1)]
	_ = x[ShaderSky-(2)]
	_ = x[ShaderStaticBackground-(4)]
	_ = x[ShaderLiquid-(8)]
	_ = x[ShaderFrob-(16)]
}

var _ShaderFlagsValues = []ShaderFlags{ShaderTiled, ShaderSky, ShaderStaticBackground, ShaderLiquid, ShaderFrob}

var _ShaderFlagsNameToValueMap = map[string]ShaderFlags{
	_ShaderFlagsName_0[0:11]:       ShaderTiled,
	_ShaderFlagsLowerName_0[0:11]:  ShaderTiled,
	_ShaderFlagsName_0[11:20]:      ShaderSky,
	_ShaderFlagsLowerName_0[11:20]: ShaderSky,
	_ShaderFlagsName_1[0:22]:       ShaderStaticBackground,
	_ShaderFlagsLowerName_1[0:22]:  ShaderStaticBackground,
	_ShaderFlagsName_2[0:12]:       ShaderLiquid,
	_ShaderFlagsLowerName_2[0:12]:  ShaderLiquid,
	_ShaderFlagsName_3[0:10]:       ShaderFrob,
	_ShaderFlagsLowerName_3[0:10]:  ShaderFrob,
}

var _ShaderFlagsNames = []string{
	_ShaderFlagsName_0[0:11],
	_ShaderFlagsName_0[11:20],
	_ShaderFlagsName_1[0:22],
	_ShaderFlagsName_2[0:12],
	_ShaderFlagsName_3[0:10],
}

// ShaderFlagsString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ShaderFlagsString(s string) (ShaderFlags, error) {
	if val, ok := _ShaderFlagsNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ShaderFlagsNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ShaderFlags values", s)
}

// ShaderFlagsValues returns all values of the enum
func ShaderFlagsValues() []ShaderFlags {
	return _ShaderFlagsValues
}

// ShaderFlagsStrings returns a slice of all String values of the enum
func ShaderFlagsStrings() []string {
	strs := make([]string, len(_ShaderFlagsNames))
	copy(strs, _ShaderFlagsNames)
	return strs
}

// IsAShaderFlags returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ShaderFlags) IsAShaderFlags() bool {
	for _, v := range _ShaderFlagsValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for ShaderFlags
func (i ShaderFlags) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for ShaderFlags
func (i *ShaderFlags) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("ShaderFlags should be a string, got %s", data)
	}

	var err error
	*i, err = ShaderFlagsString(s)
	return err
}
