// Code generated by "enumer -type=SurfaceStretch -json"; DO NOT EDIT.

package materials

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _SurfaceStretchName = "StretchNoneStretchAspectStretchFill"

var _SurfaceStretchIndex = [...]uint8{0, 11, 24, 35}

const _SurfaceStretchLowerName = "stretchnonestretchaspectstretchfill"

func (i SurfaceStretch) String() string {
	if i < 0 || i >= SurfaceStretch(len(_SurfaceStretchIndex)-1) {
		return fmt.Sprintf("SurfaceStretch(%d)", i)
	}
	return _SurfaceStretchName[_SurfaceStretchIndex[i]:_SurfaceStretchIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _SurfaceStretchNoOp() {
	var x [1]struct{}
	_ = x[StretchNone-(0)]
	_ = x[StretchAspect-(1)]
	_ = x[StretchFill-(2)]
}

var _SurfaceStretchValues = []SurfaceStretch{StretchNone, StretchAspect, StretchFill}

var _SurfaceStretchNameToValueMap = map[string]SurfaceStretch{
	_SurfaceStretchName[0:11]:       StretchNone,
	_SurfaceStretchLowerName[0:11]:  StretchNone,
	_SurfaceStretchName[11:24]:      StretchAspect,
	_SurfaceStretchLowerName[11:24]: StretchAspect,
	_SurfaceStretchName[24:35]:      StretchFill,
	_SurfaceStretchLowerName[24:35]: StretchFill,
}

var _SurfaceStretchNames = []string{
	_SurfaceStretchName[0:11],
	_SurfaceStretchName[11:24],
	_SurfaceStretchName[24:35],
}

// SurfaceStretchString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func SurfaceStretchString(s string) (SurfaceStretch, error) {
	if val, ok := _SurfaceStretchNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _SurfaceStretchNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to SurfaceStretch values", s)
}

// SurfaceStretchValues returns all values of the enum
func SurfaceStretchValues() []SurfaceStretch {
	return _SurfaceStretchValues
}

// SurfaceStretchStrings returns a slice of all String values of the enum
func SurfaceStretchStrings() []string {
	strs := make([]string, len(_SurfaceStretchNames))
	copy(strs, _SurfaceStretchNames)
	return strs
}

// IsASurfaceStretch returns "true" if the value is listed in the enum definition. "false" otherwise
func (i SurfaceStretch) IsASurfaceStretch() bool {
	for _, v := range _SurfaceStretchValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for SurfaceStretch
func (i SurfaceStretch) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for SurfaceStretch
func (i *SurfaceStretch) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("SurfaceStretch should be a string, got %s", data)
	}

	var err error
	*i, err = SurfaceStretchString(s)
	return err
}
