// Code generated by "enumer -type=SurfaceScale -json"; DO NOT EDIT.

package materials

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _SurfaceScaleName = "ScaleNoneScaleHeightScaleWidthScaleAll"

var _SurfaceScaleIndex = [...]uint8{0, 9, 20, 30, 38}

const _SurfaceScaleLowerName = "scalenonescaleheightscalewidthscaleall"

func (i SurfaceScale) String() string {
	if i < 0 || i >= SurfaceScale(len(_SurfaceScaleIndex)-1) {
		return fmt.Sprintf("SurfaceScale(%d)", i)
	}
	return _SurfaceScaleName[_SurfaceScaleIndex[i]:_SurfaceScaleIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _SurfaceScaleNoOp() {
	var x [1]struct{}
	_ = x[ScaleNone-(0)]
	_ = x[ScaleHeight-(1)]
	_ = x[ScaleWidth-(2)]
	_ = x[ScaleAll-(3)]
}

var _SurfaceScaleValues = []SurfaceScale{ScaleNone, ScaleHeight, ScaleWidth, ScaleAll}

var _SurfaceScaleNameToValueMap = map[string]SurfaceScale{
	_SurfaceScaleName[0:9]:        ScaleNone,
	_SurfaceScaleLowerName[0:9]:   ScaleNone,
	_SurfaceScaleName[9:20]:       ScaleHeight,
	_SurfaceScaleLowerName[9:20]:  ScaleHeight,
	_SurfaceScaleName[20:30]:      ScaleWidth,
	_SurfaceScaleLowerName[20:30]: ScaleWidth,
	_SurfaceScaleName[30:38]:      ScaleAll,
	_SurfaceScaleLowerName[30:38]: ScaleAll,
}

var _SurfaceScaleNames = []string{
	_SurfaceScaleName[0:9],
	_SurfaceScaleName[9:20],
	_SurfaceScaleName[20:30],
	_SurfaceScaleName[30:38],
}

// SurfaceScaleString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func SurfaceScaleString(s string) (SurfaceScale, error) {
	if val, ok := _SurfaceScaleNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _SurfaceScaleNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to SurfaceScale values", s)
}

// SurfaceScaleValues returns all values of the enum
func SurfaceScaleValues() []SurfaceScale {
	return _SurfaceScaleValues
}

// SurfaceScaleStrings returns a slice of all String values of the enum
func SurfaceScaleStrings() []string {
	strs := make([]string, len(_SurfaceScaleNames))
	copy(strs, _SurfaceScaleNames)
	return strs
}

// IsASurfaceScale returns "true" if the value is listed in the enum definition. "false" otherwise
func (i SurfaceScale) IsASurfaceScale() bool {
	for _, v := range _SurfaceScaleValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for SurfaceScale
func (i SurfaceScale) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for SurfaceScale
func (i *SurfaceScale) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("SurfaceScale should be a string, got %s", data)
	}

	var err error
	*i, err = SurfaceScaleString(s)
	return err
}
