// Code generated by ecs/cmd/gofoom_ecs_generator. DO NOT EDIT.
package materials

import "tlyakhov/gofoom/ecs"

var ImageCID ecs.ComponentID
var LitCID ecs.ComponentID
var ShaderCID ecs.ComponentID
var SolidCID ecs.ComponentID
var SpriteCID ecs.ComponentID
var SpriteSheetCID ecs.ComponentID
var TextCID ecs.ComponentID
var ToneMapCID ecs.ComponentID
var VisibleCID ecs.ComponentID

func init() {
	ImageCID = ecs.RegisterComponent(&ecs.Arena[Image, *Image]{})
	LitCID = ecs.RegisterComponent(&ecs.Arena[Lit, *Lit]{})
	ShaderCID = ecs.RegisterComponent(&ecs.Arena[Shader, *Shader]{})
	SolidCID = ecs.RegisterComponent(&ecs.Arena[Solid, *Solid]{})
	SpriteCID = ecs.RegisterComponent(&ecs.Arena[Sprite, *Sprite]{})
	SpriteSheetCID = ecs.RegisterComponent(&ecs.Arena[SpriteSheet, *SpriteSheet]{})
	TextCID = ecs.RegisterComponent(&ecs.Arena[Text, *Text]{})
	ToneMapCID = ecs.RegisterComponent(&ecs.Arena[ToneMap, *ToneMap]{})
	VisibleCID = ecs.RegisterComponent(&ecs.Arena[Visible, *Visible]{})
}
func GetImage(e ecs.Entity) *Image {
	if asserted, ok := ecs.Component(e, ImageCID).(*Image); ok {
		return asserted
	}
	return nil
}

func (*Image) ComponentID() ecs.ComponentID {
	return ImageCID
}
func GetLit(e ecs.Entity) *Lit {
	if asserted, ok := ecs.Component(e, LitCID).(*Lit); ok {
		return asserted
	}
	return nil
}

func (*Lit) ComponentID() ecs.ComponentID {
	return LitCID
}
func GetShader(e ecs.Entity) *Shader {
	if asserted, ok := ecs.Component(e, ShaderCID).(*Shader); ok {
		return asserted
	}
	return nil
}

func (*Shader) ComponentID() ecs.ComponentID {
	return ShaderCID
}
func GetSolid(e ecs.Entity) *Solid {
	if asserted, ok := ecs.Component(e, SolidCID).(*Solid); ok {
		return asserted
	}
	return nil
}

func (*Solid) ComponentID() ecs.ComponentID {
	return SolidCID
}
func GetSprite(e ecs.Entity) *Sprite {
	if asserted, ok := ecs.Component(e, SpriteCID).(*Sprite); ok {
		return asserted
	}
	return nil
}

func (*Sprite) ComponentID() ecs.ComponentID {
	return SpriteCID
}
func GetSpriteSheet(e ecs.Entity) *SpriteSheet {
	if asserted, ok := ecs.Component(e, SpriteSheetCID).(*SpriteSheet); ok {
		return asserted
	}
	return nil
}

func (*SpriteSheet) ComponentID() ecs.ComponentID {
	return SpriteSheetCID
}
func GetText(e ecs.Entity) *Text {
	if asserted, ok := ecs.Component(e, TextCID).(*Text); ok {
		return asserted
	}
	return nil
}

func (*Text) ComponentID() ecs.ComponentID {
	return TextCID
}
func GetToneMap(e ecs.Entity) *ToneMap {
	panic("Tried to GetToneMap, which is a singleton. use ecs.Singleton instead")
}

func (*ToneMap) ComponentID() ecs.ComponentID {
	return ToneMapCID
}
func GetVisible(e ecs.Entity) *Visible {
	if asserted, ok := ecs.Component(e, VisibleCID).(*Visible); ok {
		return asserted
	}
	return nil
}

func (*Visible) ComponentID() ecs.ComponentID {
	return VisibleCID
}
