// Code generated by 'yaegi extract tlyakhov/gofoom/components/sectors'. DO NOT EDIT.

//go:build go1.21
// +build go1.21

package scripting_symbols

import (
	"reflect"
	"tlyakhov/gofoom/components/behaviors"
)

func init() {
	Symbols["tlyakhov/gofoom/components/sectors/sectors"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"DoorIntentClosed":           reflect.ValueOf(behaviors.DoorIntentClosed),
		"DoorIntentOpen":             reflect.ValueOf(behaviors.DoorIntentOpen),
		"DoorIntentReset":            reflect.ValueOf(behaviors.DoorIntentReset),
		"DoorIntentString":           reflect.ValueOf(behaviors.DoorIntentString),
		"DoorIntentStrings":          reflect.ValueOf(behaviors.DoorIntentStrings),
		"DoorIntentValues":           reflect.ValueOf(behaviors.DoorIntentValues),
		"DoorStateClosed":            reflect.ValueOf(behaviors.DoorStateClosed),
		"DoorStateClosing":           reflect.ValueOf(behaviors.DoorStateClosing),
		"DoorStateOpen":              reflect.ValueOf(behaviors.DoorStateOpen),
		"DoorStateOpening":           reflect.ValueOf(behaviors.DoorStateOpening),
		"DoorStateString":            reflect.ValueOf(behaviors.DoorStateString),
		"DoorStateStrings":           reflect.ValueOf(behaviors.DoorStateStrings),
		"DoorStateValues":            reflect.ValueOf(behaviors.DoorStateValues),
		"UnderwaterComponentIndex":   reflect.ValueOf(&behaviors.UnderwaterComponentIndex).Elem(),
		"UnderwaterFromDb":           reflect.ValueOf(behaviors.UnderwaterFromDb),
		"VerticalDoorComponentIndex": reflect.ValueOf(&behaviors.VerticalDoorComponentIndex).Elem(),
		"VerticalDoorFromDb":         reflect.ValueOf(behaviors.VerticalDoorFromDb),

		// type definitions
		"DoorIntent":   reflect.ValueOf((*behaviors.DoorIntent)(nil)),
		"DoorState":    reflect.ValueOf((*behaviors.DoorState)(nil)),
		"Underwater":   reflect.ValueOf((*behaviors.Underwater)(nil)),
		"VerticalDoor": reflect.ValueOf((*behaviors.VerticalDoor)(nil)),
	}
}
