// Code generated by 'yaegi extract tlyakhov/gofoom/components/sectors'. DO NOT EDIT.

//go:build go1.21
// +build go1.21

package scripting_symbols

import (
	"reflect"
	"tlyakhov/gofoom/components/sectors"
)

func init() {
	Symbols["tlyakhov/gofoom/components/sectors/sectors"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"DoorIntentClosed":           reflect.ValueOf(sectors.DoorIntentClosed),
		"DoorIntentOpen":             reflect.ValueOf(sectors.DoorIntentOpen),
		"DoorIntentReset":            reflect.ValueOf(sectors.DoorIntentReset),
		"DoorIntentString":           reflect.ValueOf(sectors.DoorIntentString),
		"DoorIntentStrings":          reflect.ValueOf(sectors.DoorIntentStrings),
		"DoorIntentValues":           reflect.ValueOf(sectors.DoorIntentValues),
		"DoorStateClosed":            reflect.ValueOf(sectors.DoorStateClosed),
		"DoorStateClosing":           reflect.ValueOf(sectors.DoorStateClosing),
		"DoorStateOpen":              reflect.ValueOf(sectors.DoorStateOpen),
		"DoorStateOpening":           reflect.ValueOf(sectors.DoorStateOpening),
		"DoorStateString":            reflect.ValueOf(sectors.DoorStateString),
		"DoorStateStrings":           reflect.ValueOf(sectors.DoorStateStrings),
		"DoorStateValues":            reflect.ValueOf(sectors.DoorStateValues),
		"UnderwaterComponentIndex":   reflect.ValueOf(&sectors.UnderwaterComponentIndex).Elem(),
		"UnderwaterFromDb":           reflect.ValueOf(sectors.UnderwaterFromDb),
		"VerticalDoorComponentIndex": reflect.ValueOf(&sectors.VerticalDoorComponentIndex).Elem(),
		"VerticalDoorFromDb":         reflect.ValueOf(sectors.VerticalDoorFromDb),

		// type definitions
		"DoorIntent":   reflect.ValueOf((*sectors.DoorIntent)(nil)),
		"DoorState":    reflect.ValueOf((*sectors.DoorState)(nil)),
		"Underwater":   reflect.ValueOf((*sectors.Underwater)(nil)),
		"VerticalDoor": reflect.ValueOf((*sectors.VerticalDoor)(nil)),
	}
}
