// Code generated by 'yaegi extract tlyakhov/gofoom/components/audio'. DO NOT EDIT.

//go:build go1.22
// +build go1.22

package scripting_symbols

import (
	"reflect"
	"tlyakhov/gofoom/components/audio"
)

func init() {
	Symbols["tlyakhov/gofoom/components/audio/audio"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"GetMixer":  reflect.ValueOf(audio.GetMixer),
		"GetSound":  reflect.ValueOf(audio.GetSound),
		"GetSource": reflect.ValueOf(audio.GetSource),
		"MixerCID":  reflect.ValueOf(&audio.MixerCID).Elem(),
		"NewDelay":  reflect.ValueOf(audio.NewDelay),
		"PlaySound": reflect.ValueOf(audio.PlaySound),
		"SoundCID":  reflect.ValueOf(&audio.SoundCID).Elem(),
		"SourceCID": reflect.ValueOf(&audio.SourceCID).Elem(),

		// type definitions
		"BitCrush":   reflect.ValueOf((*audio.BitCrush)(nil)),
		"Delay":      reflect.ValueOf((*audio.Delay)(nil)),
		"Effect":     reflect.ValueOf((*audio.Effect)(nil)),
		"Mixer":      reflect.ValueOf((*audio.Mixer)(nil)),
		"Sound":      reflect.ValueOf((*audio.Sound)(nil)),
		"SoundEvent": reflect.ValueOf((*audio.SoundEvent)(nil)),
		"Source":     reflect.ValueOf((*audio.Source)(nil)),

		// interface wrapper definitions
		"_Effect": reflect.ValueOf((*_tlyakhov_gofoom_components_audio_Effect)(nil)),
	}
}

// _tlyakhov_gofoom_components_audio_Effect is an interface wrapper for Effect type
type _tlyakhov_gofoom_components_audio_Effect struct {
	IValue   interface{}
	WProcess func(data []int16)
}

func (W _tlyakhov_gofoom_components_audio_Effect) Process(data []int16) {
	W.WProcess(data)
}
