// Code generated by 'yaegi extract tlyakhov/gofoom/components/selection'. DO NOT EDIT.

//go:build go1.25
// +build go1.25

package scripting_symbols

import (
	"reflect"
	"tlyakhov/gofoom/components/selection"
)

func init() {
	Symbols["tlyakhov/gofoom/components/selection/selection"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"NewSelection":                   reflect.ValueOf(selection.NewSelection),
		"NewSelectionClone":              reflect.ValueOf(selection.NewSelectionClone),
		"SelectableActionWaypoint":       reflect.ValueOf(selection.SelectableActionWaypoint),
		"SelectableBody":                 reflect.ValueOf(selection.SelectableBody),
		"SelectableCeiling":              reflect.ValueOf(selection.SelectableCeiling),
		"SelectableEntity":               reflect.ValueOf(selection.SelectableEntity),
		"SelectableFloor":                reflect.ValueOf(selection.SelectableFloor),
		"SelectableFromActionWaypoint":   reflect.ValueOf(selection.SelectableFromActionWaypoint),
		"SelectableFromBody":             reflect.ValueOf(selection.SelectableFromBody),
		"SelectableFromCeil":             reflect.ValueOf(selection.SelectableFromCeil),
		"SelectableFromEntity":           reflect.ValueOf(selection.SelectableFromEntity),
		"SelectableFromFloor":            reflect.ValueOf(selection.SelectableFromFloor),
		"SelectableFromInternalSegment":  reflect.ValueOf(selection.SelectableFromInternalSegment),
		"SelectableFromInternalSegmentA": reflect.ValueOf(selection.SelectableFromInternalSegmentA),
		"SelectableFromInternalSegmentB": reflect.ValueOf(selection.SelectableFromInternalSegmentB),
		"SelectableFromSector":           reflect.ValueOf(selection.SelectableFromSector),
		"SelectableFromSegment":          reflect.ValueOf(selection.SelectableFromSegment),
		"SelectableFromWall":             reflect.ValueOf(selection.SelectableFromWall),
		"SelectableHi":                   reflect.ValueOf(selection.SelectableHi),
		"SelectableInternalSegment":      reflect.ValueOf(selection.SelectableInternalSegment),
		"SelectableInternalSegmentA":     reflect.ValueOf(selection.SelectableInternalSegmentA),
		"SelectableInternalSegmentB":     reflect.ValueOf(selection.SelectableInternalSegmentB),
		"SelectableLow":                  reflect.ValueOf(selection.SelectableLow),
		"SelectableMid":                  reflect.ValueOf(selection.SelectableMid),
		"SelectablePath":                 reflect.ValueOf(selection.SelectablePath),
		"SelectableSector":               reflect.ValueOf(selection.SelectableSector),
		"SelectableSectorSegment":        reflect.ValueOf(selection.SelectableSectorSegment),
		"SelectableTypeString":           reflect.ValueOf(selection.SelectableTypeString),
		"SelectableTypeStrings":          reflect.ValueOf(selection.SelectableTypeStrings),
		"SelectableTypeValues":           reflect.ValueOf(selection.SelectableTypeValues),

		// type definitions
		"Selectable":     reflect.ValueOf((*selection.Selectable)(nil)),
		"SelectableType": reflect.ValueOf((*selection.SelectableType)(nil)),
		"Selection":      reflect.ValueOf((*selection.Selection)(nil)),
	}
}
