// Code generated by 'yaegi extract tlyakhov/gofoom/dynamic'. DO NOT EDIT.

//go:build go1.25
// +build go1.25

package scripting_symbols

import (
	"go/constant"
	"go/token"
	"reflect"
	"tlyakhov/gofoom/dynamic"
)

func init() {
	Symbols["tlyakhov/gofoom/dynamic/dynamic"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"AnimationCoordinatesAbsolute": reflect.ValueOf(dynamic.AnimationCoordinatesAbsolute),
		"AnimationCoordinatesRelative": reflect.ValueOf(dynamic.AnimationCoordinatesRelative),
		"AnimationCoordinatesString":   reflect.ValueOf(dynamic.AnimationCoordinatesString),
		"AnimationCoordinatesStrings":  reflect.ValueOf(dynamic.AnimationCoordinatesStrings),
		"AnimationCoordinatesValues":   reflect.ValueOf(dynamic.AnimationCoordinatesValues),
		"AnimationLifetimeBounce":      reflect.ValueOf(dynamic.AnimationLifetimeBounce),
		"AnimationLifetimeBounceOnce":  reflect.ValueOf(dynamic.AnimationLifetimeBounceOnce),
		"AnimationLifetimeLoop":        reflect.ValueOf(dynamic.AnimationLifetimeLoop),
		"AnimationLifetimeOnce":        reflect.ValueOf(dynamic.AnimationLifetimeOnce),
		"AnimationLifetimeString":      reflect.ValueOf(dynamic.AnimationLifetimeString),
		"AnimationLifetimeStrings":     reflect.ValueOf(dynamic.AnimationLifetimeStrings),
		"AnimationLifetimeValues":      reflect.ValueOf(dynamic.AnimationLifetimeValues),
		"DynamicStateString":           reflect.ValueOf(dynamic.DynamicStateString),
		"DynamicStateStrings":          reflect.ValueOf(dynamic.DynamicStateStrings),
		"DynamicStateValues":           reflect.ValueOf(dynamic.DynamicStateValues),
		"DynamicStates":                reflect.ValueOf(dynamic.DynamicStates),
		"EaseIn2":                      reflect.ValueOf(dynamic.EaseIn2),
		"EaseIn3":                      reflect.ValueOf(dynamic.EaseIn3),
		"EaseIn4":                      reflect.ValueOf(dynamic.EaseIn4),
		"EaseInOut2":                   reflect.ValueOf(dynamic.EaseInOut2),
		"EaseInOut3":                   reflect.ValueOf(dynamic.EaseInOut3),
		"EaseInOut4":                   reflect.ValueOf(dynamic.EaseInOut4),
		"EaseOut2":                     reflect.ValueOf(dynamic.EaseOut2),
		"EaseOut3":                     reflect.ValueOf(dynamic.EaseOut3),
		"EaseOut4":                     reflect.ValueOf(dynamic.EaseOut4),
		"ElasticIn":                    reflect.ValueOf(dynamic.ElasticIn),
		"ElasticInOut":                 reflect.ValueOf(dynamic.ElasticInOut),
		"ElasticOut":                   reflect.ValueOf(dynamic.ElasticOut),
		"EventClasses":                 reflect.ValueOf(dynamic.EventClasses),
		"Lerp":                         reflect.ValueOf(dynamic.Lerp),
		"MaxEvents":                    reflect.ValueOf(constant.MakeFromLiteral("1024", token.INT, 0)),
		"NewSimulation":                reflect.ValueOf(dynamic.NewSimulation),
		"Now":                          reflect.ValueOf(dynamic.Now),
		"Prev":                         reflect.ValueOf(dynamic.Prev),
		"Random":                       reflect.ValueOf(dynamic.Random),
		"RegisterEventClass":           reflect.ValueOf(dynamic.RegisterEventClass),
		"Render":                       reflect.ValueOf(dynamic.Render),
		"Spawn":                        reflect.ValueOf(dynamic.Spawn),
		"Spike":                        reflect.ValueOf(dynamic.Spike),
		"Spike2":                       reflect.ValueOf(dynamic.Spike2),
		"Spike3":                       reflect.ValueOf(dynamic.Spike3),
		"Spike4":                       reflect.ValueOf(dynamic.Spike4),
		"SubscribeToEvent":             reflect.ValueOf(dynamic.SubscribeToEvent),
		"TweenAngles":                  reflect.ValueOf(dynamic.TweenAngles),
		"TweeningFuncNames":            reflect.ValueOf(&dynamic.TweeningFuncNames).Elem(),
		"TweeningFuncs":                reflect.ValueOf(&dynamic.TweeningFuncs).Elem(),

		// type definitions
		"Animated":             reflect.ValueOf((*dynamic.Animated)(nil)),
		"AnimationCoordinates": reflect.ValueOf((*dynamic.AnimationCoordinates)(nil)),
		"AnimationLifetime":    reflect.ValueOf((*dynamic.AnimationLifetime)(nil)),
		"Dynamic":              reflect.ValueOf((*dynamic.Dynamic)(nil)),
		"DynamicState":         reflect.ValueOf((*dynamic.DynamicState)(nil)),
		"Event":                reflect.ValueOf((*dynamic.Event)(nil)),
		"EventClass":           reflect.ValueOf((*dynamic.EventClass)(nil)),
		"EventConsumer":        reflect.ValueOf((*dynamic.EventConsumer)(nil)),
		"EventID":              reflect.ValueOf((*dynamic.EventID)(nil)),
		"EventQueue":           reflect.ValueOf((*dynamic.EventQueue)(nil)),
		"Simulation":           reflect.ValueOf((*dynamic.Simulation)(nil)),
		"Spawnable":            reflect.ValueOf((*dynamic.Spawnable)(nil)),
		"TweeningFunc":         reflect.ValueOf((*dynamic.TweeningFunc)(nil)),

		// interface wrapper definitions
		"_Animated":  reflect.ValueOf((*_tlyakhov_gofoom_dynamic_Animated)(nil)),
		"_Dynamic":   reflect.ValueOf((*_tlyakhov_gofoom_dynamic_Dynamic)(nil)),
		"_Spawnable": reflect.ValueOf((*_tlyakhov_gofoom_dynamic_Spawnable)(nil)),
	}
}

// _tlyakhov_gofoom_dynamic_Animated is an interface wrapper for Animated type
type _tlyakhov_gofoom_dynamic_Animated struct {
	IValue   interface{}
	WAnimate func()
	WReset   func()
}

func (W _tlyakhov_gofoom_dynamic_Animated) Animate() {
	W.WAnimate()
}
func (W _tlyakhov_gofoom_dynamic_Animated) Reset() {
	W.WReset()
}

// _tlyakhov_gofoom_dynamic_Dynamic is an interface wrapper for Dynamic type
type _tlyakhov_gofoom_dynamic_Dynamic struct {
	IValue        interface{}
	WAttach       func(sim *dynamic.Simulation)
	WDetach       func(sim *dynamic.Simulation)
	WGetAnimation func() dynamic.Animated
	WNewFrame     func()
	WNewSimStep   func()
	WPrecompute   func()
	WResetToSpawn func()
	WUpdate       func(a0 float64)
}

func (W _tlyakhov_gofoom_dynamic_Dynamic) Attach(sim *dynamic.Simulation) {
	W.WAttach(sim)
}
func (W _tlyakhov_gofoom_dynamic_Dynamic) Detach(sim *dynamic.Simulation) {
	W.WDetach(sim)
}
func (W _tlyakhov_gofoom_dynamic_Dynamic) GetAnimation() dynamic.Animated {
	return W.WGetAnimation()
}
func (W _tlyakhov_gofoom_dynamic_Dynamic) NewFrame() {
	W.WNewFrame()
}
func (W _tlyakhov_gofoom_dynamic_Dynamic) NewSimStep() {
	W.WNewSimStep()
}
func (W _tlyakhov_gofoom_dynamic_Dynamic) Precompute() {
	W.WPrecompute()
}
func (W _tlyakhov_gofoom_dynamic_Dynamic) ResetToSpawn() {
	W.WResetToSpawn()
}
func (W _tlyakhov_gofoom_dynamic_Dynamic) Update(a0 float64) {
	W.WUpdate(a0)
}

// _tlyakhov_gofoom_dynamic_Spawnable is an interface wrapper for Spawnable type
type _tlyakhov_gofoom_dynamic_Spawnable struct {
	IValue        interface{}
	WAttach       func(sim *dynamic.Simulation)
	WDetach       func(sim *dynamic.Simulation)
	WResetToSpawn func()
}

func (W _tlyakhov_gofoom_dynamic_Spawnable) Attach(sim *dynamic.Simulation) {
	W.WAttach(sim)
}
func (W _tlyakhov_gofoom_dynamic_Spawnable) Detach(sim *dynamic.Simulation) {
	W.WDetach(sim)
}
func (W _tlyakhov_gofoom_dynamic_Spawnable) ResetToSpawn() {
	W.WResetToSpawn()
}
