// Code generated by 'yaegi extract tlyakhov/gofoom/constants'. DO NOT EDIT.

//go:build go1.22
// +build go1.22

package scripting_symbols

import (
	"go/constant"
	"go/token"
	"reflect"
	"tlyakhov/gofoom/constants"
)

func init() {
	Symbols["tlyakhov/gofoom/constants/constants"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"AirDensity":               reflect.ValueOf(constant.MakeFromLiteral("1.2930000000000000000277555756156289135105907917022705078125", token.FLOAT, 0)),
		"AudioUnitsFactor":         reflect.ValueOf(constant.MakeFromLiteral("12", token.INT, 0)),
		"AvatarSrc":                reflect.ValueOf(constant.MakeFromLiteral("\"/data/game/avatar.png\"", token.STRING, 0)),
		"CollisionCheck":           reflect.ValueOf(constant.MakeFromLiteral("2", token.FLOAT, 0)),
		"CollisionSteps":           reflect.ValueOf(constant.MakeFromLiteral("10", token.INT, 0)),
		"DebugLevel":               reflect.ValueOf(constant.MakeFromLiteral("1", token.INT, 0)),
		"DebugLighting":            reflect.ValueOf(constants.DebugLighting),
		"FieldOfView":              reflect.ValueOf(constant.MakeFromLiteral("90", token.INT, 0)),
		"FirstMap":                 reflect.ValueOf(constant.MakeFromLiteral("\"testMap\"", token.STRING, 0)),
		"GameTextFadeTime":         reflect.ValueOf(constant.MakeFromLiteral("1000", token.INT, 0)),
		"Gravity":                  reflect.ValueOf(constant.MakeFromLiteral("9.800000000000000000173472347597680709441192448139190673828125", token.FLOAT, 0)),
		"GravitySwim":              reflect.ValueOf(constant.MakeFromLiteral("0.1000000000000000000013552527156068805425093160010874271392822266", token.FLOAT, 0)),
		"InfoBarSrc":               reflect.ValueOf(constant.MakeFromLiteral("\"/data/game/infobar.png\"", token.STRING, 0)),
		"InteractionDistance":      reflect.ValueOf(constant.MakeFromLiteral("70", token.INT, 0)),
		"IntersectEpsilon":         reflect.ValueOf(constant.MakeFromLiteral("1.000000000000000000018377930495836641360156492146227247275191985e-10", token.FLOAT, 0)),
		"InventoryGatherDistance":  reflect.ValueOf(constant.MakeFromLiteral("30", token.INT, 0)),
		"InventoryGatherTextStyle": reflect.ValueOf(constant.MakeFromLiteral("\"#666\"", token.STRING, 0)),
		"LightAttenuationEpsilon":  reflect.ValueOf(constant.MakeFromLiteral("0.0009999999999999999999584953855845392833856521974666975438594818115", token.FLOAT, 0)),
		"LightGrid":                reflect.ValueOf(constant.MakeFromLiteral("4", token.FLOAT, 0)),
		"LightmapRefreshDither":    reflect.ValueOf(constant.MakeFromLiteral("4", token.INT, 0)),
		"LiquidChurnSize":          reflect.ValueOf(constant.MakeFromLiteral("0.02999999999999999999939013627797690375587080779951065778732299805", token.FLOAT, 0)),
		"LiquidChurnSpeed":         reflect.ValueOf(constant.MakeFromLiteral("2", token.FLOAT, 0)),
		"MaxGameText":              reflect.ValueOf(constant.MakeFromLiteral("25", token.INT, 0)),
		"MaxGameTextTime":          reflect.ValueOf(constant.MakeFromLiteral("15000", token.INT, 0)),
		"MaxLightmapAge":           reflect.ValueOf(constant.MakeFromLiteral("3", token.INT, 0)),
		"MaxPortals":               reflect.ValueOf(constant.MakeFromLiteral("300", token.INT, 0)),
		"MaxViewDistance":          reflect.ValueOf(constant.MakeFromLiteral("10000", token.FLOAT, 0)),
		"MaxWeaponMarks":           reflect.ValueOf(constant.MakeFromLiteral("30", token.INT, 0)),
		"MetersPerUnit":            reflect.ValueOf(constant.MakeFromLiteral("0.03125", token.FLOAT, 0)),
		"MinMillisPerFrame":        reflect.ValueOf(constant.MakeFromLiteral("100", token.FLOAT, 0)),
		"PlayerBoundingRadius":     reflect.ValueOf(constant.MakeFromLiteral("10", token.FLOAT, 0)),
		"PlayerCrouchHeight":       reflect.ValueOf(constant.MakeFromLiteral("16", token.FLOAT, 0)),
		"PlayerHeight":             reflect.ValueOf(constant.MakeFromLiteral("40", token.FLOAT, 0)),
		"PlayerHurtTime":           reflect.ValueOf(constant.MakeFromLiteral("30", token.INT, 0)),
		"PlayerJumpForce":          reflect.ValueOf(constant.MakeFromLiteral("37500", token.FLOAT, 0)),
		"PlayerMass":               reflect.ValueOf(constant.MakeFromLiteral("80", token.FLOAT, 0)),
		"PlayerMaxHealth":          reflect.ValueOf(constant.MakeFromLiteral("100", token.INT, 0)),
		"PlayerMountHeight":        reflect.ValueOf(constant.MakeFromLiteral("15", token.FLOAT, 0)),
		"PlayerSwimStrength":       reflect.ValueOf(constant.MakeFromLiteral("12500", token.FLOAT, 0)),
		"PlayerTurnSpeed":          reflect.ValueOf(constant.MakeFromLiteral("180", token.FLOAT, 0)),
		"PlayerWalkForce":          reflect.ValueOf(constant.MakeFromLiteral("6250", token.FLOAT, 0)),
		"RenderBlocks":             reflect.ValueOf(constant.MakeFromLiteral("32", token.INT, 0)),
		"RenderMultiThreaded":      reflect.ValueOf(constants.RenderMultiThreaded),
		"SourcesPerSound":          reflect.ValueOf(constant.MakeFromLiteral("8", token.INT, 0)),
		"SphereDragCoefficient":    reflect.ValueOf(constant.MakeFromLiteral("0.4699999999999999999989157978275144955659925471991300582885742188", token.FLOAT, 0)),
		"SwimDamping":              reflect.ValueOf(constant.MakeFromLiteral("1.5", token.FLOAT, 0)),
		"TimeStep":                 reflect.ValueOf(constant.MakeFromLiteral("7.8125", token.FLOAT, 0)),
		"TimeStepS":                reflect.ValueOf(constant.MakeFromLiteral("0.0078125", token.FLOAT, 0)),
		"UnitsPerMeter":            reflect.ValueOf(constant.MakeFromLiteral("32", token.FLOAT, 0)),
		"UserSettings":             reflect.ValueOf(constant.MakeFromLiteral("\"settings.json\"", token.STRING, 0)),
		"VelocityEpsilon":          reflect.ValueOf(constant.MakeFromLiteral("9.99999999999999999994126620636112567498475617893197842480160209e-16", token.FLOAT, 0)),
		"WanderSectorProbability":  reflect.ValueOf(constant.MakeFromLiteral("0.25", token.FLOAT, 0)),
	}
}
