// Code generated by 'yaegi extract tlyakhov/gofoom/components/materials'. DO NOT EDIT.

//go:build go1.22
// +build go1.22

package scripting_symbols

import (
	"reflect"
	"tlyakhov/gofoom/components/materials"
)

func init() {
	Symbols["tlyakhov/gofoom/components/materials/materials"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"ImageComponentIndex":       reflect.ValueOf(&materials.ImageComponentIndex).Elem(),
		"ImageFromDb":               reflect.ValueOf(materials.ImageFromDb),
		"LitComponentIndex":         reflect.ValueOf(&materials.LitComponentIndex).Elem(),
		"LitFromDb":                 reflect.ValueOf(materials.LitFromDb),
		"ShaderComponentIndex":      reflect.ValueOf(&materials.ShaderComponentIndex).Elem(),
		"ShaderFlagsString":         reflect.ValueOf(materials.ShaderFlagsString),
		"ShaderFlagsStrings":        reflect.ValueOf(materials.ShaderFlagsStrings),
		"ShaderFlagsValues":         reflect.ValueOf(materials.ShaderFlagsValues),
		"ShaderFromDb":              reflect.ValueOf(materials.ShaderFromDb),
		"ShaderLiquid":              reflect.ValueOf(materials.ShaderLiquid),
		"ShaderSky":                 reflect.ValueOf(materials.ShaderSky),
		"ShaderStaticBackground":    reflect.ValueOf(materials.ShaderStaticBackground),
		"ShaderTiled":               reflect.ValueOf(materials.ShaderTiled),
		"SolidComponentIndex":       reflect.ValueOf(&materials.SolidComponentIndex).Elem(),
		"SolidFromDb":               reflect.ValueOf(materials.SolidFromDb),
		"SpriteSheetComponentIndex": reflect.ValueOf(&materials.SpriteSheetComponentIndex).Elem(),
		"SpriteSheetFromDb":         reflect.ValueOf(materials.SpriteSheetFromDb),
		"StretchAspect":             reflect.ValueOf(materials.StretchAspect),
		"StretchFill":               reflect.ValueOf(materials.StretchFill),
		"StretchNone":               reflect.ValueOf(materials.StretchNone),
		"SurfaceStretchString":      reflect.ValueOf(materials.SurfaceStretchString),
		"SurfaceStretchStrings":     reflect.ValueOf(materials.SurfaceStretchStrings),
		"SurfaceStretchValues":      reflect.ValueOf(materials.SurfaceStretchValues),
		"TextComponentIndex":        reflect.ValueOf(&materials.TextComponentIndex).Elem(),
		"TextFromDb":                reflect.ValueOf(materials.TextFromDb),

		// type definitions
		"Image":          reflect.ValueOf((*materials.Image)(nil)),
		"Lit":            reflect.ValueOf((*materials.Lit)(nil)),
		"Shader":         reflect.ValueOf((*materials.Shader)(nil)),
		"ShaderFlags":    reflect.ValueOf((*materials.ShaderFlags)(nil)),
		"ShaderStage":    reflect.ValueOf((*materials.ShaderStage)(nil)),
		"Solid":          reflect.ValueOf((*materials.Solid)(nil)),
		"Sprite":         reflect.ValueOf((*materials.Sprite)(nil)),
		"SpriteSheet":    reflect.ValueOf((*materials.SpriteSheet)(nil)),
		"Surface":        reflect.ValueOf((*materials.Surface)(nil)),
		"SurfaceStretch": reflect.ValueOf((*materials.SurfaceStretch)(nil)),
		"Text":           reflect.ValueOf((*materials.Text)(nil)),
	}
}
