// Code generated by 'yaegi extract tlyakhov/gofoom/pathfinding'. DO NOT EDIT.

//go:build go1.26
// +build go1.26

package scripting_symbols

import (
	"reflect"
	"tlyakhov/gofoom/pathfinding"
)

func init() {
	Symbols["tlyakhov/gofoom/pathfinding/pathfinding"] = map[string]reflect.Value{
		// type definitions
		"Finder":               reflect.ValueOf((*pathfinding.Finder)(nil)),
		"SectorTraversalCheck": reflect.ValueOf((*pathfinding.SectorTraversalCheck)(nil)),
	}
}
