// Code generated by 'yaegi extract tlyakhov/gofoom/components/character'. DO NOT EDIT.

//go:build go1.25
// +build go1.25

package scripting_symbols

import (
	"reflect"
	"tlyakhov/gofoom/components/character"
)

func init() {
	Symbols["tlyakhov/gofoom/components/character/character"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"GetNpc":             reflect.ValueOf(character.GetNpc),
		"GetPlayer":          reflect.ValueOf(character.GetPlayer),
		"NpcCID":             reflect.ValueOf(&character.NpcCID).Elem(),
		"NpcStateCount":      reflect.ValueOf(character.NpcStateCount),
		"NpcStateDead":       reflect.ValueOf(character.NpcStateDead),
		"NpcStateIdle":       reflect.ValueOf(character.NpcStateIdle),
		"NpcStateLostTarget": reflect.ValueOf(character.NpcStateLostTarget),
		"NpcStatePursuit":    reflect.ValueOf(character.NpcStatePursuit),
		"NpcStateSawTarget":  reflect.ValueOf(character.NpcStateSawTarget),
		"NpcStateSearching":  reflect.ValueOf(character.NpcStateSearching),
		"NpcStateString":     reflect.ValueOf(character.NpcStateString),
		"NpcStateStrings":    reflect.ValueOf(character.NpcStateStrings),
		"NpcStateValues":     reflect.ValueOf(character.NpcStateValues),
		"PlayerCID":          reflect.ValueOf(&character.PlayerCID).Elem(),

		// type definitions
		"Npc":      reflect.ValueOf((*character.Npc)(nil)),
		"NpcState": reflect.ValueOf((*character.NpcState)(nil)),
		"Player":   reflect.ValueOf((*character.Player)(nil)),
	}
}
