// Code generated by 'yaegi extract tlyakhov/gofoom/components/behaviors'. DO NOT EDIT.

//go:build go1.22
// +build go1.22

package scripting_symbols

import (
	"reflect"
	"tlyakhov/gofoom/components/behaviors"
)

func init() {
	Symbols["tlyakhov/gofoom/components/behaviors/behaviors"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"AliveCID":          reflect.ValueOf(&behaviors.AliveCID).Elem(),
		"DoorIntentClosed":  reflect.ValueOf(behaviors.DoorIntentClosed),
		"DoorIntentOpen":    reflect.ValueOf(behaviors.DoorIntentOpen),
		"DoorIntentReset":   reflect.ValueOf(behaviors.DoorIntentReset),
		"DoorIntentString":  reflect.ValueOf(behaviors.DoorIntentString),
		"DoorIntentStrings": reflect.ValueOf(behaviors.DoorIntentStrings),
		"DoorIntentValues":  reflect.ValueOf(behaviors.DoorIntentValues),
		"DoorStateClosed":   reflect.ValueOf(behaviors.DoorStateClosed),
		"DoorStateClosing":  reflect.ValueOf(behaviors.DoorStateClosing),
		"DoorStateOpen":     reflect.ValueOf(behaviors.DoorStateOpen),
		"DoorStateOpening":  reflect.ValueOf(behaviors.DoorStateOpening),
		"DoorStateString":   reflect.ValueOf(behaviors.DoorStateString),
		"DoorStateStrings":  reflect.ValueOf(behaviors.DoorStateStrings),
		"DoorStateValues":   reflect.ValueOf(behaviors.DoorStateValues),
		"FollowerCID":       reflect.ValueOf(&behaviors.FollowerCID).Elem(),
		"GetAlive":          reflect.ValueOf(behaviors.GetAlive),
		"GetFollower":       reflect.ValueOf(behaviors.GetFollower),
		"GetInventoryItem":  reflect.ValueOf(behaviors.GetInventoryItem),
		"GetPlayer":         reflect.ValueOf(behaviors.GetPlayer),
		"GetProximity":      reflect.ValueOf(behaviors.GetProximity),
		"GetUnderwater":     reflect.ValueOf(behaviors.GetUnderwater),
		"GetVerticalDoor":   reflect.ValueOf(behaviors.GetVerticalDoor),
		"GetWander":         reflect.ValueOf(behaviors.GetWander),
		"GetWeaponInstant":  reflect.ValueOf(behaviors.GetWeaponInstant),
		"InventoryItemCID":  reflect.ValueOf(&behaviors.InventoryItemCID).Elem(),
		"PlayerCID":         reflect.ValueOf(&behaviors.PlayerCID).Elem(),
		"ProximityCID":      reflect.ValueOf(&behaviors.ProximityCID).Elem(),
		"UnderwaterCID":     reflect.ValueOf(&behaviors.UnderwaterCID).Elem(),
		"VerticalDoorCID":   reflect.ValueOf(&behaviors.VerticalDoorCID).Elem(),
		"WanderCID":         reflect.ValueOf(&behaviors.WanderCID).Elem(),
		"WeaponInstantCID":  reflect.ValueOf(&behaviors.WeaponInstantCID).Elem(),

		// type definitions
		"Alive":         reflect.ValueOf((*behaviors.Alive)(nil)),
		"Damage":        reflect.ValueOf((*behaviors.Damage)(nil)),
		"DoorIntent":    reflect.ValueOf((*behaviors.DoorIntent)(nil)),
		"DoorState":     reflect.ValueOf((*behaviors.DoorState)(nil)),
		"Follower":      reflect.ValueOf((*behaviors.Follower)(nil)),
		"InventoryItem": reflect.ValueOf((*behaviors.InventoryItem)(nil)),
		"InventorySlot": reflect.ValueOf((*behaviors.InventorySlot)(nil)),
		"Player":        reflect.ValueOf((*behaviors.Player)(nil)),
		"Proximity":     reflect.ValueOf((*behaviors.Proximity)(nil)),
		"Underwater":    reflect.ValueOf((*behaviors.Underwater)(nil)),
		"VerticalDoor":  reflect.ValueOf((*behaviors.VerticalDoor)(nil)),
		"Wander":        reflect.ValueOf((*behaviors.Wander)(nil)),
		"WeaponInstant": reflect.ValueOf((*behaviors.WeaponInstant)(nil)),
		"WeaponMark":    reflect.ValueOf((*behaviors.WeaponMark)(nil)),
	}
}
