// Code generated by 'yaegi extract tlyakhov/gofoom/components/audio'. DO NOT EDIT.

//go:build go1.22
// +build go1.22

package scripting_symbols

import (
	"go/constant"
	"go/token"
	"reflect"
	"tlyakhov/gofoom/components/audio"
)

func init() {
	Symbols["tlyakhov/gofoom/components/audio/audio"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"GetSound":           reflect.ValueOf(audio.GetSound),
		"GetSoundEvent":      reflect.ValueOf(audio.GetSoundEvent),
		"GetSource":          reflect.ValueOf(audio.GetSource),
		"Mixer":              reflect.ValueOf(&audio.Mixer).Elem(),
		"NewConvReverb":      reflect.ValueOf(audio.NewConvReverb),
		"PlaySound":          reflect.ValueOf(audio.PlaySound),
		"SetReverbPreset":    reflect.ValueOf(audio.SetReverbPreset),
		"SoundCID":           reflect.ValueOf(&audio.SoundCID).Elem(),
		"SoundEventCID":      reflect.ValueOf(&audio.SoundEventCID).Elem(),
		"SourceCID":          reflect.ValueOf(&audio.SourceCID).Elem(),
		"WavFormatALaw":      reflect.ValueOf(constant.MakeFromLiteral("6", token.INT, 0)),
		"WavFormatIEEEFloat": reflect.ValueOf(constant.MakeFromLiteral("3", token.INT, 0)),
		"WavFormatMuLaw":     reflect.ValueOf(constant.MakeFromLiteral("7", token.INT, 0)),
		"WavFormatPCM":       reflect.ValueOf(constant.MakeFromLiteral("1", token.INT, 0)),

		// type definitions
		"ConvReverb": reflect.ValueOf((*audio.ConvReverb)(nil)),
		"Sound":      reflect.ValueOf((*audio.Sound)(nil)),
		"SoundEvent": reflect.ValueOf((*audio.SoundEvent)(nil)),
		"Source":     reflect.ValueOf((*audio.Source)(nil)),
	}
}
