// Code generated by 'yaegi extract tlyakhov/gofoom/controllers'. DO NOT EDIT.

//go:build go1.22
// +build go1.22

package scripting_symbols

import (
	"reflect"
	"tlyakhov/gofoom/controllers"
)

func init() {
	Symbols["tlyakhov/gofoom/controllers/controllers"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"AutoPortal":                reflect.ValueOf(controllers.AutoPortal),
		"BodySectorScript":          reflect.ValueOf(controllers.BodySectorScript),
		"CreateSpawn":               reflect.ValueOf(controllers.CreateSpawn),
		"CreateTestDirt":            reflect.ValueOf(controllers.CreateTestDirt),
		"CreateTestGrass":           reflect.ValueOf(controllers.CreateTestGrass),
		"CreateTestHeightmapSector": reflect.ValueOf(controllers.CreateTestHeightmapSector),
		"CreateTestSector":          reflect.ValueOf(controllers.CreateTestSector),
		"CreateTestSky":             reflect.ValueOf(controllers.CreateTestSky),
		"CreateTestTree":            reflect.ValueOf(controllers.CreateTestTree),
		"CreateTestWorld":           reflect.ValueOf(controllers.CreateTestWorld),
		"CreateTestWorld2":          reflect.ValueOf(controllers.CreateTestWorld2),
		"CreateTestWorld3":          reflect.ValueOf(controllers.CreateTestWorld3),
		"DefaultMaterial":           reflect.ValueOf(controllers.DefaultMaterial),
		"MovePlayer":                reflect.ValueOf(controllers.MovePlayer),
		"MovePlayerForce":           reflect.ValueOf(controllers.MovePlayerForce),
		"MovePlayerNoClip":          reflect.ValueOf(controllers.MovePlayerNoClip),
		"PickUpInventoryItem":       reflect.ValueOf(controllers.PickUpInventoryItem),
		"ResetAllSpawnables":        reflect.ValueOf(controllers.ResetAllSpawnables),
		"Respawn":                   reflect.ValueOf(controllers.Respawn),

		// type definitions
		"ActionController":           reflect.ValueOf((*controllers.ActionController)(nil)),
		"AliveController":            reflect.ValueOf((*controllers.AliveController)(nil)),
		"BodyController":             reflect.ValueOf((*controllers.BodyController)(nil)),
		"ImageController":            reflect.ValueOf((*controllers.ImageController)(nil)),
		"InternalSegmentController":  reflect.ValueOf((*controllers.InternalSegmentController)(nil)),
		"InventoryItemController":    reflect.ValueOf((*controllers.InventoryItemController)(nil)),
		"InventorySlotController":    reflect.ValueOf((*controllers.InventorySlotController)(nil)),
		"MobileController":           reflect.ValueOf((*controllers.MobileController)(nil)),
		"ParticleController":         reflect.ValueOf((*controllers.ParticleController)(nil)),
		"PlayerController":           reflect.ValueOf((*controllers.PlayerController)(nil)),
		"PlayerTargetableController": reflect.ValueOf((*controllers.PlayerTargetableController)(nil)),
		"ProximityController":        reflect.ValueOf((*controllers.ProximityController)(nil)),
		"SectorController":           reflect.ValueOf((*controllers.SectorController)(nil)),
		"SectorSplitter":             reflect.ValueOf((*controllers.SectorSplitter)(nil)),
		"SoundController":            reflect.ValueOf((*controllers.SoundController)(nil)),
		"SoundEventController":       reflect.ValueOf((*controllers.SoundEventController)(nil)),
		"UnderwaterController":       reflect.ValueOf((*controllers.UnderwaterController)(nil)),
		"VerticalDoorController":     reflect.ValueOf((*controllers.VerticalDoorController)(nil)),
		"WanderController":           reflect.ValueOf((*controllers.WanderController)(nil)),
		"WeaponController":           reflect.ValueOf((*controllers.WeaponController)(nil)),
	}
}
