// Code generated by 'yaegi extract tlyakhov/gofoom/components/core'. DO NOT EDIT.

//go:build go1.22
// +build go1.22

package scripting_symbols

import (
	"reflect"
	"tlyakhov/gofoom/components/core"
)

func init() {
	Symbols["tlyakhov/gofoom/components/core/core"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"BodyCID":                  reflect.ValueOf(&core.BodyCID).Elem(),
		"CollideBounce":            reflect.ValueOf(core.CollideBounce),
		"CollideDeactivate":        reflect.ValueOf(core.CollideDeactivate),
		"CollideNone":              reflect.ValueOf(core.CollideNone),
		"CollideRemove":            reflect.ValueOf(core.CollideRemove),
		"CollideSeparate":          reflect.ValueOf(core.CollideSeparate),
		"CollideStop":              reflect.ValueOf(core.CollideStop),
		"CollisionResponseString":  reflect.ValueOf(core.CollisionResponseString),
		"CollisionResponseStrings": reflect.ValueOf(core.CollisionResponseStrings),
		"CollisionResponseValues":  reflect.ValueOf(core.CollisionResponseValues),
		"GetBody":                  reflect.ValueOf(core.GetBody),
		"GetInternalSegment":       reflect.ValueOf(core.GetInternalSegment),
		"GetLight":                 reflect.ValueOf(core.GetLight),
		"GetMobile":                reflect.ValueOf(core.GetMobile),
		"GetScripted":              reflect.ValueOf(core.GetScripted),
		"GetSector":                reflect.ValueOf(core.GetSector),
		"InternalSegmentCID":       reflect.ValueOf(&core.InternalSegmentCID).Elem(),
		"LightCID":                 reflect.ValueOf(&core.LightCID).Elem(),
		"MobileCID":                reflect.ValueOf(&core.MobileCID).Elem(),
		"QuadTree":                 reflect.ValueOf(&core.QuadTree).Elem(),
		"ScriptedCID":              reflect.ValueOf(&core.ScriptedCID).Elem(),
		"SectorCID":                reflect.ValueOf(&core.SectorCID).Elem(),

		// type definitions
		"Body":              reflect.ValueOf((*core.Body)(nil)),
		"CollisionResponse": reflect.ValueOf((*core.CollisionResponse)(nil)),
		"InternalSegment":   reflect.ValueOf((*core.InternalSegment)(nil)),
		"Light":             reflect.ValueOf((*core.Light)(nil)),
		"LightmapCell":      reflect.ValueOf((*core.LightmapCell)(nil)),
		"Mobile":            reflect.ValueOf((*core.Mobile)(nil)),
		"QuadNode":          reflect.ValueOf((*core.QuadNode)(nil)),
		"Script":            reflect.ValueOf((*core.Script)(nil)),
		"ScriptParam":       reflect.ValueOf((*core.ScriptParam)(nil)),
		"Scripted":          reflect.ValueOf((*core.Scripted)(nil)),
		"Sector":            reflect.ValueOf((*core.Sector)(nil)),
		"SectorPlane":       reflect.ValueOf((*core.SectorPlane)(nil)),
		"SectorSegment":     reflect.ValueOf((*core.SectorSegment)(nil)),
		"Segment":           reflect.ValueOf((*core.Segment)(nil)),
	}
}
