// Code generated by 'yaegi extract tlyakhov/gofoom/components/character'. DO NOT EDIT.

//go:build go1.25
// +build go1.25

package scripting_symbols

import (
	"reflect"
	"tlyakhov/gofoom/components/character"
)

func init() {
	Symbols["tlyakhov/gofoom/components/character/character"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"GetPlayer": reflect.ValueOf(character.GetPlayer),
		"PlayerCID": reflect.ValueOf(&character.PlayerCID).Elem(),

		// type definitions
		"Player": reflect.ValueOf((*character.Player)(nil)),
	}
}
