// Code generated by 'yaegi extract tlyakhov/gofoom/components/materials'. DO NOT EDIT.

//go:build go1.21
// +build go1.21

package scripting_symbols

import (
	"reflect"
	"tlyakhov/gofoom/components/materials"
)

func init() {
	Symbols["tlyakhov/gofoom/components/materials/materials"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"ConstructSprites":          reflect.ValueOf(materials.ConstructSprites),
		"ImageComponentIndex":       reflect.ValueOf(&materials.ImageComponentIndex).Elem(),
		"ImageFromDb":               reflect.ValueOf(materials.ImageFromDb),
		"LitComponentIndex":         reflect.ValueOf(&materials.LitComponentIndex).Elem(),
		"LitFromDb":                 reflect.ValueOf(materials.LitFromDb),
		"SerializeSprites":          reflect.ValueOf(materials.SerializeSprites),
		"ShaderComponentIndex":      reflect.ValueOf(&materials.ShaderComponentIndex).Elem(),
		"ShaderFromDb":              reflect.ValueOf(materials.ShaderFromDb),
		"SkyComponentIndex":         reflect.ValueOf(&materials.SkyComponentIndex).Elem(),
		"SkyFromDb":                 reflect.ValueOf(materials.SkyFromDb),
		"SolidComponentIndex":       reflect.ValueOf(&materials.SolidComponentIndex).Elem(),
		"SolidFromDb":               reflect.ValueOf(materials.SolidFromDb),
		"SpriteSheetComponentIndex": reflect.ValueOf(&materials.SpriteSheetComponentIndex).Elem(),
		"SpriteSheetFromDb":         reflect.ValueOf(materials.SpriteSheetFromDb),
		"TextComponentIndex":        reflect.ValueOf(&materials.TextComponentIndex).Elem(),
		"TextFromDb":                reflect.ValueOf(materials.TextFromDb),
		"TiledComponentIndex":       reflect.ValueOf(&materials.TiledComponentIndex).Elem(),
		"TiledFromDb":               reflect.ValueOf(materials.TiledFromDb),

		// type definitions
		"Image":       reflect.ValueOf((*materials.Image)(nil)),
		"Lit":         reflect.ValueOf((*materials.Lit)(nil)),
		"Shader":      reflect.ValueOf((*materials.Shader)(nil)),
		"ShaderStage": reflect.ValueOf((*materials.ShaderStage)(nil)),
		"Sky":         reflect.ValueOf((*materials.Sky)(nil)),
		"Solid":       reflect.ValueOf((*materials.Solid)(nil)),
		"Sprite":      reflect.ValueOf((*materials.Sprite)(nil)),
		"SpriteSheet": reflect.ValueOf((*materials.SpriteSheet)(nil)),
		"Text":        reflect.ValueOf((*materials.Text)(nil)),
		"Tiled":       reflect.ValueOf((*materials.Tiled)(nil)),
	}
}
