// Code generated by 'yaegi extract tlyakhov/gofoom/ecs'. DO NOT EDIT.

//go:build go1.22
// +build go1.22

package scripting_symbols

import (
	"go/constant"
	"go/token"
	"reflect"
	"tlyakhov/gofoom/ecs"
)

func init() {
	Symbols["tlyakhov/gofoom/ecs/ecs"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"ComponentHideInEditor":        reflect.ValueOf(ecs.ComponentHideInEditor),
		"ComponentInternal":            reflect.ValueOf(ecs.ComponentInternal),
		"ComponentLockedInEditor":      reflect.ValueOf(ecs.ComponentLockedInEditor),
		"ComponentNoSave":              reflect.ValueOf(ecs.ComponentNoSave),
		"ComponentTableGrowthRate":     reflect.ValueOf(constant.MakeFromLiteral("8", token.INT, 0)),
		"ComponentTableHit":            reflect.ValueOf(&ecs.ComponentTableHit).Elem(),
		"ComponentTableMiss":           reflect.ValueOf(&ecs.ComponentTableMiss).Elem(),
		"ConstructArray":               reflect.ValueOf(ecs.ConstructArray),
		"ControllerAlways":             reflect.ValueOf(ecs.ControllerAlways),
		"ControllerRecalculate":        reflect.ValueOf(ecs.ControllerRecalculate),
		"EntityBits":                   reflect.ValueOf(constant.MakeFromLiteral("24", token.INT, 0)),
		"EntityDelimiter":              reflect.ValueOf(constant.MakeFromLiteral("\"∈⋮\"", token.STRING, 0)),
		"EntityHumanRegexp":            reflect.ValueOf(&ecs.EntityHumanRegexp).Elem(),
		"EntityHumanRegexpIdxEntity":   reflect.ValueOf(constant.MakeFromLiteral("1", token.INT, 0)),
		"EntityHumanRegexpIdxMatch":    reflect.ValueOf(constant.MakeFromLiteral("0", token.INT, 0)),
		"EntityHumanRegexpIdxSourceID": reflect.ValueOf(constant.MakeFromLiteral("2", token.INT, 0)),
		"EntityRegexp":                 reflect.ValueOf(&ecs.EntityRegexp).Elem(),
		"EntityRegexpIdxEntity":        reflect.ValueOf(constant.MakeFromLiteral("1", token.INT, 0)),
		"EntityRegexpIdxFile":          reflect.ValueOf(constant.MakeFromLiteral("4", token.INT, 0)),
		"EntityRegexpIdxMatch":         reflect.ValueOf(constant.MakeFromLiteral("0", token.INT, 0)),
		"EntityRegexpIdxName":          reflect.ValueOf(constant.MakeFromLiteral("2", token.INT, 0)),
		"EntityRegexpIdxSourceID":      reflect.ValueOf(constant.MakeFromLiteral("3", token.INT, 0)),
		"EntitySourceIDBits":           reflect.ValueOf(constant.MakeFromLiteral("8", token.INT, 0)),
		"EntityTableGrowthRate":        reflect.ValueOf(constant.MakeFromLiteral("8", token.INT, 0)),
		"GetLinked":                    reflect.ValueOf(ecs.GetLinked),
		"GetNamed":                     reflect.ValueOf(ecs.GetNamed),
		"GetSourceFile":                reflect.ValueOf(ecs.GetSourceFile),
		"LinkedCID":                    reflect.ValueOf(&ecs.LinkedCID).Elem(),
		"MaxEntities":                  reflect.ValueOf(constant.MakeFromLiteral("16777215", token.INT, 0)),
		"NamedCID":                     reflect.ValueOf(&ecs.NamedCID).Elem(),
		"NewUniverse":                  reflect.ValueOf(ecs.NewUniverse),
		"ParseComponentIDs":            reflect.ValueOf(ecs.ParseComponentIDs),
		"ParseEntitiesFromMap":         reflect.ValueOf(ecs.ParseEntitiesFromMap),
		"ParseEntity":                  reflect.ValueOf(ecs.ParseEntity),
		"ParseEntityHumanOrCanonical":  reflect.ValueOf(ecs.ParseEntityHumanOrCanonical),
		"ParseEntitySlice":             reflect.ValueOf(ecs.ParseEntitySlice),
		"ParseEntityTable":             reflect.ValueOf(ecs.ParseEntityTable),
		"SerializeComponentIDs":        reflect.ValueOf(ecs.SerializeComponentIDs),
		"SourceFileCID":                reflect.ValueOf(&ecs.SourceFileCID).Elem(),
		"Types":                        reflect.ValueOf(ecs.Types),

		// type definitions
		"Attachable":       reflect.ValueOf((*ecs.Attachable)(nil)),
		"AttachableColumn": reflect.ValueOf((*ecs.AttachableColumn)(nil)),
		"Attached":         reflect.ValueOf((*ecs.Attached)(nil)),
		"BaseController":   reflect.ValueOf((*ecs.BaseController)(nil)),
		"ComponentFlags":   reflect.ValueOf((*ecs.ComponentFlags)(nil)),
		"ComponentID":      reflect.ValueOf((*ecs.ComponentID)(nil)),
		"ComponentTable":   reflect.ValueOf((*ecs.ComponentTable)(nil)),
		"Controller":       reflect.ValueOf((*ecs.Controller)(nil)),
		"ControllerMethod": reflect.ValueOf((*ecs.ControllerMethod)(nil)),
		"Entity":           reflect.ValueOf((*ecs.Entity)(nil)),
		"EntitySourceID":   reflect.ValueOf((*ecs.EntitySourceID)(nil)),
		"EntityTable":      reflect.ValueOf((*ecs.EntityTable)(nil)),
		"Linked":           reflect.ValueOf((*ecs.Linked)(nil)),
		"LinkedController": reflect.ValueOf((*ecs.LinkedController)(nil)),
		"Named":            reflect.ValueOf((*ecs.Named)(nil)),
		"Serializable":     reflect.ValueOf((*ecs.Serializable)(nil)),
		"SourceFile":       reflect.ValueOf((*ecs.SourceFile)(nil)),
		"SubSerializable":  reflect.ValueOf((*ecs.SubSerializable)(nil)),
		"Universe":         reflect.ValueOf((*ecs.Universe)(nil)),

		// interface wrapper definitions
		"_Attachable":       reflect.ValueOf((*_tlyakhov_gofoom_ecs_Attachable)(nil)),
		"_AttachableColumn": reflect.ValueOf((*_tlyakhov_gofoom_ecs_AttachableColumn)(nil)),
		"_Controller":       reflect.ValueOf((*_tlyakhov_gofoom_ecs_Controller)(nil)),
		"_Serializable":     reflect.ValueOf((*_tlyakhov_gofoom_ecs_Serializable)(nil)),
		"_SubSerializable":  reflect.ValueOf((*_tlyakhov_gofoom_ecs_SubSerializable)(nil)),
	}
}

// _tlyakhov_gofoom_ecs_Attachable is an interface wrapper for Attachable type
type _tlyakhov_gofoom_ecs_Attachable struct {
	IValue           interface{}
	WBase            func() *ecs.Attached
	WConstruct       func(data map[string]any)
	WGetUniverse     func() *ecs.Universe
	WIsActive        func() bool
	WMultiAttachable func() bool
	WOnAttach        func(u *ecs.Universe)
	WOnDelete        func()
	WOnDetach        func(a0 ecs.Entity)
	WSerialize       func() map[string]any
	WString          func() string
}

func (W _tlyakhov_gofoom_ecs_Attachable) Base() *ecs.Attached {
	return W.WBase()
}
func (W _tlyakhov_gofoom_ecs_Attachable) Construct(data map[string]any) {
	W.WConstruct(data)
}
func (W _tlyakhov_gofoom_ecs_Attachable) GetUniverse() *ecs.Universe {
	return W.WGetUniverse()
}
func (W _tlyakhov_gofoom_ecs_Attachable) IsActive() bool {
	return W.WIsActive()
}
func (W _tlyakhov_gofoom_ecs_Attachable) MultiAttachable() bool {
	return W.WMultiAttachable()
}
func (W _tlyakhov_gofoom_ecs_Attachable) OnAttach(u *ecs.Universe) {
	W.WOnAttach(u)
}
func (W _tlyakhov_gofoom_ecs_Attachable) OnDelete() {
	W.WOnDelete()
}
func (W _tlyakhov_gofoom_ecs_Attachable) OnDetach(a0 ecs.Entity) {
	W.WOnDetach(a0)
}
func (W _tlyakhov_gofoom_ecs_Attachable) Serialize() map[string]any {
	return W.WSerialize()
}
func (W _tlyakhov_gofoom_ecs_Attachable) String() string {
	if W.WString == nil {
		return ""
	}
	return W.WString()
}

// _tlyakhov_gofoom_ecs_AttachableColumn is an interface wrapper for AttachableColumn type
type _tlyakhov_gofoom_ecs_AttachableColumn struct {
	IValue      interface{}
	WAdd        func(c *ecs.Attachable)
	WAttachable func(index int) ecs.Attachable
	WCap        func() int
	WDetach     func(index int)
	WFrom       func(source ecs.AttachableColumn, ecs *ecs.Universe)
	WID         func() ecs.ComponentID
	WLen        func() int
	WNew        func() ecs.Attachable
	WReplace    func(c *ecs.Attachable, index int)
	WString     func() string
	WType       func() reflect.Type
}

func (W _tlyakhov_gofoom_ecs_AttachableColumn) Add(c *ecs.Attachable) {
	W.WAdd(c)
}
func (W _tlyakhov_gofoom_ecs_AttachableColumn) Attachable(index int) ecs.Attachable {
	return W.WAttachable(index)
}
func (W _tlyakhov_gofoom_ecs_AttachableColumn) Cap() int {
	return W.WCap()
}
func (W _tlyakhov_gofoom_ecs_AttachableColumn) Detach(index int) {
	W.WDetach(index)
}
func (W _tlyakhov_gofoom_ecs_AttachableColumn) From(source ecs.AttachableColumn, ecs *ecs.Universe) {
	W.WFrom(source, ecs)
}
func (W _tlyakhov_gofoom_ecs_AttachableColumn) ID() ecs.ComponentID {
	return W.WID()
}
func (W _tlyakhov_gofoom_ecs_AttachableColumn) Len() int {
	return W.WLen()
}
func (W _tlyakhov_gofoom_ecs_AttachableColumn) New() ecs.Attachable {
	return W.WNew()
}
func (W _tlyakhov_gofoom_ecs_AttachableColumn) Replace(c *ecs.Attachable, index int) {
	W.WReplace(c, index)
}
func (W _tlyakhov_gofoom_ecs_AttachableColumn) String() string {
	if W.WString == nil {
		return ""
	}
	return W.WString()
}
func (W _tlyakhov_gofoom_ecs_AttachableColumn) Type() reflect.Type {
	return W.WType()
}

// _tlyakhov_gofoom_ecs_Controller is an interface wrapper for Controller type
type _tlyakhov_gofoom_ecs_Controller struct {
	IValue               interface{}
	WAlways              func()
	WComponentID         func() ecs.ComponentID
	WEditorPausedMethods func() ecs.ControllerMethod
	WMethods             func() ecs.ControllerMethod
	WRecalculate         func()
	WTarget              func(a0 ecs.Attachable, a1 ecs.Entity) bool
}

func (W _tlyakhov_gofoom_ecs_Controller) Always() {
	W.WAlways()
}
func (W _tlyakhov_gofoom_ecs_Controller) ComponentID() ecs.ComponentID {
	return W.WComponentID()
}
func (W _tlyakhov_gofoom_ecs_Controller) EditorPausedMethods() ecs.ControllerMethod {
	return W.WEditorPausedMethods()
}
func (W _tlyakhov_gofoom_ecs_Controller) Methods() ecs.ControllerMethod {
	return W.WMethods()
}
func (W _tlyakhov_gofoom_ecs_Controller) Recalculate() {
	W.WRecalculate()
}
func (W _tlyakhov_gofoom_ecs_Controller) Target(a0 ecs.Attachable, a1 ecs.Entity) bool {
	return W.WTarget(a0, a1)
}

// _tlyakhov_gofoom_ecs_Serializable is an interface wrapper for Serializable type
type _tlyakhov_gofoom_ecs_Serializable struct {
	IValue       interface{}
	WConstruct   func(data map[string]any)
	WGetUniverse func() *ecs.Universe
	WOnAttach    func(u *ecs.Universe)
	WSerialize   func() map[string]any
}

func (W _tlyakhov_gofoom_ecs_Serializable) Construct(data map[string]any) {
	W.WConstruct(data)
}
func (W _tlyakhov_gofoom_ecs_Serializable) GetUniverse() *ecs.Universe {
	return W.WGetUniverse()
}
func (W _tlyakhov_gofoom_ecs_Serializable) OnAttach(u *ecs.Universe) {
	W.WOnAttach(u)
}
func (W _tlyakhov_gofoom_ecs_Serializable) Serialize() map[string]any {
	return W.WSerialize()
}

// _tlyakhov_gofoom_ecs_SubSerializable is an interface wrapper for SubSerializable type
type _tlyakhov_gofoom_ecs_SubSerializable struct {
	IValue     interface{}
	WConstruct func(ecs *ecs.Universe, data map[string]any)
	WSerialize func() map[string]any
}

func (W _tlyakhov_gofoom_ecs_SubSerializable) Construct(ecs *ecs.Universe, data map[string]any) {
	W.WConstruct(ecs, data)
}
func (W _tlyakhov_gofoom_ecs_SubSerializable) Serialize() map[string]any {
	return W.WSerialize()
}
