// Code generated by 'yaegi extract tlyakhov/gofoom/components/inventory'. DO NOT EDIT.

//go:build go1.25
// +build go1.25

package scripting_symbols

import (
	"reflect"
	"tlyakhov/gofoom/components/inventory"
)

func init() {
	Symbols["tlyakhov/gofoom/components/inventory/inventory"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"CarrierCID":               reflect.ValueOf(&inventory.CarrierCID).Elem(),
		"GetCarrier":               reflect.ValueOf(inventory.GetCarrier),
		"GetItem":                  reflect.ValueOf(inventory.GetItem),
		"GetSlot":                  reflect.ValueOf(inventory.GetSlot),
		"GetWeapon":                reflect.ValueOf(inventory.GetWeapon),
		"GetWeaponClass":           reflect.ValueOf(inventory.GetWeaponClass),
		"GetWeaponClassInstant":    reflect.ValueOf(inventory.GetWeaponClassInstant),
		"GetWeaponClassProjectile": reflect.ValueOf(inventory.GetWeaponClassProjectile),
		"ItemAutoPlayerTargetable": reflect.ValueOf(inventory.ItemAutoPlayerTargetable),
		"ItemAutoProximity":        reflect.ValueOf(inventory.ItemAutoProximity),
		"ItemBounce":               reflect.ValueOf(inventory.ItemBounce),
		"ItemCID":                  reflect.ValueOf(&inventory.ItemCID).Elem(),
		"ItemFlagsString":          reflect.ValueOf(inventory.ItemFlagsString),
		"ItemFlagsStrings":         reflect.ValueOf(inventory.ItemFlagsStrings),
		"ItemFlagsValues":          reflect.ValueOf(inventory.ItemFlagsValues),
		"SlotCID":                  reflect.ValueOf(&inventory.SlotCID).Elem(),
		"WeaponCID":                reflect.ValueOf(&inventory.WeaponCID).Elem(),
		"WeaponClassCID":           reflect.ValueOf(&inventory.WeaponClassCID).Elem(),
		"WeaponClassInstantCID":    reflect.ValueOf(&inventory.WeaponClassInstantCID).Elem(),
		"WeaponClassProjectileCID": reflect.ValueOf(&inventory.WeaponClassProjectileCID).Elem(),
		"WeaponCooling":            reflect.ValueOf(inventory.WeaponCooling),
		"WeaponFire":               reflect.ValueOf(inventory.WeaponFire),
		"WeaponFiring":             reflect.ValueOf(inventory.WeaponFiring),
		"WeaponHeld":               reflect.ValueOf(inventory.WeaponHeld),
		"WeaponHolstered":          reflect.ValueOf(inventory.WeaponHolstered),
		"WeaponHolstering":         reflect.ValueOf(inventory.WeaponHolstering),
		"WeaponIdle":               reflect.ValueOf(inventory.WeaponIdle),
		"WeaponIntentString":       reflect.ValueOf(inventory.WeaponIntentString),
		"WeaponIntentStrings":      reflect.ValueOf(inventory.WeaponIntentStrings),
		"WeaponIntentValues":       reflect.ValueOf(inventory.WeaponIntentValues),
		"WeaponReloading":          reflect.ValueOf(inventory.WeaponReloading),
		"WeaponStateCount":         reflect.ValueOf(inventory.WeaponStateCount),
		"WeaponStateString":        reflect.ValueOf(inventory.WeaponStateString),
		"WeaponStateStrings":       reflect.ValueOf(inventory.WeaponStateStrings),
		"WeaponStateValues":        reflect.ValueOf(inventory.WeaponStateValues),
		"WeaponUnholstering":       reflect.ValueOf(inventory.WeaponUnholstering),

		// type definitions
		"Carrier":               reflect.ValueOf((*inventory.Carrier)(nil)),
		"Item":                  reflect.ValueOf((*inventory.Item)(nil)),
		"ItemFlags":             reflect.ValueOf((*inventory.ItemFlags)(nil)),
		"Slot":                  reflect.ValueOf((*inventory.Slot)(nil)),
		"Weapon":                reflect.ValueOf((*inventory.Weapon)(nil)),
		"WeaponClass":           reflect.ValueOf((*inventory.WeaponClass)(nil)),
		"WeaponClassInstant":    reflect.ValueOf((*inventory.WeaponClassInstant)(nil)),
		"WeaponClassProjectile": reflect.ValueOf((*inventory.WeaponClassProjectile)(nil)),
		"WeaponIntent":          reflect.ValueOf((*inventory.WeaponIntent)(nil)),
		"WeaponMark":            reflect.ValueOf((*inventory.WeaponMark)(nil)),
		"WeaponState":           reflect.ValueOf((*inventory.WeaponState)(nil)),
		"WeaponStateParams":     reflect.ValueOf((*inventory.WeaponStateParams)(nil)),
	}
}
