// Code generated by 'yaegi extract tlyakhov/gofoom/components/core'. DO NOT EDIT.

//go:build go1.21
// +build go1.21

package scripting_symbols

import (
	"reflect"
	"tlyakhov/gofoom/components/core"
)

func init() {
	Symbols["tlyakhov/gofoom/components/core/core"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"BodyComponentIndex":          reflect.ValueOf(&core.BodyComponentIndex).Elem(),
		"BodyFromDb":                  reflect.ValueOf(core.BodyFromDb),
		"BodyShadowAABB":              reflect.ValueOf(core.BodyShadowAABB),
		"BodyShadowNone":              reflect.ValueOf(core.BodyShadowNone),
		"BodyShadowSphere":            reflect.ValueOf(core.BodyShadowSphere),
		"BodyShadowString":            reflect.ValueOf(core.BodyShadowString),
		"BodyShadowStrings":           reflect.ValueOf(core.BodyShadowStrings),
		"BodyShadowValues":            reflect.ValueOf(core.BodyShadowValues),
		"Bounce":                      reflect.ValueOf(core.Bounce),
		"Callback":                    reflect.ValueOf(core.Callback),
		"CollisionResponseString":     reflect.ValueOf(core.CollisionResponseString),
		"CollisionResponseStrings":    reflect.ValueOf(core.CollisionResponseStrings),
		"CollisionResponseValues":     reflect.ValueOf(core.CollisionResponseValues),
		"LightComponentIndex":         reflect.ValueOf(&core.LightComponentIndex).Elem(),
		"LightFromDb":                 reflect.ValueOf(core.LightFromDb),
		"Remove":                      reflect.ValueOf(core.Remove),
		"ScriptStyleBoolExpr":         reflect.ValueOf(core.ScriptStyleBoolExpr),
		"ScriptStyleRaw":              reflect.ValueOf(core.ScriptStyleRaw),
		"ScriptStyleStatement":        reflect.ValueOf(core.ScriptStyleStatement),
		"ScriptStyleString":           reflect.ValueOf(core.ScriptStyleString),
		"ScriptStyleStrings":          reflect.ValueOf(core.ScriptStyleStrings),
		"ScriptStyleValues":           reflect.ValueOf(core.ScriptStyleValues),
		"SectorComponentIndex":        reflect.ValueOf(&core.SectorComponentIndex).Elem(),
		"SectorFromDb":                reflect.ValueOf(core.SectorFromDb),
		"Slide":                       reflect.ValueOf(core.Slide),
		"SpawnComponentIndex":         reflect.ValueOf(&core.SpawnComponentIndex).Elem(),
		"SpawnFromDb":                 reflect.ValueOf(core.SpawnFromDb),
		"StaticSegmentComponentIndex": reflect.ValueOf(&core.StaticSegmentComponentIndex).Elem(),
		"StaticSegmentFromDb":         reflect.ValueOf(core.StaticSegmentFromDb),
		"Stop":                        reflect.ValueOf(core.Stop),

		// type definitions
		"Body":              reflect.ValueOf((*core.Body)(nil)),
		"BodyShadow":        reflect.ValueOf((*core.BodyShadow)(nil)),
		"CollisionResponse": reflect.ValueOf((*core.CollisionResponse)(nil)),
		"Light":             reflect.ValueOf((*core.Light)(nil)),
		"Script":            reflect.ValueOf((*core.Script)(nil)),
		"ScriptStyle":       reflect.ValueOf((*core.ScriptStyle)(nil)),
		"Sector":            reflect.ValueOf((*core.Sector)(nil)),
		"SectorSegment":     reflect.ValueOf((*core.SectorSegment)(nil)),
		"Segment":           reflect.ValueOf((*core.Segment)(nil)),
		"Spawn":             reflect.ValueOf((*core.Spawn)(nil)),
		"StaticSegment":     reflect.ValueOf((*core.StaticSegment)(nil)),
	}
}
