// Code generated by 'yaegi extract tlyakhov/gofoom/components/core'. DO NOT EDIT.

//go:build go1.22
// +build go1.22

package scripting_symbols

import (
	"reflect"
	"tlyakhov/gofoom/components/core"
)

func init() {
	Symbols["tlyakhov/gofoom/components/core/core"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"BodyComponentIndex":             reflect.ValueOf(&core.BodyComponentIndex).Elem(),
		"BodyFromDb":                     reflect.ValueOf(core.BodyFromDb),
		"BodyShadowAABB":                 reflect.ValueOf(core.BodyShadowAABB),
		"BodyShadowNone":                 reflect.ValueOf(core.BodyShadowNone),
		"BodyShadowSphere":               reflect.ValueOf(core.BodyShadowSphere),
		"BodyShadowString":               reflect.ValueOf(core.BodyShadowString),
		"BodyShadowStrings":              reflect.ValueOf(core.BodyShadowStrings),
		"BodyShadowValues":               reflect.ValueOf(core.BodyShadowValues),
		"Bounce":                         reflect.ValueOf(core.Bounce),
		"Callback":                       reflect.ValueOf(core.Callback),
		"CollisionResponseString":        reflect.ValueOf(core.CollisionResponseString),
		"CollisionResponseStrings":       reflect.ValueOf(core.CollisionResponseStrings),
		"CollisionResponseValues":        reflect.ValueOf(core.CollisionResponseValues),
		"InternalSegmentComponentIndex":  reflect.ValueOf(&core.InternalSegmentComponentIndex).Elem(),
		"InternalSegmentFromDb":          reflect.ValueOf(core.InternalSegmentFromDb),
		"LightComponentIndex":            reflect.ValueOf(&core.LightComponentIndex).Elem(),
		"LightFromDb":                    reflect.ValueOf(core.LightFromDb),
		"NewSelection":                   reflect.ValueOf(core.NewSelection),
		"NewSelectionClone":              reflect.ValueOf(core.NewSelectionClone),
		"Remove":                         reflect.ValueOf(core.Remove),
		"ScriptStyleBoolExpr":            reflect.ValueOf(core.ScriptStyleBoolExpr),
		"ScriptStyleRaw":                 reflect.ValueOf(core.ScriptStyleRaw),
		"ScriptStyleStatement":           reflect.ValueOf(core.ScriptStyleStatement),
		"ScriptStyleString":              reflect.ValueOf(core.ScriptStyleString),
		"ScriptStyleStrings":             reflect.ValueOf(core.ScriptStyleStrings),
		"ScriptStyleValues":              reflect.ValueOf(core.ScriptStyleValues),
		"SectorComponentIndex":           reflect.ValueOf(&core.SectorComponentIndex).Elem(),
		"SectorFromDb":                   reflect.ValueOf(core.SectorFromDb),
		"SelectableBody":                 reflect.ValueOf(core.SelectableBody),
		"SelectableCeiling":              reflect.ValueOf(core.SelectableCeiling),
		"SelectableEntity":               reflect.ValueOf(core.SelectableEntity),
		"SelectableFloor":                reflect.ValueOf(core.SelectableFloor),
		"SelectableFromBody":             reflect.ValueOf(core.SelectableFromBody),
		"SelectableFromCeil":             reflect.ValueOf(core.SelectableFromCeil),
		"SelectableFromEntity":           reflect.ValueOf(core.SelectableFromEntity),
		"SelectableFromFloor":            reflect.ValueOf(core.SelectableFromFloor),
		"SelectableFromInternalSegment":  reflect.ValueOf(core.SelectableFromInternalSegment),
		"SelectableFromInternalSegmentA": reflect.ValueOf(core.SelectableFromInternalSegmentA),
		"SelectableFromInternalSegmentB": reflect.ValueOf(core.SelectableFromInternalSegmentB),
		"SelectableFromSector":           reflect.ValueOf(core.SelectableFromSector),
		"SelectableFromSegment":          reflect.ValueOf(core.SelectableFromSegment),
		"SelectableFromWall":             reflect.ValueOf(core.SelectableFromWall),
		"SelectableHi":                   reflect.ValueOf(core.SelectableHi),
		"SelectableInternalSegment":      reflect.ValueOf(core.SelectableInternalSegment),
		"SelectableInternalSegmentA":     reflect.ValueOf(core.SelectableInternalSegmentA),
		"SelectableInternalSegmentB":     reflect.ValueOf(core.SelectableInternalSegmentB),
		"SelectableLow":                  reflect.ValueOf(core.SelectableLow),
		"SelectableMid":                  reflect.ValueOf(core.SelectableMid),
		"SelectableSector":               reflect.ValueOf(core.SelectableSector),
		"SelectableSectorSegment":        reflect.ValueOf(core.SelectableSectorSegment),
		"SelectableTypeString":           reflect.ValueOf(core.SelectableTypeString),
		"SelectableTypeStrings":          reflect.ValueOf(core.SelectableTypeStrings),
		"SelectableTypeValues":           reflect.ValueOf(core.SelectableTypeValues),
		"Slide":                          reflect.ValueOf(core.Slide),
		"SpawnComponentIndex":            reflect.ValueOf(&core.SpawnComponentIndex).Elem(),
		"SpawnFromDb":                    reflect.ValueOf(core.SpawnFromDb),
		"Stop":                           reflect.ValueOf(core.Stop),

		// type definitions
		"Body":              reflect.ValueOf((*core.Body)(nil)),
		"BodyShadow":        reflect.ValueOf((*core.BodyShadow)(nil)),
		"CollisionResponse": reflect.ValueOf((*core.CollisionResponse)(nil)),
		"InternalSegment":   reflect.ValueOf((*core.InternalSegment)(nil)),
		"Light":             reflect.ValueOf((*core.Light)(nil)),
		"Script":            reflect.ValueOf((*core.Script)(nil)),
		"ScriptStyle":       reflect.ValueOf((*core.ScriptStyle)(nil)),
		"Sector":            reflect.ValueOf((*core.Sector)(nil)),
		"SectorSegment":     reflect.ValueOf((*core.SectorSegment)(nil)),
		"Segment":           reflect.ValueOf((*core.Segment)(nil)),
		"Selectable":        reflect.ValueOf((*core.Selectable)(nil)),
		"SelectableType":    reflect.ValueOf((*core.SelectableType)(nil)),
		"Selection":         reflect.ValueOf((*core.Selection)(nil)),
		"Spawn":             reflect.ValueOf((*core.Spawn)(nil)),
	}
}
