// Code generated by 'yaegi extract tlyakhov/gofoom/components/materials'. DO NOT EDIT.

//go:build go1.22
// +build go1.22

package scripting_symbols

import (
	"reflect"
	"tlyakhov/gofoom/components/materials"
)

func init() {
	Symbols["tlyakhov/gofoom/components/materials/materials"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"GetImage":               reflect.ValueOf(materials.GetImage),
		"GetLit":                 reflect.ValueOf(materials.GetLit),
		"GetShader":              reflect.ValueOf(materials.GetShader),
		"GetSolid":               reflect.ValueOf(materials.GetSolid),
		"GetSprite":              reflect.ValueOf(materials.GetSprite),
		"GetText":                reflect.ValueOf(materials.GetText),
		"ImageCID":               reflect.ValueOf(&materials.ImageCID).Elem(),
		"LitCID":                 reflect.ValueOf(&materials.LitCID).Elem(),
		"ShaderCID":              reflect.ValueOf(&materials.ShaderCID).Elem(),
		"ShaderFlagsString":      reflect.ValueOf(materials.ShaderFlagsString),
		"ShaderFlagsStrings":     reflect.ValueOf(materials.ShaderFlagsStrings),
		"ShaderFlagsValues":      reflect.ValueOf(materials.ShaderFlagsValues),
		"ShaderLiquid":           reflect.ValueOf(materials.ShaderLiquid),
		"ShaderSky":              reflect.ValueOf(materials.ShaderSky),
		"ShaderStaticBackground": reflect.ValueOf(materials.ShaderStaticBackground),
		"ShaderTiled":            reflect.ValueOf(materials.ShaderTiled),
		"SolidCID":               reflect.ValueOf(&materials.SolidCID).Elem(),
		"SpriteCID":              reflect.ValueOf(&materials.SpriteCID).Elem(),
		"TextCID":                reflect.ValueOf(&materials.TextCID).Elem(),

		// type definitions
		"Image":       reflect.ValueOf((*materials.Image)(nil)),
		"Lit":         reflect.ValueOf((*materials.Lit)(nil)),
		"Shader":      reflect.ValueOf((*materials.Shader)(nil)),
		"ShaderFlags": reflect.ValueOf((*materials.ShaderFlags)(nil)),
		"ShaderStage": reflect.ValueOf((*materials.ShaderStage)(nil)),
		"Solid":       reflect.ValueOf((*materials.Solid)(nil)),
		"Sprite":      reflect.ValueOf((*materials.Sprite)(nil)),
		"Surface":     reflect.ValueOf((*materials.Surface)(nil)),
		"Text":        reflect.ValueOf((*materials.Text)(nil)),
	}
}
