// Code generated by 'yaegi extract tlyakhov/gofoom/dynamic'. DO NOT EDIT.

//go:build go1.22
// +build go1.22

package scripting_symbols

import (
	"reflect"
	"tlyakhov/gofoom/dynamic"
)

func init() {
	Symbols["tlyakhov/gofoom/dynamic/dynamic"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"AnimationCoordinatesAbsolute": reflect.ValueOf(dynamic.AnimationCoordinatesAbsolute),
		"AnimationCoordinatesRelative": reflect.ValueOf(dynamic.AnimationCoordinatesRelative),
		"AnimationCoordinatesString":   reflect.ValueOf(dynamic.AnimationCoordinatesString),
		"AnimationCoordinatesStrings":  reflect.ValueOf(dynamic.AnimationCoordinatesStrings),
		"AnimationCoordinatesValues":   reflect.ValueOf(dynamic.AnimationCoordinatesValues),
		"AnimationLifetimeBounce":      reflect.ValueOf(dynamic.AnimationLifetimeBounce),
		"AnimationLifetimeBounceOnce":  reflect.ValueOf(dynamic.AnimationLifetimeBounceOnce),
		"AnimationLifetimeLoop":        reflect.ValueOf(dynamic.AnimationLifetimeLoop),
		"AnimationLifetimeOnce":        reflect.ValueOf(dynamic.AnimationLifetimeOnce),
		"AnimationLifetimeString":      reflect.ValueOf(dynamic.AnimationLifetimeString),
		"AnimationLifetimeStrings":     reflect.ValueOf(dynamic.AnimationLifetimeStrings),
		"AnimationLifetimeValues":      reflect.ValueOf(dynamic.AnimationLifetimeValues),
		"DynamicNow":                   reflect.ValueOf(dynamic.DynamicNow),
		"DynamicPrev":                  reflect.ValueOf(dynamic.DynamicPrev),
		"DynamicRender":                reflect.ValueOf(dynamic.DynamicRender),
		"DynamicSpawn":                 reflect.ValueOf(dynamic.DynamicSpawn),
		"DynamicStageString":           reflect.ValueOf(dynamic.DynamicStageString),
		"DynamicStageStrings":          reflect.ValueOf(dynamic.DynamicStageStrings),
		"DynamicStageValues":           reflect.ValueOf(dynamic.DynamicStageValues),
		"EaseIn2":                      reflect.ValueOf(dynamic.EaseIn2),
		"EaseIn3":                      reflect.ValueOf(dynamic.EaseIn3),
		"EaseIn4":                      reflect.ValueOf(dynamic.EaseIn4),
		"EaseInOut2":                   reflect.ValueOf(dynamic.EaseInOut2),
		"EaseInOut3":                   reflect.ValueOf(dynamic.EaseInOut3),
		"EaseInOut4":                   reflect.ValueOf(dynamic.EaseInOut4),
		"EaseOut2":                     reflect.ValueOf(dynamic.EaseOut2),
		"EaseOut3":                     reflect.ValueOf(dynamic.EaseOut3),
		"EaseOut4":                     reflect.ValueOf(dynamic.EaseOut4),
		"ElasticIn":                    reflect.ValueOf(dynamic.ElasticIn),
		"ElasticInOut":                 reflect.ValueOf(dynamic.ElasticInOut),
		"ElasticOut":                   reflect.ValueOf(dynamic.ElasticOut),
		"Lerp":                         reflect.ValueOf(dynamic.Lerp),
		"NewSimulation":                reflect.ValueOf(dynamic.NewSimulation),
		"Random":                       reflect.ValueOf(dynamic.Random),
		"Spike":                        reflect.ValueOf(dynamic.Spike),
		"Spike2":                       reflect.ValueOf(dynamic.Spike2),
		"Spike3":                       reflect.ValueOf(dynamic.Spike3),
		"Spike4":                       reflect.ValueOf(dynamic.Spike4),
		"TweenAngles":                  reflect.ValueOf(dynamic.TweenAngles),
		"TweeningFuncNames":            reflect.ValueOf(&dynamic.TweeningFuncNames).Elem(),
		"TweeningFuncs":                reflect.ValueOf(&dynamic.TweeningFuncs).Elem(),

		// type definitions
		"Animated":             reflect.ValueOf((*dynamic.Animated)(nil)),
		"AnimationCoordinates": reflect.ValueOf((*dynamic.AnimationCoordinates)(nil)),
		"AnimationLifetime":    reflect.ValueOf((*dynamic.AnimationLifetime)(nil)),
		"Dynamic":              reflect.ValueOf((*dynamic.Dynamic)(nil)),
		"DynamicStage":         reflect.ValueOf((*dynamic.DynamicStage)(nil)),
		"Simulation":           reflect.ValueOf((*dynamic.Simulation)(nil)),
		"TweeningFunc":         reflect.ValueOf((*dynamic.TweeningFunc)(nil)),

		// interface wrapper definitions
		"_Animated": reflect.ValueOf((*_tlyakhov_gofoom_dynamic_Animated)(nil)),
		"_Dynamic":  reflect.ValueOf((*_tlyakhov_gofoom_dynamic_Dynamic)(nil)),
	}
}

// _tlyakhov_gofoom_dynamic_Animated is an interface wrapper for Animated type
type _tlyakhov_gofoom_dynamic_Animated struct {
	IValue   interface{}
	WAnimate func()
	WReset   func()
}

func (W _tlyakhov_gofoom_dynamic_Animated) Animate() {
	W.WAnimate()
}
func (W _tlyakhov_gofoom_dynamic_Animated) Reset() {
	W.WReset()
}

// _tlyakhov_gofoom_dynamic_Dynamic is an interface wrapper for Dynamic type
type _tlyakhov_gofoom_dynamic_Dynamic struct {
	IValue        interface{}
	WAttach       func(sim *dynamic.Simulation)
	WDetach       func(sim *dynamic.Simulation)
	WGetAnimation func() dynamic.Animated
	WNewFrame     func()
	WRecalculate  func()
	WResetToSpawn func()
	WUpdate       func(a0 float64)
}

func (W _tlyakhov_gofoom_dynamic_Dynamic) Attach(sim *dynamic.Simulation) {
	W.WAttach(sim)
}
func (W _tlyakhov_gofoom_dynamic_Dynamic) Detach(sim *dynamic.Simulation) {
	W.WDetach(sim)
}
func (W _tlyakhov_gofoom_dynamic_Dynamic) GetAnimation() dynamic.Animated {
	return W.WGetAnimation()
}
func (W _tlyakhov_gofoom_dynamic_Dynamic) NewFrame() {
	W.WNewFrame()
}
func (W _tlyakhov_gofoom_dynamic_Dynamic) Recalculate() {
	W.WRecalculate()
}
func (W _tlyakhov_gofoom_dynamic_Dynamic) ResetToSpawn() {
	W.WResetToSpawn()
}
func (W _tlyakhov_gofoom_dynamic_Dynamic) Update(a0 float64) {
	W.WUpdate(a0)
}
