// Code generated by 'yaegi extract tlyakhov/gofoom/archetypes'. DO NOT EDIT.

//go:build go1.22
// +build go1.22

package scripting_symbols

import (
	"reflect"
	"tlyakhov/gofoom/archetypes"
)

func init() {
	Symbols["tlyakhov/gofoom/archetypes/archetypes"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"AttachableIsMaterial": reflect.ValueOf(archetypes.AttachableIsMaterial),
		"CreateBasic":          reflect.ValueOf(archetypes.CreateBasic),
		"CreateBasicMaterial":  reflect.ValueOf(archetypes.CreateBasicMaterial),
		"CreateLightBody":      reflect.ValueOf(archetypes.CreateLightBody),
		"CreatePlayerBody":     reflect.ValueOf(archetypes.CreatePlayerBody),
		"CreateSector":         reflect.ValueOf(archetypes.CreateSector),
		"EntityMapIsMaterial":  reflect.ValueOf(archetypes.EntityMapIsMaterial),
		"EntityRefIsMaterial":  reflect.ValueOf(archetypes.EntityRefIsMaterial),
		"IsLightBody":          reflect.ValueOf(archetypes.IsLightBody),
		"IsPlayerBody":         reflect.ValueOf(archetypes.IsPlayerBody),
	}
}
