// Code generated by 'yaegi extract tlyakhov/gofoom/containers'. DO NOT EDIT.

//go:build go1.22
// +build go1.22

package scripting_symbols

import (
	"reflect"
	"tlyakhov/gofoom/containers"
)

func init() {
	Symbols["tlyakhov/gofoom/containers/containers"] = map[string]reflect.Value{
		// type definitions
		"SyncQueue":       reflect.ValueOf((*containers.SyncQueue)(nil)),
		"SyncUniqueQueue": reflect.ValueOf((*containers.SyncUniqueQueue)(nil)),
	}
}
