// Code generated by 'yaegi extract tlyakhov/gofoom/archetypes'. DO NOT EDIT.

//go:build go1.22
// +build go1.22

package scripting_symbols

import (
	"reflect"
	"tlyakhov/gofoom/archetypes"
)

func init() {
	Symbols["tlyakhov/gofoom/archetypes/archetypes"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"ComponentTableIsMaterial": reflect.ValueOf(archetypes.ComponentTableIsMaterial),
		"CreateBasicMaterial":      reflect.ValueOf(archetypes.CreateBasicMaterial),
		"CreateFont":               reflect.ValueOf(archetypes.CreateFont),
		"CreateLightBody":          reflect.ValueOf(archetypes.CreateLightBody),
		"EntityIsMaterial":         reflect.ValueOf(archetypes.EntityIsMaterial),
	}
}
