// Code generated by 'yaegi extract tlyakhov/gofoom/concepts'. DO NOT EDIT.

//go:build go1.22
// +build go1.22

package scripting_symbols

import (
	"go/constant"
	"go/token"
	"reflect"
	"tlyakhov/gofoom/concepts"
)

func init() {
	Symbols["tlyakhov/gofoom/concepts/concepts"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"ByteClamp":            reflect.ValueOf(concepts.ByteClamp),
		"ColorToInt32PreMul":   reflect.ValueOf(concepts.ColorToInt32PreMul),
		"Deg2rad":              reflect.ValueOf(concepts.Deg2rad),
		"ExecutionDuration":    reflect.ValueOf(concepts.ExecutionDuration),
		"ExecutionTrack":       reflect.ValueOf(concepts.ExecutionTrack),
		"HSPtoRGB":             reflect.ValueOf(concepts.HSPtoRGB),
		"Hash64to32":           reflect.ValueOf(concepts.Hash64to32),
		"IdentityMatrix2":      reflect.ValueOf(&concepts.IdentityMatrix2).Elem(),
		"Int32ToNRGBA":         reflect.ValueOf(concepts.Int32ToNRGBA),
		"Int32ToRGBA":          reflect.ValueOf(concepts.Int32ToRGBA),
		"Int32ToVector3":       reflect.ValueOf(concepts.Int32ToVector3),
		"Int32ToVector4PreMul": reflect.ValueOf(concepts.Int32ToVector4PreMul),
		"Intersect":            reflect.ValueOf(concepts.Intersect),
		"IntersectLineAABB":    reflect.ValueOf(concepts.IntersectLineAABB),
		"IntersectLineSphere":  reflect.ValueOf(concepts.IntersectLineSphere),
		"IntersectPointAABB":   reflect.ValueOf(concepts.IntersectPointAABB),
		"IntersectSegments":    reflect.ValueOf(concepts.IntersectSegments),
		"IntersectSegmentsRaw": reflect.ValueOf(concepts.IntersectSegmentsRaw),
		"MatBasis1X":           reflect.ValueOf(concepts.MatBasis1X),
		"MatBasis1Y":           reflect.ValueOf(concepts.MatBasis1Y),
		"MatBasis2X":           reflect.ValueOf(concepts.MatBasis2X),
		"MatBasis2Y":           reflect.ValueOf(concepts.MatBasis2Y),
		"MatTransX":            reflect.ValueOf(concepts.MatTransX),
		"MatTransY":            reflect.ValueOf(concepts.MatTransY),
		"NRGBAToInt32":         reflect.ValueOf(concepts.NRGBAToInt32),
		"NearestPow2":          reflect.ValueOf(concepts.NearestPow2),
		"NormalizeAngle":       reflect.ValueOf(concepts.NormalizeAngle),
		"ParseHexColor":        reflect.ValueOf(concepts.ParseHexColor),
		"ParseMatrix2":         reflect.ValueOf(concepts.ParseMatrix2),
		"ParseVector2":         reflect.ValueOf(concepts.ParseVector2),
		"ParseVector3":         reflect.ValueOf(concepts.ParseVector3),
		"ParseVector4":         reflect.ValueOf(concepts.ParseVector4),
		"Pb":                   reflect.ValueOf(constant.MakeFromLiteral("0.1140000000000000000014094628242311557642096886411309242248535156", token.FLOAT, 0)),
		"Pg":                   reflect.ValueOf(constant.MakeFromLiteral("0.5870000000000000000221177243187042904537520371377468109130859375", token.FLOAT, 0)),
		"Pr":                   reflect.ValueOf(constant.MakeFromLiteral("0.2989999999999999999900253400131333592071314342319965362548828125", token.FLOAT, 0)),
		"RGBAToInt32":          reflect.ValueOf(concepts.RGBAToInt32),
		"RGBtoHSP":             reflect.ValueOf(concepts.RGBtoHSP),
		"Rad2deg":              reflect.ValueOf(concepts.Rad2deg),
		"RngDecide":            reflect.ValueOf(concepts.RngDecide),
		"RngXorShift64":        reflect.ValueOf(concepts.RngXorShift64),
		"StackTrace":           reflect.ValueOf(concepts.StackTrace),
		"TruncateString":       reflect.ValueOf(concepts.TruncateString),
		"V2":                   reflect.ValueOf(concepts.V2),
		"V3":                   reflect.ValueOf(concepts.V3),
		"V4":                   reflect.ValueOf(concepts.V4),
		"Vector2AABBIntersect": reflect.ValueOf(concepts.Vector2AABBIntersect),

		// type definitions
		"Matrix2": reflect.ValueOf((*concepts.Matrix2)(nil)),
		"Vector2": reflect.ValueOf((*concepts.Vector2)(nil)),
		"Vector3": reflect.ValueOf((*concepts.Vector3)(nil)),
		"Vector4": reflect.ValueOf((*concepts.Vector4)(nil)),
	}
}
