// Code generated by 'yaegi extract tlyakhov/gofoom/components/behaviors'. DO NOT EDIT.

//go:build go1.21
// +build go1.21

package scripting_symbols

import (
	"reflect"
	"tlyakhov/gofoom/components/behaviors"
)

func init() {
	Symbols["tlyakhov/gofoom/components/behaviors/behaviors"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"AliveComponentIndex":     reflect.ValueOf(&behaviors.AliveComponentIndex).Elem(),
		"AliveFromDb":             reflect.ValueOf(behaviors.AliveFromDb),
		"AnimatedComponentIndex":  reflect.ValueOf(&behaviors.AnimatedComponentIndex).Elem(),
		"AnimatedFromDb":          reflect.ValueOf(behaviors.AnimatedFromDb),
		"PlayerComponentIndex":    reflect.ValueOf(&behaviors.PlayerComponentIndex).Elem(),
		"PlayerFromDb":            reflect.ValueOf(behaviors.PlayerFromDb),
		"ProximityComponentIndex": reflect.ValueOf(&behaviors.ProximityComponentIndex).Elem(),
		"ProximityFromDb":         reflect.ValueOf(behaviors.ProximityFromDb),
		"WanderComponentIndex":    reflect.ValueOf(&behaviors.WanderComponentIndex).Elem(),
		"WanderFromDb":            reflect.ValueOf(behaviors.WanderFromDb),

		// type definitions
		"Alive":     reflect.ValueOf((*behaviors.Alive)(nil)),
		"Animated":  reflect.ValueOf((*behaviors.Animated)(nil)),
		"Damage":    reflect.ValueOf((*behaviors.Damage)(nil)),
		"Player":    reflect.ValueOf((*behaviors.Player)(nil)),
		"Proximity": reflect.ValueOf((*behaviors.Proximity)(nil)),
		"Wander":    reflect.ValueOf((*behaviors.Wander)(nil)),
	}
}
