// Code generated by 'yaegi extract tlyakhov/gofoom/containers'. DO NOT EDIT.

//go:build go1.25
// +build go1.25

package scripting_symbols

import (
	"reflect"
)

func init() {
	Symbols["tlyakhov/gofoom/containers/containers"] = map[string]reflect.Value{}
}
