// Code generated by 'yaegi extract tlyakhov/gofoom/controllers'. DO NOT EDIT.

//go:build go1.25
// +build go1.25

package scripting_symbols

import (
	"reflect"
	"tlyakhov/gofoom/controllers"
)

func init() {
	Symbols["tlyakhov/gofoom/controllers/controllers"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"AutoPortal":                reflect.ValueOf(controllers.AutoPortal),
		"BodySectorScript":          reflect.ValueOf(controllers.BodySectorScript),
		"Cast":                      reflect.ValueOf(controllers.Cast),
		"CloneEntity":               reflect.ValueOf(controllers.CloneEntity),
		"CreateFont":                reflect.ValueOf(controllers.CreateFont),
		"CreateLightBody":           reflect.ValueOf(controllers.CreateLightBody),
		"CreateSpawn":               reflect.ValueOf(controllers.CreateSpawn),
		"CreateTestDirt":            reflect.ValueOf(controllers.CreateTestDirt),
		"CreateTestGrass":           reflect.ValueOf(controllers.CreateTestGrass),
		"CreateTestHeightmapSector": reflect.ValueOf(controllers.CreateTestHeightmapSector),
		"CreateTestSector":          reflect.ValueOf(controllers.CreateTestSector),
		"CreateTestSky":             reflect.ValueOf(controllers.CreateTestSky),
		"CreateTestTree":            reflect.ValueOf(controllers.CreateTestTree),
		"CreateTestWorld":           reflect.ValueOf(controllers.CreateTestWorld),
		"CreateTestWorld2":          reflect.ValueOf(controllers.CreateTestWorld2),
		"CreateTestWorld3":          reflect.ValueOf(controllers.CreateTestWorld3),
		"DefaultMaterial":           reflect.ValueOf(controllers.DefaultMaterial),
		"DeleteSpawned":             reflect.ValueOf(controllers.DeleteSpawned),
		"EntitiesByClass":           reflect.ValueOf(controllers.EntitiesByClass),
		"EventIdBack":               reflect.ValueOf(&controllers.EventIdBack).Elem(),
		"EventIdDown":               reflect.ValueOf(&controllers.EventIdDown).Elem(),
		"EventIdForward":            reflect.ValueOf(&controllers.EventIdForward).Elem(),
		"EventIdLeft":               reflect.ValueOf(&controllers.EventIdLeft).Elem(),
		"EventIdPitch":              reflect.ValueOf(&controllers.EventIdPitch).Elem(),
		"EventIdPrimaryAction":      reflect.ValueOf(&controllers.EventIdPrimaryAction).Elem(),
		"EventIdRight":              reflect.ValueOf(&controllers.EventIdRight).Elem(),
		"EventIdSecondaryAction":    reflect.ValueOf(&controllers.EventIdSecondaryAction).Elem(),
		"EventIdTurnLeft":           reflect.ValueOf(&controllers.EventIdTurnLeft).Elem(),
		"EventIdTurnRight":          reflect.ValueOf(&controllers.EventIdTurnRight).Elem(),
		"EventIdUp":                 reflect.ValueOf(&controllers.EventIdUp).Elem(),
		"EventIdYaw":                reflect.ValueOf(&controllers.EventIdYaw).Elem(),
		"MovePlayer":                reflect.ValueOf(controllers.MovePlayer),
		"MovePlayerForce":           reflect.ValueOf(controllers.MovePlayerForce),
		"MovePlayerNoClip":          reflect.ValueOf(controllers.MovePlayerNoClip),
		"NpcMove":                   reflect.ValueOf(controllers.NpcMove),
		"PickUpInventoryItem":       reflect.ValueOf(controllers.PickUpInventoryItem),
		"ResetAllSpawnables":        reflect.ValueOf(controllers.ResetAllSpawnables),
		"RespawnAll":                reflect.ValueOf(controllers.RespawnAll),
		"Spawn":                     reflect.ValueOf(controllers.Spawn),

		// type definitions
		"ActionController":           reflect.ValueOf((*controllers.ActionController)(nil)),
		"AliveController":            reflect.ValueOf((*controllers.AliveController)(nil)),
		"BodyController":             reflect.ValueOf((*controllers.BodyController)(nil)),
		"DoorController":             reflect.ValueOf((*controllers.DoorController)(nil)),
		"EntityAxisEventParams":      reflect.ValueOf((*controllers.EntityAxisEventParams)(nil)),
		"EntityEventParams":          reflect.ValueOf((*controllers.EntityEventParams)(nil)),
		"EphemeralController":        reflect.ValueOf((*controllers.EphemeralController)(nil)),
		"ImageController":            reflect.ValueOf((*controllers.ImageController)(nil)),
		"InternalSegmentController":  reflect.ValueOf((*controllers.InternalSegmentController)(nil)),
		"InventoryCarrierController": reflect.ValueOf((*controllers.InventoryCarrierController)(nil)),
		"InventoryItemController":    reflect.ValueOf((*controllers.InventoryItemController)(nil)),
		"InventorySlotController":    reflect.ValueOf((*controllers.InventorySlotController)(nil)),
		"MarkMakerController":        reflect.ValueOf((*controllers.MarkMakerController)(nil)),
		"MobileController":           reflect.ValueOf((*controllers.MobileController)(nil)),
		"NpcController":              reflect.ValueOf((*controllers.NpcController)(nil)),
		"ParticleController":         reflect.ValueOf((*controllers.ParticleController)(nil)),
		"PlayerController":           reflect.ValueOf((*controllers.PlayerController)(nil)),
		"PlayerTargetableController": reflect.ValueOf((*controllers.PlayerTargetableController)(nil)),
		"ProximityController":        reflect.ValueOf((*controllers.ProximityController)(nil)),
		"PursuerController":          reflect.ValueOf((*controllers.PursuerController)(nil)),
		"ScriptedController":         reflect.ValueOf((*controllers.ScriptedController)(nil)),
		"SectorController":           reflect.ValueOf((*controllers.SectorController)(nil)),
		"SectorSplitter":             reflect.ValueOf((*controllers.SectorSplitter)(nil)),
		"SoundController":            reflect.ValueOf((*controllers.SoundController)(nil)),
		"SoundEventController":       reflect.ValueOf((*controllers.SoundEventController)(nil)),
		"UnderwaterController":       reflect.ValueOf((*controllers.UnderwaterController)(nil)),
		"WanderController":           reflect.ValueOf((*controllers.WanderController)(nil)),
		"WeaponController":           reflect.ValueOf((*controllers.WeaponController)(nil)),
	}
}
