// Code generated by 'yaegi extract tlyakhov/gofoom/concepts'. DO NOT EDIT.

//go:build go1.25
// +build go1.25

package scripting_symbols

import (
	"go/constant"
	"go/token"
	"reflect"
	"tlyakhov/gofoom/concepts"
)

func init() {
	Symbols["tlyakhov/gofoom/concepts/concepts"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"AsmInt32ToVector4":       reflect.ValueOf(concepts.AsmInt32ToVector4),
		"AsmInt32ToVector4PreMul": reflect.ValueOf(concepts.AsmInt32ToVector4PreMul),
		"AsmVector4Mul4Self":      reflect.ValueOf(concepts.AsmVector4Mul4Self),
		"BlendColors":             reflect.ValueOf(concepts.BlendColors),
		"BlendDissolve":           reflect.ValueOf(concepts.BlendDissolve),
		"BlendFrameBuffer":        reflect.ValueOf(concepts.BlendFrameBuffer),
		"BlendFuncString":         reflect.ValueOf(concepts.BlendFuncString),
		"BlendFuncStrings":        reflect.ValueOf(concepts.BlendFuncStrings),
		"BlendFuncValues":         reflect.ValueOf(concepts.BlendFuncValues),
		"BlendMultiply":           reflect.ValueOf(concepts.BlendMultiply),
		"BlendNormal":             reflect.ValueOf(concepts.BlendNormal),
		"BlendOverlay":            reflect.ValueOf(concepts.BlendOverlay),
		"BlendScreen":             reflect.ValueOf(concepts.BlendScreen),
		"BlendingFuncs":           reflect.ValueOf(&concepts.BlendingFuncs).Elem(),
		"ByteClamp":               reflect.ValueOf(concepts.ByteClamp),
		"ColorToInt32PreMul":      reflect.ValueOf(concepts.ColorToInt32PreMul),
		"Deg2rad":                 reflect.ValueOf(concepts.Deg2rad),
		"ExecutionDuration":       reflect.ValueOf(concepts.ExecutionDuration),
		"ExecutionTrack":          reflect.ValueOf(concepts.ExecutionTrack),
		"HSPtoRGB":                reflect.ValueOf(concepts.HSPtoRGB),
		"Hash64to32":              reflect.ValueOf(concepts.Hash64to32),
		"IdentityMatrix2":         reflect.ValueOf(&concepts.IdentityMatrix2).Elem(),
		"Int32ToNRGBA":            reflect.ValueOf(concepts.Int32ToNRGBA),
		"Int32ToRGBA":             reflect.ValueOf(concepts.Int32ToRGBA),
		"Int32ToVector3":          reflect.ValueOf(concepts.Int32ToVector3),
		"Int32ToVector4PreMul":    reflect.ValueOf(concepts.Int32ToVector4PreMul),
		"Intersect":               reflect.ValueOf(concepts.Intersect),
		"IntersectLineAABB":       reflect.ValueOf(concepts.IntersectLineAABB),
		"IntersectLineSphere":     reflect.ValueOf(concepts.IntersectLineSphere),
		"IntersectPointAABB":      reflect.ValueOf(concepts.IntersectPointAABB),
		"IntersectSegments":       reflect.ValueOf(concepts.IntersectSegments),
		"IntersectSegmentsRaw":    reflect.ValueOf(concepts.IntersectSegmentsRaw),
		"MatBasis1X":              reflect.ValueOf(concepts.MatBasis1X),
		"MatBasis1Y":              reflect.ValueOf(concepts.MatBasis1Y),
		"MatBasis2X":              reflect.ValueOf(concepts.MatBasis2X),
		"MatBasis2Y":              reflect.ValueOf(concepts.MatBasis2Y),
		"MatTransX":               reflect.ValueOf(concepts.MatTransX),
		"MatTransY":               reflect.ValueOf(concepts.MatTransY),
		"MillisToNanos":           reflect.ValueOf(concepts.MillisToNanos),
		"MinimizeAngleDistance":   reflect.ValueOf(concepts.MinimizeAngleDistance),
		"NRGBAToInt32":            reflect.ValueOf(concepts.NRGBAToInt32),
		"NanosToMillis":           reflect.ValueOf(concepts.NanosToMillis),
		"NearestPow2":             reflect.ValueOf(concepts.NearestPow2),
		"NormalizeAngle":          reflect.ValueOf(concepts.NormalizeAngle),
		"ParseHexColor":           reflect.ValueOf(concepts.ParseHexColor),
		"ParseMatrix2":            reflect.ValueOf(concepts.ParseMatrix2),
		"ParseVector2":            reflect.ValueOf(concepts.ParseVector2),
		"ParseVector3":            reflect.ValueOf(concepts.ParseVector3),
		"ParseVector4":            reflect.ValueOf(concepts.ParseVector4),
		"Pb":                      reflect.ValueOf(constant.MakeFromLiteral("0.1140000000000000000014094628242311557642096886411309242248535156", token.FLOAT, 0)),
		"Pg":                      reflect.ValueOf(constant.MakeFromLiteral("0.5870000000000000000221177243187042904537520371377468109130859375", token.FLOAT, 0)),
		"Pr":                      reflect.ValueOf(constant.MakeFromLiteral("0.2989999999999999999900253400131333592071314342319965362548828125", token.FLOAT, 0)),
		"RGBAToInt32":             reflect.ValueOf(concepts.RGBAToInt32),
		"RGBtoHSP":                reflect.ValueOf(concepts.RGBtoHSP),
		"Rad2deg":                 reflect.ValueOf(concepts.Rad2deg),
		"RngDecide":               reflect.ValueOf(concepts.RngDecide),
		"RngXorShift64":           reflect.ValueOf(concepts.RngXorShift64),
		"StackTrace":              reflect.ValueOf(concepts.StackTrace),
		"TruncateString":          reflect.ValueOf(concepts.TruncateString),
		"Vector2AABBIntersect":    reflect.ValueOf(concepts.Vector2AABBIntersect),

		// type definitions
		"BlendType": reflect.ValueOf((*concepts.BlendType)(nil)),
		"Matrix2":   reflect.ValueOf((*concepts.Matrix2)(nil)),
		"Ray":       reflect.ValueOf((*concepts.Ray)(nil)),
		"Vector2":   reflect.ValueOf((*concepts.Vector2)(nil)),
		"Vector3":   reflect.ValueOf((*concepts.Vector3)(nil)),
		"Vector4":   reflect.ValueOf((*concepts.Vector4)(nil)),

		// interface wrapper definitions
		"_Flaggable": reflect.ValueOf((*_tlyakhov_gofoom_concepts_Flaggable)(nil)),
	}
}

// _tlyakhov_gofoom_concepts_Flaggable is an interface wrapper for Flaggable type
type _tlyakhov_gofoom_concepts_Flaggable struct {
	IValue  interface{}
	WString func() string
}

func (W _tlyakhov_gofoom_concepts_Flaggable) String() string {
	if W.WString == nil {
		return ""
	}
	return W.WString()
}
