// Code generated by 'yaegi extract tlyakhov/gofoom/components/inventory'. DO NOT EDIT.

//go:build go1.22
// +build go1.22

package scripting_symbols

import (
	"reflect"
	"tlyakhov/gofoom/components/inventory"
)

func init() {
	Symbols["tlyakhov/gofoom/components/inventory/inventory"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"CarrierCID":               reflect.ValueOf(&inventory.CarrierCID).Elem(),
		"GetCarrier":               reflect.ValueOf(inventory.GetCarrier),
		"GetySlot":         reflect.ValueOf(inventory.GetSlot),
		"GetItem":                  reflect.ValueOf(inventory.GetItem),
		"GetWeapon":                reflect.ValueOf(inventory.GetWeapon),
		"GetWeaponClass":           reflect.ValueOf(inventory.GetWeaponClass),
		"SlotCID":         reflect.ValueOf(&inventory.SlotCID).Elem(),
		"ItemAutoPlayerTargetable": reflect.ValueOf(inventory.ItemAutoPlayerTargetable),
		"ItemAutoProximity":        reflect.ValueOf(inventory.ItemAutoProximity),
		"ItemBounce":               reflect.ValueOf(inventory.ItemBounce),
		"ItemCID":                  reflect.ValueOf(&inventory.ItemCID).Elem(),
		"ItemFlagsString":          reflect.ValueOf(inventory.ItemFlagsString),
		"ItemFlagsStrings":         reflect.ValueOf(inventory.ItemFlagsStrings),
		"ItemFlagsValues":          reflect.ValueOf(inventory.ItemFlagsValues),
		"WeaponCID":                reflect.ValueOf(&inventory.WeaponCID).Elem(),
		"WeaponClassCID":           reflect.ValueOf(&inventory.WeaponClassCID).Elem(),

		// type definitions
		"Carrier":       reflect.ValueOf((*inventory.Carrier)(nil)),
		"Slot": reflect.ValueOf((*inventory.Slot)(nil)),
		"Item":          reflect.ValueOf((*inventory.Item)(nil)),
		"ItemFlags":     reflect.ValueOf((*inventory.ItemFlags)(nil)),
		"Weapon":        reflect.ValueOf((*inventory.Weapon)(nil)),
		"WeaponClass":   reflect.ValueOf((*inventory.WeaponClass)(nil)),
		"WeaponMark":    reflect.ValueOf((*inventory.WeaponMark)(nil)),
	}
}
 