// Code generated by 'yaegi extract tlyakhov/gofoom/components/behaviors'. DO NOT EDIT.

//go:build go1.21
// +build go1.21

package scripting_symbols

import (
	"reflect"
	"tlyakhov/gofoom/components/behaviors"
)

func init() {
	Symbols["tlyakhov/gofoom/components/behaviors/behaviors"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"AliveComponentIndex":         reflect.ValueOf(&behaviors.AliveComponentIndex).Elem(),
		"AliveFromDb":                 reflect.ValueOf(behaviors.AliveFromDb),
		"DoorIntentClosed":            reflect.ValueOf(behaviors.DoorIntentClosed),
		"DoorIntentOpen":              reflect.ValueOf(behaviors.DoorIntentOpen),
		"DoorIntentReset":             reflect.ValueOf(behaviors.DoorIntentReset),
		"DoorIntentString":            reflect.ValueOf(behaviors.DoorIntentString),
		"DoorIntentStrings":           reflect.ValueOf(behaviors.DoorIntentStrings),
		"DoorIntentValues":            reflect.ValueOf(behaviors.DoorIntentValues),
		"DoorStateClosed":             reflect.ValueOf(behaviors.DoorStateClosed),
		"DoorStateClosing":            reflect.ValueOf(behaviors.DoorStateClosing),
		"DoorStateOpen":               reflect.ValueOf(behaviors.DoorStateOpen),
		"DoorStateOpening":            reflect.ValueOf(behaviors.DoorStateOpening),
		"DoorStateString":             reflect.ValueOf(behaviors.DoorStateString),
		"DoorStateStrings":            reflect.ValueOf(behaviors.DoorStateStrings),
		"DoorStateValues":             reflect.ValueOf(behaviors.DoorStateValues),
		"InventoryItemComponentIndex": reflect.ValueOf(&behaviors.InventoryItemComponentIndex).Elem(),
		"InventoryItemFromDb":         reflect.ValueOf(behaviors.InventoryItemFromDb),
		"PlayerComponentIndex":        reflect.ValueOf(&behaviors.PlayerComponentIndex).Elem(),
		"PlayerFromDb":                reflect.ValueOf(behaviors.PlayerFromDb),
		"ProximityComponentIndex":     reflect.ValueOf(&behaviors.ProximityComponentIndex).Elem(),
		"ProximityFromDb":             reflect.ValueOf(behaviors.ProximityFromDb),
		"UnderwaterComponentIndex":    reflect.ValueOf(&behaviors.UnderwaterComponentIndex).Elem(),
		"UnderwaterFromDb":            reflect.ValueOf(behaviors.UnderwaterFromDb),
		"VerticalDoorComponentIndex":  reflect.ValueOf(&behaviors.VerticalDoorComponentIndex).Elem(),
		"VerticalDoorFromDb":          reflect.ValueOf(behaviors.VerticalDoorFromDb),
		"WanderComponentIndex":        reflect.ValueOf(&behaviors.WanderComponentIndex).Elem(),
		"WanderFromDb":                reflect.ValueOf(behaviors.WanderFromDb),

		// type definitions
		"Alive":         reflect.ValueOf((*behaviors.Alive)(nil)),
		"Damage":        reflect.ValueOf((*behaviors.Damage)(nil)),
		"DoorIntent":    reflect.ValueOf((*behaviors.DoorIntent)(nil)),
		"DoorState":     reflect.ValueOf((*behaviors.DoorState)(nil)),
		"InventoryItem": reflect.ValueOf((*behaviors.InventoryItem)(nil)),
		"Player":        reflect.ValueOf((*behaviors.Player)(nil)),
		"Proximity":     reflect.ValueOf((*behaviors.Proximity)(nil)),
		"Underwater":    reflect.ValueOf((*behaviors.Underwater)(nil)),
		"VerticalDoor":  reflect.ValueOf((*behaviors.VerticalDoor)(nil)),
		"Wander":        reflect.ValueOf((*behaviors.Wander)(nil)),
	}
}
