// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package resources

import (
	_ "embed"
	"fyne.io/fyne/v2"
)

//go:embed icon-add-entity.svg
var resourceIconAddEntitySvgData []byte
var resourceIconAddEntitySvg = &fyne.StaticResource{
	StaticName:    "icon-add-entity.svg",
	StaticContent: resourceIconAddEntitySvgData,
}

//go:embed icon-add-sector.svg
var resourceIconAddSectorSvgData []byte
var resourceIconAddSectorSvg = &fyne.StaticResource{
	StaticName:    "icon-add-sector.svg",
	StaticContent: resourceIconAddSectorSvgData,
}

//go:embed icon-split-sector.svg
var resourceIconSplitSectorSvgData []byte
var resourceIconSplitSectorSvg = &fyne.StaticResource{
	StaticName:    "icon-split-sector.svg",
	StaticContent: resourceIconSplitSectorSvgData,
}

//go:embed icon-split-segment.svg
var resourceIconSplitSegmentSvgData []byte
var resourceIconSplitSegmentSvg = &fyne.StaticResource{
	StaticName:    "icon-split-segment.svg",
	StaticContent: resourceIconSplitSegmentSvgData,
}
