// Code generated by "enumer -type=BodyShadow -json"; DO NOT EDIT.

package core

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _BodyShadowName = "BodyShadowNoneBodyShadowImageBodyShadowSphereBodyShadowAABB"

var _BodyShadowIndex = [...]uint8{0, 14, 29, 45, 59}

const _BodyShadowLowerName = "bodyshadownonebodyshadowimagebodyshadowspherebodyshadowaabb"

func (i BodyShadow) String() string {
	if i < 0 || i >= BodyShadow(len(_BodyShadowIndex)-1) {
		return fmt.Sprintf("BodyShadow(%d)", i)
	}
	return _BodyShadowName[_BodyShadowIndex[i]:_BodyShadowIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _BodyShadowNoOp() {
	var x [1]struct{}
	_ = x[BodyShadowNone-(0)]
	_ = x[BodyShadowImage-(1)]
	_ = x[BodyShadowSphere-(2)]
	_ = x[BodyShadowAABB-(3)]
}

var _BodyShadowValues = []BodyShadow{BodyShadowNone, BodyShadowImage, BodyShadowSphere, BodyShadowAABB}

var _BodyShadowNameToValueMap = map[string]BodyShadow{
	_BodyShadowName[0:14]:       BodyShadowNone,
	_BodyShadowLowerName[0:14]:  BodyShadowNone,
	_BodyShadowName[14:29]:      BodyShadowImage,
	_BodyShadowLowerName[14:29]: BodyShadowImage,
	_BodyShadowName[29:45]:      BodyShadowSphere,
	_BodyShadowLowerName[29:45]: BodyShadowSphere,
	_BodyShadowName[45:59]:      BodyShadowAABB,
	_BodyShadowLowerName[45:59]: BodyShadowAABB,
}

var _BodyShadowNames = []string{
	_BodyShadowName[0:14],
	_BodyShadowName[14:29],
	_BodyShadowName[29:45],
	_BodyShadowName[45:59],
}

// BodyShadowString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func BodyShadowString(s string) (BodyShadow, error) {
	if val, ok := _BodyShadowNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _BodyShadowNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to BodyShadow values", s)
}

// BodyShadowValues returns all values of the enum
func BodyShadowValues() []BodyShadow {
	return _BodyShadowValues
}

// BodyShadowStrings returns a slice of all String values of the enum
func BodyShadowStrings() []string {
	strs := make([]string, len(_BodyShadowNames))
	copy(strs, _BodyShadowNames)
	return strs
}

// IsABodyShadow returns "true" if the value is listed in the enum definition. "false" otherwise
func (i BodyShadow) IsABodyShadow() bool {
	for _, v := range _BodyShadowValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for BodyShadow
func (i BodyShadow) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for BodyShadow
func (i *BodyShadow) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("BodyShadow should be a string, got %s", data)
	}

	var err error
	*i, err = BodyShadowString(s)
	return err
}
