// Code generated by "enumer -type=CollisionResponse -json"; DO NOT EDIT.

package core

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _CollisionResponseName = "CollideNoneCollideSeparateCollideBounceCollideStopCollideRemove"

var _CollisionResponseIndex = [...]uint8{0, 11, 26, 39, 50, 63}

const _CollisionResponseLowerName = "collidenonecollideseparatecollidebouncecollidestopcollideremove"

func (i CollisionResponse) String() string {
	if i < 0 || i >= CollisionResponse(len(_CollisionResponseIndex)-1) {
		return fmt.Sprintf("CollisionResponse(%d)", i)
	}
	return _CollisionResponseName[_CollisionResponseIndex[i]:_CollisionResponseIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _CollisionResponseNoOp() {
	var x [1]struct{}
	_ = x[CollideNone-(0)]
	_ = x[CollideSeparate-(1)]
	_ = x[CollideBounce-(2)]
	_ = x[CollideStop-(3)]
	_ = x[CollideRemove-(4)]
}

var _CollisionResponseValues = []CollisionResponse{CollideNone, CollideSeparate, CollideBounce, CollideStop, CollideRemove}

var _CollisionResponseNameToValueMap = map[string]CollisionResponse{
	_CollisionResponseName[0:11]:       CollideNone,
	_CollisionResponseLowerName[0:11]:  CollideNone,
	_CollisionResponseName[11:26]:      CollideSeparate,
	_CollisionResponseLowerName[11:26]: CollideSeparate,
	_CollisionResponseName[26:39]:      CollideBounce,
	_CollisionResponseLowerName[26:39]: CollideBounce,
	_CollisionResponseName[39:50]:      CollideStop,
	_CollisionResponseLowerName[39:50]: CollideStop,
	_CollisionResponseName[50:63]:      CollideRemove,
	_CollisionResponseLowerName[50:63]: CollideRemove,
}

var _CollisionResponseNames = []string{
	_CollisionResponseName[0:11],
	_CollisionResponseName[11:26],
	_CollisionResponseName[26:39],
	_CollisionResponseName[39:50],
	_CollisionResponseName[50:63],
}

// CollisionResponseString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func CollisionResponseString(s string) (CollisionResponse, error) {
	if val, ok := _CollisionResponseNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _CollisionResponseNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to CollisionResponse values", s)
}

// CollisionResponseValues returns all values of the enum
func CollisionResponseValues() []CollisionResponse {
	return _CollisionResponseValues
}

// CollisionResponseStrings returns a slice of all String values of the enum
func CollisionResponseStrings() []string {
	strs := make([]string, len(_CollisionResponseNames))
	copy(strs, _CollisionResponseNames)
	return strs
}

// IsACollisionResponse returns "true" if the value is listed in the enum definition. "false" otherwise
func (i CollisionResponse) IsACollisionResponse() bool {
	for _, v := range _CollisionResponseValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for CollisionResponse
func (i CollisionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for CollisionResponse
func (i *CollisionResponse) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("CollisionResponse should be a string, got %s", data)
	}

	var err error
	*i, err = CollisionResponseString(s)
	return err
}
