// Code generated by "enumer -type=CollisionResponse -json"; DO NOT EDIT.

package core

import (
	"encoding/json"
	"fmt"
	"strings"
)

const (
	_CollisionResponseName_0      = "CollideNoneCollideDeactivate"
	_CollisionResponseLowerName_0 = "collidenonecollidedeactivate"
	_CollisionResponseName_1      = "CollideSeparate"
	_CollisionResponseLowerName_1 = "collideseparate"
	_CollisionResponseName_2      = "CollideBounce"
	_CollisionResponseLowerName_2 = "collidebounce"
	_CollisionResponseName_3      = "CollideStop"
	_CollisionResponseLowerName_3 = "collidestop"
	_CollisionResponseName_4      = "CollideRemove"
	_CollisionResponseLowerName_4 = "collideremove"
)

var (
	_CollisionResponseIndex_0 = [...]uint8{0, 11, 28}
	_CollisionResponseIndex_1 = [...]uint8{0, 15}
	_CollisionResponseIndex_2 = [...]uint8{0, 13}
	_CollisionResponseIndex_3 = [...]uint8{0, 11}
	_CollisionResponseIndex_4 = [...]uint8{0, 13}
)

func (i CollisionResponse) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _CollisionResponseName_0[_CollisionResponseIndex_0[i]:_CollisionResponseIndex_0[i+1]]
	case i == 4:
		return _CollisionResponseName_1
	case i == 8:
		return _CollisionResponseName_2
	case i == 16:
		return _CollisionResponseName_3
	case i == 32:
		return _CollisionResponseName_4
	default:
		return fmt.Sprintf("CollisionResponse(%d)", i)
	}
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _CollisionResponseNoOp() {
	var x [1]struct{}
	_ = x[CollideNone-(1)]
	_ = x[CollideDeactivate-(2)]
	_ = x[CollideSeparate-(4)]
	_ = x[CollideBounce-(8)]
	_ = x[CollideStop-(16)]
	_ = x[CollideRemove-(32)]
}

var _CollisionResponseValues = []CollisionResponse{CollideNone, CollideDeactivate, CollideSeparate, CollideBounce, CollideStop, CollideRemove}

var _CollisionResponseNameToValueMap = map[string]CollisionResponse{
	_CollisionResponseName_0[0:11]:       CollideNone,
	_CollisionResponseLowerName_0[0:11]:  CollideNone,
	_CollisionResponseName_0[11:28]:      CollideDeactivate,
	_CollisionResponseLowerName_0[11:28]: CollideDeactivate,
	_CollisionResponseName_1[0:15]:       CollideSeparate,
	_CollisionResponseLowerName_1[0:15]:  CollideSeparate,
	_CollisionResponseName_2[0:13]:       CollideBounce,
	_CollisionResponseLowerName_2[0:13]:  CollideBounce,
	_CollisionResponseName_3[0:11]:       CollideStop,
	_CollisionResponseLowerName_3[0:11]:  CollideStop,
	_CollisionResponseName_4[0:13]:       CollideRemove,
	_CollisionResponseLowerName_4[0:13]:  CollideRemove,
}

var _CollisionResponseNames = []string{
	_CollisionResponseName_0[0:11],
	_CollisionResponseName_0[11:28],
	_CollisionResponseName_1[0:15],
	_CollisionResponseName_2[0:13],
	_CollisionResponseName_3[0:11],
	_CollisionResponseName_4[0:13],
}

// CollisionResponseString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func CollisionResponseString(s string) (CollisionResponse, error) {
	if val, ok := _CollisionResponseNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _CollisionResponseNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to CollisionResponse values", s)
}

// CollisionResponseValues returns all values of the enum
func CollisionResponseValues() []CollisionResponse {
	return _CollisionResponseValues
}

// CollisionResponseStrings returns a slice of all String values of the enum
func CollisionResponseStrings() []string {
	strs := make([]string, len(_CollisionResponseNames))
	copy(strs, _CollisionResponseNames)
	return strs
}

// IsACollisionResponse returns "true" if the value is listed in the enum definition. "false" otherwise
func (i CollisionResponse) IsACollisionResponse() bool {
	for _, v := range _CollisionResponseValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for CollisionResponse
func (i CollisionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for CollisionResponse
func (i *CollisionResponse) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("CollisionResponse should be a string, got %s", data)
	}

	var err error
	*i, err = CollisionResponseString(s)
	return err
}
