// Code generated by "enumer -type=MaterialScale -json"; DO NOT EDIT.

package core

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _MaterialScaleName = "ScaleNoneScaleHeightScaleWidthScaleAll"

var _MaterialScaleIndex = [...]uint8{0, 9, 20, 30, 38}

const _MaterialScaleLowerName = "scalenonescaleheightscalewidthscaleall"

func (i MaterialScale) String() string {
	if i < 0 || i >= MaterialScale(len(_MaterialScaleIndex)-1) {
		return fmt.Sprintf("MaterialScale(%d)", i)
	}
	return _MaterialScaleName[_MaterialScaleIndex[i]:_MaterialScaleIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _MaterialScaleNoOp() {
	var x [1]struct{}
	_ = x[ScaleNone-(0)]
	_ = x[ScaleHeight-(1)]
	_ = x[ScaleWidth-(2)]
	_ = x[ScaleAll-(3)]
}

var _MaterialScaleValues = []MaterialScale{ScaleNone, ScaleHeight, ScaleWidth, ScaleAll}

var _MaterialScaleNameToValueMap = map[string]MaterialScale{
	_MaterialScaleName[0:9]:        ScaleNone,
	_MaterialScaleLowerName[0:9]:   ScaleNone,
	_MaterialScaleName[9:20]:       ScaleHeight,
	_MaterialScaleLowerName[9:20]:  ScaleHeight,
	_MaterialScaleName[20:30]:      ScaleWidth,
	_MaterialScaleLowerName[20:30]: ScaleWidth,
	_MaterialScaleName[30:38]:      ScaleAll,
	_MaterialScaleLowerName[30:38]: ScaleAll,
}

var _MaterialScaleNames = []string{
	_MaterialScaleName[0:9],
	_MaterialScaleName[9:20],
	_MaterialScaleName[20:30],
	_MaterialScaleName[30:38],
}

// MaterialScaleString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func MaterialScaleString(s string) (MaterialScale, error) {
	if val, ok := _MaterialScaleNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _MaterialScaleNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to MaterialScale values", s)
}

// MaterialScaleValues returns all values of the enum
func MaterialScaleValues() []MaterialScale {
	return _MaterialScaleValues
}

// MaterialScaleStrings returns a slice of all String values of the enum
func MaterialScaleStrings() []string {
	strs := make([]string, len(_MaterialScaleNames))
	copy(strs, _MaterialScaleNames)
	return strs
}

// IsAMaterialScale returns "true" if the value is listed in the enum definition. "false" otherwise
func (i MaterialScale) IsAMaterialScale() bool {
	for _, v := range _MaterialScaleValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for MaterialScale
func (i MaterialScale) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for MaterialScale
func (i *MaterialScale) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("MaterialScale should be a string, got %s", data)
	}

	var err error
	*i, err = MaterialScaleString(s)
	return err
}
