// Code generated by "enumer -type=ScriptStyle -json"; DO NOT EDIT.

package core

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _ScriptStyleName = "ScriptStyleRawScriptStyleBoolExprScriptStyleStatement"

var _ScriptStyleIndex = [...]uint8{0, 14, 33, 53}

const _ScriptStyleLowerName = "scriptstylerawscriptstyleboolexprscriptstylestatement"

func (i ScriptStyle) String() string {
	if i < 0 || i >= ScriptStyle(len(_ScriptStyleIndex)-1) {
		return fmt.Sprintf("ScriptStyle(%d)", i)
	}
	return _ScriptStyleName[_ScriptStyleIndex[i]:_ScriptStyleIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ScriptStyleNoOp() {
	var x [1]struct{}
	_ = x[ScriptStyleRaw-(0)]
	_ = x[ScriptStyleBoolExpr-(1)]
	_ = x[ScriptStyleStatement-(2)]
}

var _ScriptStyleValues = []ScriptStyle{ScriptStyleRaw, ScriptStyleBoolExpr, ScriptStyleStatement}

var _ScriptStyleNameToValueMap = map[string]ScriptStyle{
	_ScriptStyleName[0:14]:       ScriptStyleRaw,
	_ScriptStyleLowerName[0:14]:  ScriptStyleRaw,
	_ScriptStyleName[14:33]:      ScriptStyleBoolExpr,
	_ScriptStyleLowerName[14:33]: ScriptStyleBoolExpr,
	_ScriptStyleName[33:53]:      ScriptStyleStatement,
	_ScriptStyleLowerName[33:53]: ScriptStyleStatement,
}

var _ScriptStyleNames = []string{
	_ScriptStyleName[0:14],
	_ScriptStyleName[14:33],
	_ScriptStyleName[33:53],
}

// ScriptStyleString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ScriptStyleString(s string) (ScriptStyle, error) {
	if val, ok := _ScriptStyleNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ScriptStyleNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ScriptStyle values", s)
}

// ScriptStyleValues returns all values of the enum
func ScriptStyleValues() []ScriptStyle {
	return _ScriptStyleValues
}

// ScriptStyleStrings returns a slice of all String values of the enum
func ScriptStyleStrings() []string {
	strs := make([]string, len(_ScriptStyleNames))
	copy(strs, _ScriptStyleNames)
	return strs
}

// IsAScriptStyle returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ScriptStyle) IsAScriptStyle() bool {
	for _, v := range _ScriptStyleValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for ScriptStyle
func (i ScriptStyle) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for ScriptStyle
func (i *ScriptStyle) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("ScriptStyle should be a string, got %s", data)
	}

	var err error
	*i, err = ScriptStyleString(s)
	return err
}
