// Code generated by "enumer -type=SelectableType -json"; DO NOT EDIT.

package core

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _SelectableTypeName = "SelectableEntityRefSelectableSectorSelectableSectorSegmentSelectableCeilingSelectableFloorSelectableHiSelectableLowSelectableMidSelectableInternalSegmentSelectableInternalSegmentASelectableInternalSegmentBSelectableBody"

var _SelectableTypeIndex = [...]uint8{0, 19, 35, 58, 75, 90, 102, 115, 128, 153, 179, 205, 219}

const _SelectableTypeLowerName = "selectableentityrefselectablesectorselectablesectorsegmentselectableceilingselectablefloorselectablehiselectablelowselectablemidselectableinternalsegmentselectableinternalsegmentaselectableinternalsegmentbselectablebody"

func (i SelectableType) String() string {
	if i < 0 || i >= SelectableType(len(_SelectableTypeIndex)-1) {
		return fmt.Sprintf("SelectableType(%d)", i)
	}
	return _SelectableTypeName[_SelectableTypeIndex[i]:_SelectableTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _SelectableTypeNoOp() {
	var x [1]struct{}
	_ = x[SelectableEntityRef-(0)]
	_ = x[SelectableSector-(1)]
	_ = x[SelectableSectorSegment-(2)]
	_ = x[SelectableCeiling-(3)]
	_ = x[SelectableFloor-(4)]
	_ = x[SelectableHi-(5)]
	_ = x[SelectableLow-(6)]
	_ = x[SelectableMid-(7)]
	_ = x[SelectableInternalSegment-(8)]
	_ = x[SelectableInternalSegmentA-(9)]
	_ = x[SelectableInternalSegmentB-(10)]
	_ = x[SelectableBody-(11)]
}

var _SelectableTypeValues = []SelectableType{SelectableEntityRef, SelectableSector, SelectableSectorSegment, SelectableCeiling, SelectableFloor, SelectableHi, SelectableLow, SelectableMid, SelectableInternalSegment, SelectableInternalSegmentA, SelectableInternalSegmentB, SelectableBody}

var _SelectableTypeNameToValueMap = map[string]SelectableType{
	_SelectableTypeName[0:19]:         SelectableEntityRef,
	_SelectableTypeLowerName[0:19]:    SelectableEntityRef,
	_SelectableTypeName[19:35]:        SelectableSector,
	_SelectableTypeLowerName[19:35]:   SelectableSector,
	_SelectableTypeName[35:58]:        SelectableSectorSegment,
	_SelectableTypeLowerName[35:58]:   SelectableSectorSegment,
	_SelectableTypeName[58:75]:        SelectableCeiling,
	_SelectableTypeLowerName[58:75]:   SelectableCeiling,
	_SelectableTypeName[75:90]:        SelectableFloor,
	_SelectableTypeLowerName[75:90]:   SelectableFloor,
	_SelectableTypeName[90:102]:       SelectableHi,
	_SelectableTypeLowerName[90:102]:  SelectableHi,
	_SelectableTypeName[102:115]:      SelectableLow,
	_SelectableTypeLowerName[102:115]: SelectableLow,
	_SelectableTypeName[115:128]:      SelectableMid,
	_SelectableTypeLowerName[115:128]: SelectableMid,
	_SelectableTypeName[128:153]:      SelectableInternalSegment,
	_SelectableTypeLowerName[128:153]: SelectableInternalSegment,
	_SelectableTypeName[153:179]:      SelectableInternalSegmentA,
	_SelectableTypeLowerName[153:179]: SelectableInternalSegmentA,
	_SelectableTypeName[179:205]:      SelectableInternalSegmentB,
	_SelectableTypeLowerName[179:205]: SelectableInternalSegmentB,
	_SelectableTypeName[205:219]:      SelectableBody,
	_SelectableTypeLowerName[205:219]: SelectableBody,
}

var _SelectableTypeNames = []string{
	_SelectableTypeName[0:19],
	_SelectableTypeName[19:35],
	_SelectableTypeName[35:58],
	_SelectableTypeName[58:75],
	_SelectableTypeName[75:90],
	_SelectableTypeName[90:102],
	_SelectableTypeName[102:115],
	_SelectableTypeName[115:128],
	_SelectableTypeName[128:153],
	_SelectableTypeName[153:179],
	_SelectableTypeName[179:205],
	_SelectableTypeName[205:219],
}

// SelectableTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func SelectableTypeString(s string) (SelectableType, error) {
	if val, ok := _SelectableTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _SelectableTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to SelectableType values", s)
}

// SelectableTypeValues returns all values of the enum
func SelectableTypeValues() []SelectableType {
	return _SelectableTypeValues
}

// SelectableTypeStrings returns a slice of all String values of the enum
func SelectableTypeStrings() []string {
	strs := make([]string, len(_SelectableTypeNames))
	copy(strs, _SelectableTypeNames)
	return strs
}

// IsASelectableType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i SelectableType) IsASelectableType() bool {
	for _, v := range _SelectableTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for SelectableType
func (i SelectableType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for SelectableType
func (i *SelectableType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("SelectableType should be a string, got %s", data)
	}

	var err error
	*i, err = SelectableTypeString(s)
	return err
}
