// Code generated by "enumer -type=SelectableType -json"; DO NOT EDIT.

package core

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _SelectableTypeName = "SelectableEntitySelectableSectorSelectableSectorSegmentSelectableCeilingSelectableFloorSelectableHiSelectableLowSelectableMidSelectableInternalSegmentSelectableInternalSegmentASelectableInternalSegmentBSelectableBody"

var _SelectableTypeIndex = [...]uint8{0, 16, 32, 55, 72, 87, 99, 112, 125, 150, 176, 202, 216}

const _SelectableTypeLowerName = "selectableentityselectablesectorselectablesectorsegmentselectableceilingselectablefloorselectablehiselectablelowselectablemidselectableinternalsegmentselectableinternalsegmentaselectableinternalsegmentbselectablebody"

func (i SelectableType) String() string {
	if i < 0 || i >= SelectableType(len(_SelectableTypeIndex)-1) {
		return fmt.Sprintf("SelectableType(%d)", i)
	}
	return _SelectableTypeName[_SelectableTypeIndex[i]:_SelectableTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _SelectableTypeNoOp() {
	var x [1]struct{}
	_ = x[SelectableEntity-(0)]
	_ = x[SelectableSector-(1)]
	_ = x[SelectableSectorSegment-(2)]
	_ = x[SelectableCeiling-(3)]
	_ = x[SelectableFloor-(4)]
	_ = x[SelectableHi-(5)]
	_ = x[SelectableLow-(6)]
	_ = x[SelectableMid-(7)]
	_ = x[SelectableInternalSegment-(8)]
	_ = x[SelectableInternalSegmentA-(9)]
	_ = x[SelectableInternalSegmentB-(10)]
	_ = x[SelectableBody-(11)]
}

var _SelectableTypeValues = []SelectableType{SelectableEntity, SelectableSector, SelectableSectorSegment, SelectableCeiling, SelectableFloor, SelectableHi, SelectableLow, SelectableMid, SelectableInternalSegment, SelectableInternalSegmentA, SelectableInternalSegmentB, SelectableBody}

var _SelectableTypeNameToValueMap = map[string]SelectableType{
	_SelectableTypeName[0:16]:         SelectableEntity,
	_SelectableTypeLowerName[0:16]:    SelectableEntity,
	_SelectableTypeName[16:32]:        SelectableSector,
	_SelectableTypeLowerName[16:32]:   SelectableSector,
	_SelectableTypeName[32:55]:        SelectableSectorSegment,
	_SelectableTypeLowerName[32:55]:   SelectableSectorSegment,
	_SelectableTypeName[55:72]:        SelectableCeiling,
	_SelectableTypeLowerName[55:72]:   SelectableCeiling,
	_SelectableTypeName[72:87]:        SelectableFloor,
	_SelectableTypeLowerName[72:87]:   SelectableFloor,
	_SelectableTypeName[87:99]:        SelectableHi,
	_SelectableTypeLowerName[87:99]:   SelectableHi,
	_SelectableTypeName[99:112]:       SelectableLow,
	_SelectableTypeLowerName[99:112]:  SelectableLow,
	_SelectableTypeName[112:125]:      SelectableMid,
	_SelectableTypeLowerName[112:125]: SelectableMid,
	_SelectableTypeName[125:150]:      SelectableInternalSegment,
	_SelectableTypeLowerName[125:150]: SelectableInternalSegment,
	_SelectableTypeName[150:176]:      SelectableInternalSegmentA,
	_SelectableTypeLowerName[150:176]: SelectableInternalSegmentA,
	_SelectableTypeName[176:202]:      SelectableInternalSegmentB,
	_SelectableTypeLowerName[176:202]: SelectableInternalSegmentB,
	_SelectableTypeName[202:216]:      SelectableBody,
	_SelectableTypeLowerName[202:216]: SelectableBody,
}

var _SelectableTypeNames = []string{
	_SelectableTypeName[0:16],
	_SelectableTypeName[16:32],
	_SelectableTypeName[32:55],
	_SelectableTypeName[55:72],
	_SelectableTypeName[72:87],
	_SelectableTypeName[87:99],
	_SelectableTypeName[99:112],
	_SelectableTypeName[112:125],
	_SelectableTypeName[125:150],
	_SelectableTypeName[150:176],
	_SelectableTypeName[176:202],
	_SelectableTypeName[202:216],
}

// SelectableTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func SelectableTypeString(s string) (SelectableType, error) {
	if val, ok := _SelectableTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _SelectableTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to SelectableType values", s)
}

// SelectableTypeValues returns all values of the enum
func SelectableTypeValues() []SelectableType {
	return _SelectableTypeValues
}

// SelectableTypeStrings returns a slice of all String values of the enum
func SelectableTypeStrings() []string {
	strs := make([]string, len(_SelectableTypeNames))
	copy(strs, _SelectableTypeNames)
	return strs
}

// IsASelectableType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i SelectableType) IsASelectableType() bool {
	for _, v := range _SelectableTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for SelectableType
func (i SelectableType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for SelectableType
func (i *SelectableType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("SelectableType should be a string, got %s", data)
	}

	var err error
	*i, err = SelectableTypeString(s)
	return err
}
