// Code generated by ecs/cmd/gofoom_ecs_generator. DO NOT EDIT.
package core

import "tlyakhov/gofoom/ecs"

var BodyCID ecs.ComponentID
var InternalSegmentCID ecs.ComponentID
var LightCID ecs.ComponentID
var MobileCID ecs.ComponentID
var QuadtreeCID ecs.ComponentID
var SectorCID ecs.ComponentID

func init() {
	BodyCID = ecs.RegisterComponent(&ecs.Arena[Body, *Body]{})
	InternalSegmentCID = ecs.RegisterComponent(&ecs.Arena[InternalSegment, *InternalSegment]{})
	LightCID = ecs.RegisterComponent(&ecs.Arena[Light, *Light]{})
	MobileCID = ecs.RegisterComponent(&ecs.Arena[Mobile, *Mobile]{})
	QuadtreeCID = ecs.RegisterComponent(&ecs.Arena[Quadtree, *Quadtree]{})
	SectorCID = ecs.RegisterComponent(&ecs.Arena[Sector, *Sector]{})
}
func GetBody(e ecs.Entity) *Body {
	if asserted, ok := ecs.Component(e, BodyCID).(*Body); ok {
		return asserted
	}
	return nil
}

func (*Body) ComponentID() ecs.ComponentID {
	return BodyCID
}
func GetInternalSegment(e ecs.Entity) *InternalSegment {
	if asserted, ok := ecs.Component(e, InternalSegmentCID).(*InternalSegment); ok {
		return asserted
	}
	return nil
}

func (*InternalSegment) ComponentID() ecs.ComponentID {
	return InternalSegmentCID
}
func GetLight(e ecs.Entity) *Light {
	if asserted, ok := ecs.Component(e, LightCID).(*Light); ok {
		return asserted
	}
	return nil
}

func (*Light) ComponentID() ecs.ComponentID {
	return LightCID
}
func GetMobile(e ecs.Entity) *Mobile {
	if asserted, ok := ecs.Component(e, MobileCID).(*Mobile); ok {
		return asserted
	}
	return nil
}

func (*Mobile) ComponentID() ecs.ComponentID {
	return MobileCID
}
func GetQuadtree(e ecs.Entity) *Quadtree {
	panic("Tried to GetQuadtree, which is a singleton. use ecs.Singleton instead")
}

func (*Quadtree) ComponentID() ecs.ComponentID {
	return QuadtreeCID
}
func GetSector(e ecs.Entity) *Sector {
	if asserted, ok := ecs.Component(e, SectorCID).(*Sector); ok {
		return asserted
	}
	return nil
}

func (*Sector) ComponentID() ecs.ComponentID {
	return SectorCID
}
