// Code generated by "enumer -type=DoorBehavior -json"; DO NOT EDIT.

package sectors

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _DoorBehaviorName = "OpenOpeningClosingClosed"

var _DoorBehaviorIndex = [...]uint8{0, 4, 11, 18, 24}

const _DoorBehaviorLowerName = "openopeningclosingclosed"

func (i DoorBehavior) String() string {
	if i < 0 || i >= DoorBehavior(len(_DoorBehaviorIndex)-1) {
		return fmt.Sprintf("DoorBehavior(%d)", i)
	}
	return _DoorBehaviorName[_DoorBehaviorIndex[i]:_DoorBehaviorIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _DoorBehaviorNoOp() {
	var x [1]struct{}
	_ = x[Open-(0)]
	_ = x[Opening-(1)]
	_ = x[Closing-(2)]
	_ = x[Closed-(3)]
}

var _DoorBehaviorValues = []DoorBehavior{Open, Opening, Closing, Closed}

var _DoorBehaviorNameToValueMap = map[string]DoorBehavior{
	_DoorBehaviorName[0:4]:        Open,
	_DoorBehaviorLowerName[0:4]:   Open,
	_DoorBehaviorName[4:11]:       Opening,
	_DoorBehaviorLowerName[4:11]:  Opening,
	_DoorBehaviorName[11:18]:      Closing,
	_DoorBehaviorLowerName[11:18]: Closing,
	_DoorBehaviorName[18:24]:      Closed,
	_DoorBehaviorLowerName[18:24]: Closed,
}

var _DoorBehaviorNames = []string{
	_DoorBehaviorName[0:4],
	_DoorBehaviorName[4:11],
	_DoorBehaviorName[11:18],
	_DoorBehaviorName[18:24],
}

// DoorBehaviorString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func DoorBehaviorString(s string) (DoorBehavior, error) {
	if val, ok := _DoorBehaviorNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _DoorBehaviorNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to DoorBehavior values", s)
}

// DoorBehaviorValues returns all values of the enum
func DoorBehaviorValues() []DoorBehavior {
	return _DoorBehaviorValues
}

// DoorBehaviorStrings returns a slice of all String values of the enum
func DoorBehaviorStrings() []string {
	strs := make([]string, len(_DoorBehaviorNames))
	copy(strs, _DoorBehaviorNames)
	return strs
}

// IsADoorBehavior returns "true" if the value is listed in the enum definition. "false" otherwise
func (i DoorBehavior) IsADoorBehavior() bool {
	for _, v := range _DoorBehaviorValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for DoorBehavior
func (i DoorBehavior) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for DoorBehavior
func (i *DoorBehavior) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("DoorBehavior should be a string, got %s", data)
	}

	var err error
	*i, err = DoorBehaviorString(s)
	return err
}
