// Code generated by "enumer -type=DoorIntent -json"; DO NOT EDIT.

package sectors

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _DoorIntentName = "DoorIntentResetDoorIntentOpenDoorIntentClosed"

var _DoorIntentIndex = [...]uint8{0, 15, 29, 45}

const _DoorIntentLowerName = "doorintentresetdoorintentopendoorintentclosed"

func (i DoorIntent) String() string {
	if i < 0 || i >= DoorIntent(len(_DoorIntentIndex)-1) {
		return fmt.Sprintf("DoorIntent(%d)", i)
	}
	return _DoorIntentName[_DoorIntentIndex[i]:_DoorIntentIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _DoorIntentNoOp() {
	var x [1]struct{}
	_ = x[DoorIntentReset-(0)]
	_ = x[DoorIntentOpen-(1)]
	_ = x[DoorIntentClosed-(2)]
}

var _DoorIntentValues = []DoorIntent{DoorIntentReset, DoorIntentOpen, DoorIntentClosed}

var _DoorIntentNameToValueMap = map[string]DoorIntent{
	_DoorIntentName[0:15]:       DoorIntentReset,
	_DoorIntentLowerName[0:15]:  DoorIntentReset,
	_DoorIntentName[15:29]:      DoorIntentOpen,
	_DoorIntentLowerName[15:29]: DoorIntentOpen,
	_DoorIntentName[29:45]:      DoorIntentClosed,
	_DoorIntentLowerName[29:45]: DoorIntentClosed,
}

var _DoorIntentNames = []string{
	_DoorIntentName[0:15],
	_DoorIntentName[15:29],
	_DoorIntentName[29:45],
}

// DoorIntentString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func DoorIntentString(s string) (DoorIntent, error) {
	if val, ok := _DoorIntentNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _DoorIntentNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to DoorIntent values", s)
}

// DoorIntentValues returns all values of the enum
func DoorIntentValues() []DoorIntent {
	return _DoorIntentValues
}

// DoorIntentStrings returns a slice of all String values of the enum
func DoorIntentStrings() []string {
	strs := make([]string, len(_DoorIntentNames))
	copy(strs, _DoorIntentNames)
	return strs
}

// IsADoorIntent returns "true" if the value is listed in the enum definition. "false" otherwise
func (i DoorIntent) IsADoorIntent() bool {
	for _, v := range _DoorIntentValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for DoorIntent
func (i DoorIntent) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for DoorIntent
func (i *DoorIntent) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("DoorIntent should be a string, got %s", data)
	}

	var err error
	*i, err = DoorIntentString(s)
	return err
}
